// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: ApprovalRecord (approval module)
// Contract freeze: the aggregate + status enum are defined and serde
// round-trip; transition logic lands in ISSUE-APPROVALRECORD (#789).

use chrono::{Duration, Utc};
use rigorix_engine::approval::domain::{
    ApprovalRecord, ApprovalStatus, DecisionContext, IntentHash,
};
use serde_json::json;
use uuid::Uuid;

fn sample_record() -> ApprovalRecord {
    ApprovalRecord {
        step_name: "deploy".to_string(),
        node_id: Uuid::new_v4(),
        intent_hash: IntentHash("intent-digest".to_string()),
        intent_payload: json!({"tool": "run_command", "command": "deploy.sh"}),
        approver_id: "user@org".to_string(),
        authority: Some("role:operator".to_string()),
        decided_at: Utc::now(),
        expires_at: Utc::now() + Duration::minutes(30),
        nonce: Uuid::new_v4(),
        token_claims_ref: Some("tok-claims-ref".to_string()),
        status: ApprovalStatus::Pending,
        decision_context: DecisionContext {
            rendered_step: "deploy.sh --env prod".to_string(),
            upstream_evidence: None,
            state_snapshot: Some(json!({"git": "abc123", "branch": "main"})),
            summary: "deploy to prod".to_string(),
            full_payload: None,
        },
    }
}

#[test]
fn test_approvalrecord_is_defined() {
    let record = sample_record();
    assert_eq!(record.status, ApprovalStatus::Pending);
    assert_eq!(record.approver_id, "user@org");
    assert!(record.expires_at > record.decided_at);
}

#[test]
fn test_approvalrecord_serde_round_trip_preserves_all_fields() {
    let record = sample_record();
    let encoded = serde_json::to_string(&record).expect("serialize");
    let decoded: ApprovalRecord = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, record);
}

#[test]
fn test_approval_status_variants_are_frozen() {
    let pending = ApprovalStatus::Pending;
    assert!(matches!(pending, ApprovalStatus::Pending));
    // Valid terminal transitions (single-use): Pending → Consumed | Expired | Superseded.
    assert!(matches!(ApprovalStatus::Consumed, ApprovalStatus::Consumed));
    assert!(matches!(ApprovalStatus::Expired, ApprovalStatus::Expired));
    assert!(matches!(
        ApprovalStatus::Superseded,
        ApprovalStatus::Superseded
    ));
}

// ── #789 behavior: status transitions ────────────────────────────────────────

#[test]
fn test_consume_transitions_pending_to_consumed() {
    let mut record = sample_record();
    assert!(record.consume().is_ok());
    assert_eq!(record.status, ApprovalStatus::Consumed);
}

#[test]
fn test_consumed_record_cannot_be_replayed() {
    // Single-use semantics: a second consume is rejected (replay guard).
    let mut record = sample_record();
    record.consume().unwrap();
    let err = record.consume().unwrap_err();
    assert!(matches!(
        err,
        rigorix_engine::approval::domain::ApprovalError::AlreadyConsumed(_)
    ));
    // A consumed approval must never transition to another terminal state.
    assert!(record.supersede().is_err());
}

#[test]
fn test_expire_transitions_pending_to_expired() {
    let mut record = sample_record();
    assert!(record.expire().is_ok());
    assert_eq!(record.status, ApprovalStatus::Expired);
    // Expired approvals never dispatch — a consume attempt fails with Expired.
    let err = record.consume().unwrap_err();
    assert!(matches!(
        err,
        rigorix_engine::approval::domain::ApprovalError::Expired(_)
    ));
}

#[test]
fn test_supersede_transitions_pending_to_superseded() {
    // Re-plan / newer approval / cancelled-and-re-executed run → superseded.
    let mut record = sample_record();
    assert!(record.supersede().is_ok());
    assert_eq!(record.status, ApprovalStatus::Superseded);
    assert!(record.consume().is_err());
}

#[test]
fn test_expired_after_ttl_never_dispatches() {
    let mut record = sample_record();
    let past = record.expires_at + Duration::seconds(1);
    assert!(record.is_expired_at(past));
    // Enforced at verification: TTL lapse → Expired, no dispatch.
    assert!(record.enforce_ttl(past).is_err());
    assert_eq!(record.status, ApprovalStatus::Expired);
    let before = record.decided_at + Duration::seconds(1);
    let fresh = sample_record();
    assert!(!fresh.is_expired_at(before));
}

#[test]
fn test_non_terminal_interruption_keeps_pending() {
    // Cross-process resume: a paused run never consumed the approval, so a
    // resumed run can verify and continue.
    let record = sample_record();
    assert_eq!(record.status, ApprovalStatus::Pending);
    // Pausing is not a terminal outcome — nothing to consume yet.
    assert!(record.is_pending());
}
