// Generated by Guardian TDD
// From: AuditFormatter (Domain Service) (audit-tools module)
// Tests the AuditFormatterImpl.

#[cfg(test)]
mod tests {
    use chrono::{Duration, Utc};
    use uuid::Uuid;

    use rigorix_mcp::audit_tools::domain::entity::AuditFormatter;
    use rigorix_mcp::audit_tools::domain::formatter_impl::AuditFormatterImpl;
    use rigorix_mcp::audit_tools::domain::value::{
        AuditEnvelope, AuditSummary, ExecutionStep, TopFailure, TopTemplate,
    };
    use rigorix_mcp::execution_tools::domain::value::ExecutionStatus;

    fn sample_envelope() -> AuditEnvelope {
        let now = Utc::now();
        AuditEnvelope::new(
            Uuid::nil(),
            ExecutionStatus::Completed,
            Some("test-template".into()),
            now - Duration::hours(1),
            now,
            5000,
            vec![ExecutionStep::new(
                "build".into(),
                true,
                None,
                serde_json::json!({"output": "ok"}),
                2000,
            )],
            Some(150),
            "abc123hmac".into(),
            vec![],
        )
    }

    fn sample_summary() -> AuditSummary {
        let now = Utc::now();
        AuditSummary::new(
            now - Duration::days(7),
            now,
            10,
            7,
            3,
            0.7,
            50000,
            Some(1500),
            vec![TopFailure::new(
                "Timeout error".into(),
                2,
                Some("code-review".into()),
            )],
            vec![TopTemplate::new("code-review".into(), 5, 10000)],
        )
    }

    #[test]
    fn test_auditformatter_format_audit_text() {
        let formatter = AuditFormatterImpl::new();
        let envelope = sample_envelope();
        let text = formatter.format_audit_text(&envelope);

        assert!(text.contains(&Uuid::nil().to_string()));
        assert!(text.contains("Completed"));
        assert!(text.contains("test-template"));
        assert!(text.contains("5000 ms"));
    }

    #[test]
    fn test_auditformatter_format_audit_json() {
        let formatter = AuditFormatterImpl::new();
        let envelope = sample_envelope();
        let json = formatter.format_audit_json(&envelope);

        assert_eq!(
            json["execution_id"].as_str().unwrap(),
            Uuid::nil().to_string()
        );
        assert!(json["status"].as_str().unwrap().contains("Completed"));
        assert!(json["steps"].is_array());
    }

    #[test]
    fn test_auditformatter_format_list_text() {
        let formatter = AuditFormatterImpl::new();
        let envelopes = vec![sample_envelope(), sample_envelope()];
        let text = formatter.format_list_text(&envelopes);

        assert!(text.contains("2 total"));
    }

    #[test]
    fn test_auditformatter_format_list_text_empty() {
        let formatter = AuditFormatterImpl::new();
        let text = formatter.format_list_text(&[]);

        assert!(text.contains("No audit records"));
    }

    #[test]
    fn test_auditformatter_format_list_json() {
        let formatter = AuditFormatterImpl::new();
        let envelopes = vec![sample_envelope()];
        let json = formatter.format_list_json(&envelopes);

        assert_eq!(json["total_count"].as_u64().unwrap(), 1);
        assert!(json["audits"].is_array());
    }

    #[test]
    fn test_auditformatter_format_summary_text() {
        let formatter = AuditFormatterImpl::new();
        let summary = sample_summary();
        let text = formatter.format_summary_text(&summary);

        assert!(text.contains("10"));
        assert!(text.contains("7"));
        assert!(text.contains("3"));
        assert!(text.contains("70.0%"));
        assert!(text.contains("code-review"));
    }

    #[test]
    fn test_auditformatter_format_summary_json() {
        let formatter = AuditFormatterImpl::new();
        let summary = sample_summary();
        let json = formatter.format_summary_json(&summary);

        assert_eq!(json["total_executions"].as_u64().unwrap(), 10);
        assert_eq!(json["success_count"].as_u64().unwrap(), 7);
        assert_eq!(json["failure_count"].as_u64().unwrap(), 3);
        assert!((json["success_rate"].as_f64().unwrap() - 0.7).abs() < 0.001);
        assert!(json["top_failures"].is_array());
        assert!(json["top_templates"].is_array());
    }
}
