//! Data Transfer Objects for the Planning Pipeline module.
//!
//! @canonical .pi/architecture/modules/planning-pipeline.md
//! Implements: Contract Freeze — DTO schemas for planning pipeline operations
//! Issue: issue-contract-freeze
//!
//! DTOs define the input/output contracts for service operations.
//! They carry validation metadata and documentation but no behavior.
//!
//! # Contract (Frozen)
//! - Every service operation has a dedicated input and output DTO
//! - DTOs are serializable (JSON for API)
//! - Validation constraints are documented in field docs
//! - Fields use reasonable Rust types (no framework-specific annotations)

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

use crate::dag_engine::domain::TaskGraph;
use crate::planning::domain::classification::{ClassificationResult, ClassifiedTemplate};
use crate::planning::domain::intent::UserIntent;
use crate::planning::domain::result::{PlanningResult, TemplateSummary};

// ---------------------------------------------------------------------------
// Plan DTOs (full 6-phase flow)
// ---------------------------------------------------------------------------

/// Input for the full `plan()` flow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanInput {
    /// The user's raw intent.
    pub intent: UserIntent,

    /// Execution ID for correlation (generated if not provided).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<Uuid>,

    /// Whether to fall back to template generator on low confidence.
    #[serde(default = "default_true")]
    pub enable_generator_fallback: bool,

    /// Whether to skip validation (for development/debugging).
    #[serde(default)]
    pub skip_validation: bool,
}

fn default_true() -> bool {
    true
}

/// Output from the full `plan()` flow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanOutput {
    /// The planning result with template, confidence, params, and hash.
    pub planning_result: PlanningResult,

    /// Whether the plan was generated by the planner or via generator fallback.
    pub from_generator: bool,

    /// Whether clarification was required during the flow.
    pub clarification_used: bool,

    /// Number of LLM calls consumed in total.
    pub total_llm_calls: u32,

    /// Number of LLM tokens consumed in total.
    pub total_llm_tokens: u32,

    /// ISO 8601 timestamp of completion.
    pub completed_at: DateTime<Utc>,
}

// ---------------------------------------------------------------------------
// PlanWithGraph DTOs
// ---------------------------------------------------------------------------

/// Input for the `plan_with_graph()` flow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanWithGraphInput {
    /// The user's raw intent.
    pub intent: UserIntent,

    /// Execution ID for correlation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<Uuid>,

    /// Whether to enable generator fallback.
    #[serde(default = "default_true")]
    pub enable_generator_fallback: bool,

    /// Whether to skip validation.
    #[serde(default)]
    pub skip_validation: bool,
}

/// Output from the `plan_with_graph()` flow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanWithGraphOutput {
    /// The planning result.
    pub planning_result: PlanningResult,

    /// The generated TaskGraph (sealed and validated).
    pub graph: TaskGraph,

    /// Number of nodes in the graph.
    pub node_count: u32,

    /// Whether validation passed.
    pub validation_passed: bool,

    /// Validation warnings (non-blocking).
    #[serde(default)]
    pub validation_warnings: Vec<String>,

    /// Whether generator fallback was used.
    pub from_generator: bool,

    /// Whether clarification was used.
    pub clarification_used: bool,

    /// Total LLM calls consumed.
    pub total_llm_calls: u32,

    /// Total LLM tokens consumed.
    pub total_llm_tokens: u32,

    /// ISO 8601 timestamp.
    pub completed_at: DateTime<Utc>,
}

// ---------------------------------------------------------------------------
// CheckBudget DTOs
// ---------------------------------------------------------------------------

/// Input for budget pre-check.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckBudgetInput {
    /// The execution ID.
    pub execution_id: Uuid,

    /// Number of LLM calls required (defaults to 2 for classify + extract).
    #[serde(default = "default_min_calls")]
    pub required_calls: u32,
}

fn default_min_calls() -> u32 {
    2
}

/// Output from budget pre-check.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckBudgetOutput {
    /// Whether the budget has sufficient capacity.
    pub has_capacity: bool,

    /// Remaining LLM calls.
    pub remaining_calls: u32,

    /// Remaining LLM tokens.
    pub remaining_tokens: u32,

    /// Maximum allowed calls.
    pub max_calls: u32,

    /// Maximum allowed tokens.
    pub max_tokens: u32,

    /// Whether the budget will be exhausted after this planning operation.
    pub will_exhaust: bool,
}

// ---------------------------------------------------------------------------
// ExtractParameters DTOs
// ---------------------------------------------------------------------------

/// Input for standalone parameter extraction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtractParametersInput {
    /// The execution ID.
    pub execution_id: Uuid,

    /// The user intent with optional clarifications.
    pub intent: UserIntent,

    /// The template ID to extract parameters for.
    pub template_id: String,

    /// The list of parameter names to extract.
    pub parameter_names: Vec<String>,
}

/// Output from standalone parameter extraction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtractParametersOutput {
    /// The template ID.
    pub template_id: String,

    /// Resolved key-value parameters.
    pub parameters: HashMap<String, String>,

    /// Extra parameters found but not defined.
    #[serde(default)]
    pub extra_parameters: HashMap<String, String>,

    /// Missing required parameters.
    #[serde(default)]
    pub missing_parameters: Vec<String>,

    /// Whether all required parameters were extracted.
    pub complete: bool,

    /// LLM calls used.
    pub llm_calls_used: u32,

    /// LLM tokens used.
    pub llm_tokens_used: u32,
}

// ---------------------------------------------------------------------------
// GenerateGraph DTOs
// ---------------------------------------------------------------------------

/// Input for standalone graph generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateGraphInput {
    /// The execution ID.
    pub execution_id: Uuid,

    /// The template ID to generate from.
    pub template_id: String,

    /// Resolved parameter values.
    pub parameters: HashMap<String, String>,

    /// Whether to seal the graph after generation.
    #[serde(default = "default_true")]
    pub seal_graph: bool,
}

/// Output from standalone graph generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateGraphOutput {
    /// The generated TaskGraph.
    pub graph: TaskGraph,

    /// Number of nodes in the graph.
    pub node_count: u32,

    /// Whether the graph was sealed.
    pub sealed: bool,

    /// Whether the graph was generated from a built-in template or generator.
    pub from_generator: bool,
}

// ---------------------------------------------------------------------------
// ValidatePlan DTOs
// ---------------------------------------------------------------------------

/// Input for standalone plan validation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidatePlanInput {
    /// The execution ID.
    pub execution_id: Uuid,

    /// The TaskGraph to validate.
    pub graph: TaskGraph,

    /// The template ID that generated this graph.
    pub template_id: String,

    /// Whether to check all validation rules or just structural ones.
    #[serde(default = "default_true")]
    pub full_validation: bool,
}

/// Output from standalone plan validation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidatePlanOutput {
    /// Whether the plan passed all validation checks.
    pub passed: bool,

    /// Validation errors (blocking).
    pub errors: Vec<ValidationError>,

    /// Validation warnings (non-blocking).
    pub warnings: Vec<ValidationWarning>,

    /// Number of checks performed.
    pub checks_performed: u32,
}

/// A validation error (blocking — plan cannot proceed).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationError {
    /// Human-readable error message.
    pub message: String,

    /// The validation rule that failed.
    pub rule: String,

    /// The node ID that triggered the error (if applicable).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
}

/// A validation warning (non-blocking — plan can proceed).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationWarning {
    /// Human-readable warning message.
    pub message: String,

    /// The validation rule that triggered this warning.
    pub rule: String,

    /// The node ID that triggered the warning (if applicable).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
}

// ---------------------------------------------------------------------------
// RequestClarification DTOs
// ---------------------------------------------------------------------------

/// Input for requesting clarification from the user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestClarificationInput {
    /// The execution ID.
    pub execution_id: Uuid,

    /// The user's current intent with previous clarifications.
    pub intent: UserIntent,

    /// The classification result that triggered the clarification.
    pub classification: ClassificationResult,

    /// Optional specific question to ask (generated if not provided).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_question: Option<String>,
}

/// Output from requesting clarification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestClarificationOutput {
    /// The question to present to the user.
    pub question: String,

    /// The ambiguous templates that need disambiguation.
    pub ambiguous_templates: Vec<ClassifiedTemplate>,

    /// Suggested answers or options for the user.
    #[serde(default)]
    pub suggested_answers: Vec<String>,
}

// ---------------------------------------------------------------------------
// AvailableTemplates DTO
// ---------------------------------------------------------------------------

/// Output from listing available templates.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AvailableTemplatesOutput {
    /// Available templates with metadata.
    pub templates: Vec<TemplateSummary>,

    /// Total number of registered templates.
    pub total_count: u32,
}

// ---------------------------------------------------------------------------
// Clarification Round DTO
// ---------------------------------------------------------------------------

/// A single round of clarification with the user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClarificationRound {
    /// The question asked to the user.
    pub question: String,

    /// The user's response.
    pub answer: String,

    /// The classification result after this round.
    pub classification: ClassificationResult,

    /// ISO 8601 timestamp.
    pub timestamp: DateTime<Utc>,
}
