// Generated by Guardian TDD
// From: ValidateTemplateHandler (Domain Service) (template-tools module)
// Tests the frozen contract for ValidateTemplateHandler trait.

#[cfg(test)]
mod tests {
    use rigorix_mcp::template_tools::application::service::ValidateTemplateHandler;
    use rigorix_mcp::template_tools::domain::error::{HandlerError, ToolCallResult};
    use rigorix_mcp::template_tools::domain::value::{
        PlanTemplate, StepDefinition, ValidateTemplateInput,
    };

    /// Helper: create a minimal valid PlanTemplate for testing.
    fn make_test_template(name: &str) -> PlanTemplate {
        let step = StepDefinition::new(
            "step-1".into(),
            "test_tool".into(),
            serde_json::json!({}),
            false,
            "Test step".into(),
            None,
        );
        let now = chrono::Utc::now();
        PlanTemplate::new(
            name.into(),
            "Test description".into(),
            "1.0.0".into(),
            vec![],
            vec![step],
            None,
            std::collections::HashMap::new(),
            now,
            now,
        )
        .expect("Failed to create test template")
    }

    /// Mock handler for testing the ValidateTemplateHandler contract.
    struct MockValidateTemplateHandler;

    #[async_trait::async_trait]
    impl ValidateTemplateHandler for MockValidateTemplateHandler {
        async fn handle(
            &self,
            _input: &ValidateTemplateInput,
        ) -> Result<ToolCallResult, HandlerError> {
            let result = serde_json::json!({
                "valid": true,
                "warnings": [],
                "errors": [],
                "estimated_cost": null
            });
            Ok(ToolCallResult::success(result))
        }
    }

    #[tokio::test]
    async fn test_validate_template_handler_is_defined() {
        let handler = MockValidateTemplateHandler;
        let input = ValidateTemplateInput {
            plan: make_test_template("valid-template"),
        };
        let result = handler.handle(&input).await;
        assert!(result.is_ok(), "Handler should succeed");
    }

    #[tokio::test]
    async fn test_validate_template_handler_returns_validation_result() {
        let handler = MockValidateTemplateHandler;
        let input = ValidateTemplateInput {
            plan: make_test_template("check-me"),
        };
        let result = handler.handle(&input).await.expect("Handler should succeed");
        assert!(!result.is_error, "Result should not be an error");

        let content: serde_json::Value =
            serde_json::from_str(&result.content[0].text).expect("Should be valid JSON");
        assert!(content["valid"].as_bool().unwrap_or(false), "Template should be valid");
    }

    #[tokio::test]
    async fn test_validate_template_handler_returns_tool_call_result() {
        let handler = MockValidateTemplateHandler;
        let input = ValidateTemplateInput {
            plan: make_test_template("valid"),
        };
        let result = handler.handle(&input).await;
        assert!(result.is_ok(), "Should return Ok(ToolCallResult)");
        let tool_result = result.unwrap();
        assert!(!tool_result.content.is_empty(), "Should have content");
    }

    #[tokio::test]
    async fn test_validate_template_handler_is_send_sync() {
        let handler = MockValidateTemplateHandler;
        let boxed: Box<dyn ValidateTemplateHandler> = Box::new(handler);
        let _ = boxed;
    }
}
