// Generated by Guardian TDD
// From: AuthService (Application) (auth module)
// TDD Contract: AuthService trait with login, poll, status, refresh, logout, attest

#![allow(unused_imports)]

use async_trait::async_trait;

use rigorix_engine::identity::IdentityClaim;
use rigorix_mcp::auth::application::dto::{
    LoginInput, LoginOutput, LogoutInput, LogoutOutput, PollInput, PollOutput, RefreshInput,
    RefreshOutput, StatusInput, StatusOutput, LOGGED_OUT_STATUS,
};
use rigorix_mcp::auth::application::service::AuthService;
use rigorix_mcp::auth::domain::error::AuthError;
use rigorix_mcp::auth::domain::flow::DeviceFlowStatus;
use rigorix_mcp::auth::domain::status::TokenStatus;

/// Minimal contract-conforming stub — proves the frozen AuthService trait is
/// implementable with the ISSUE-AUTH-1 method set. Real behavior + unit tests
/// live in src/auth/application/service_impl.rs.
struct AuthServiceTddContract;

#[async_trait]
impl AuthService for AuthServiceTddContract {
    async fn login(&self, _input: &LoginInput) -> Result<LoginOutput, AuthError> {
        Ok(LoginOutput {
            status: DeviceFlowStatus::Pending,
            verification_uri: "https://idp.example.com/device".into(),
            user_code: "ABCD-EFGH".into(),
            expires_in: 600,
        })
    }

    async fn poll(&self, _input: &PollInput) -> Result<PollOutput, AuthError> {
        Ok(PollOutput {
            status: DeviceFlowStatus::Pending,
            retry_after_secs: Some(5),
            reason: None,
            claim_summary: None,
        })
    }

    async fn status(&self, _input: &StatusInput) -> Result<StatusOutput, AuthError> {
        Ok(StatusOutput {
            status: TokenStatus::Unauthenticated,
            claim_summary: None,
            source: rigorix_engine::identity::IdentitySource::Unverified,
        })
    }

    async fn refresh(&self, _input: &RefreshInput) -> Result<RefreshOutput, AuthError> {
        Err(AuthError::NotAuthenticated)
    }

    async fn logout(&self, _input: &LogoutInput) -> Result<LogoutOutput, AuthError> {
        Ok(LogoutOutput::logged_out())
    }

    async fn attest(&self) -> Result<IdentityClaim, AuthError> {
        Err(AuthError::NotAuthenticated)
    }
}

#[test]
fn test_authservice_application_is_defined() {
    let service = AuthServiceTddContract;
    let rt = tokio::runtime::Runtime::new().unwrap();
    let result = rt.block_on(service.login(&LoginInput::default()));
    assert!(result.is_ok());
    let login = result.unwrap();
    assert_eq!(login.status, DeviceFlowStatus::Pending);
    assert_eq!(login.verification_uri, "https://idp.example.com/device");
    assert_eq!(login.user_code, "ABCD-EFGH");
}

#[test]
fn test_authservice_application_method_set_invokable() {
    let service = AuthServiceTddContract;
    let rt = tokio::runtime::Runtime::new().unwrap();

    let poll = rt.block_on(service.poll(&PollInput::default())).unwrap();
    assert_eq!(poll.status, DeviceFlowStatus::Pending);

    let status = rt.block_on(service.status(&StatusInput::default())).unwrap();
    assert_eq!(status.status, TokenStatus::Unauthenticated);

    let refresh = rt.block_on(service.refresh(&RefreshInput::default()));
    assert!(matches!(refresh.unwrap_err(), AuthError::NotAuthenticated));

    let logout = rt.block_on(service.logout(&LogoutInput::default())).unwrap();
    assert_eq!(logout.status, LOGGED_OUT_STATUS);

    let attest = rt.block_on(service.attest());
    assert!(matches!(attest.unwrap_err(), AuthError::NotAuthenticated));
}
