// Generated by Guardian TDD
// From: CheckEnforcementHandler (Domain Service) (execution-tools module)
// TDD Contract: CheckEnforcementHandler trait with handle()

use std::sync::Arc;

use async_trait::async_trait;

use rigorix_mcp::execution_tools::application::service::CheckEnforcementHandler;
use rigorix_mcp::execution_tools::application::service_impl::CheckEnforcementHandlerImpl;
use rigorix_mcp::execution_tools::domain::entity::EngineFacade;
use rigorix_mcp::execution_tools::domain::error::EngineFacadeError;
use rigorix_mcp::execution_tools::domain::value::{
    BudgetStatus, CostBreakdown, EnforcementStatus, ExecutionId, ExecutionResult, ExecutionStatus,
    PlanTemplate, ValidationResult,
};

struct MockEngineForEnforcer;

#[async_trait]
impl EngineFacade for MockEngineForEnforcer {
    async fn execute(
        &self,
        _plan: PlanTemplate,
        _repository: Option<String>,
        _author: Option<String>,
    ) -> Result<ExecutionResult, EngineFacadeError> {
        Ok(ExecutionResult::new(
            uuid::Uuid::nil(),
            ExecutionStatus::Completed,
            vec![],
            0,
            None,
            String::new(),
        ))
    }
    async fn validate_plan(&self, _p: PlanTemplate) -> Result<ValidationResult, EngineFacadeError> {
        Ok(ValidationResult::new(true, vec![], vec![], None))
    }
    async fn check_enforcement(&self) -> Result<EnforcementStatus, EngineFacadeError> {
        Ok(EnforcementStatus::new(
            true,
            "strict".into(),
            BudgetStatus {
                tool_calls_total: 100,
                tool_calls_remaining: 50,
                tokens_total: 10000,
                tokens_remaining: 5000,
            },
            vec![],
        ))
    }
    async fn get_execution_cost(
        &self,
        _id: &ExecutionId,
    ) -> Result<CostBreakdown, EngineFacadeError> {
        Err(EngineFacadeError::ExecutionNotFound(uuid::Uuid::nil()))
    }

    async fn run_template(
        &self,
        _template_name: &str,
        _repository: Option<String>,
        _author: Option<String>,
    ) -> Result<ExecutionResult, EngineFacadeError> {
        Ok(ExecutionResult::new(
            uuid::Uuid::nil(),
            ExecutionStatus::Completed,
            vec![],
            0,
            None,
            String::new(),
        ))
    }
    async fn approve_execution(
        &self,
        execution_id: &ExecutionId,
        step_names: Vec<String>,
    ) -> Result<rigorix_mcp::execution_tools::domain::value::ApprovalResult, EngineFacadeError>
    {
        Ok(
            rigorix_mcp::execution_tools::domain::value::ApprovalResult::new(
                *execution_id.as_uuid(),
                step_names,
                vec![],
                vec![],
                true,
            ),
        )
    }
}

#[test]
fn test_checkenforcementhandler_is_defined() {
    let engine: Arc<dyn EngineFacade> = Arc::new(MockEngineForEnforcer);
    let _handler = CheckEnforcementHandlerImpl::new(engine);
}

#[test]
fn test_checkenforcementhandler_checks_status() {
    let rt = tokio::runtime::Runtime::new().unwrap();
    let engine: Arc<dyn EngineFacade> = Arc::new(MockEngineForEnforcer);
    let handler = CheckEnforcementHandlerImpl::new(engine);
    let result = rt.block_on(handler.handle());
    assert!(result.is_ok());
    let tc = result.unwrap();
    assert!(!tc.is_error);
    assert!(tc.content[0].text.contains("strict"));
}
