// Generated by Guardian TDD
// From: ExecuteHandler (Domain Service) (execution-tools module)
// TDD Contract: ExecuteHandler trait with handle(ExecuteInput) and timeout_duration()

#![allow(unused_imports)]

use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;

use rigorix_mcp::execution_tools::application::dto::ExecuteInput;
use rigorix_mcp::execution_tools::application::service::ExecuteHandler;
use rigorix_mcp::execution_tools::application::service_impl::ExecuteHandlerImpl;
use rigorix_mcp::execution_tools::domain::entity::EngineFacade;
use rigorix_mcp::execution_tools::domain::error::{EngineFacadeError, ToolCallResult};
use rigorix_mcp::execution_tools::domain::value::{
    CostBreakdown, EnforcementStatus, ExecutionId, ExecutionResult, ExecutionStatus, PlanTemplate,
    StepDefinition, StepResult, ValidationResult,
};

use std::collections::HashMap;

struct MockEngineForHandler;

#[async_trait]
impl EngineFacade for MockEngineForHandler {
    async fn execute(
        &self,
        _plan: PlanTemplate,
        _repository: Option<String>,
        _author: Option<String>,
    ) -> Result<ExecutionResult, EngineFacadeError> {
        Ok(ExecutionResult::new(
            uuid::Uuid::nil(),
            ExecutionStatus::Completed,
            vec![StepResult::new(
                "s1".into(),
                true,
                None,
                serde_json::json!({}),
                50,
            )],
            100,
            Some(50),
            "rigorix://audit/test".into(),
        ))
    }
    async fn validate_plan(&self, _p: PlanTemplate) -> Result<ValidationResult, EngineFacadeError> {
        Ok(ValidationResult::new(true, vec![], vec![], None))
    }
    async fn check_enforcement(&self) -> Result<EnforcementStatus, EngineFacadeError> {
        Err(EngineFacadeError::EngineNotAvailable("mock".into()))
    }
    async fn get_execution_cost(
        &self,
        _id: &ExecutionId,
    ) -> Result<CostBreakdown, EngineFacadeError> {
        Err(EngineFacadeError::ExecutionNotFound(uuid::Uuid::nil()))
    }

    async fn run_template(
        &self,
        _template_name: &str,
        _repository: Option<String>,
        _author: Option<String>,
    ) -> Result<ExecutionResult, EngineFacadeError> {
        Ok(ExecutionResult::new(
            uuid::Uuid::nil(),
            ExecutionStatus::Completed,
            vec![StepResult::new(
                "s1".into(),
                true,
                None,
                serde_json::json!({}),
                50,
            )],
            100,
            Some(50),
            "rigorix://audit/test".into(),
        ))
    }
    async fn approve_execution(
        &self,
        execution_id: &ExecutionId,
        step_names: Vec<String>,
        _identity: Option<rigorix_mcp::execution_tools::domain::value::ApprovalIdentity>,
    ) -> Result<rigorix_mcp::execution_tools::domain::value::ApprovalResult, EngineFacadeError>
    {
        Ok(
            rigorix_mcp::execution_tools::domain::value::ApprovalResult::new(
                *execution_id.as_uuid(),
                step_names,
                vec![],
                vec![],
                true,
            ),
        )
    }

    async fn execution_state(
        &self,
        _: &ExecutionId,
    ) -> Result<rigorix_mcp::execution_tools::domain::value::ExecutionStateInfo, EngineFacadeError>
    {
        unimplemented!("mock execution_state not needed by current tests")
    }
}

#[test]
fn test_executehandler_is_defined() {
    let engine: Arc<dyn EngineFacade> = Arc::new(MockEngineForHandler);
    let _handler = ExecuteHandlerImpl::new(engine, Duration::from_secs(60));
    // ExecuteHandlerImpl constructable — contract satisfied
}

#[test]
fn test_executehandler_has_timeout() {
    let engine: Arc<dyn EngineFacade> = Arc::new(MockEngineForHandler);
    let handler = ExecuteHandlerImpl::new(engine, Duration::from_secs(120));
    assert_eq!(handler.timeout_duration(), Duration::from_secs(120));
}

#[test]
fn test_executehandler_handles_execution() {
    let rt = tokio::runtime::Runtime::new().unwrap();
    let engine: Arc<dyn EngineFacade> = Arc::new(MockEngineForHandler);
    let handler = ExecuteHandlerImpl::new(engine, Duration::from_secs(60));
    let plan = PlanTemplate::new(
        "t".into(),
        "d".into(),
        vec![StepDefinition::new(
            "s1".into(),
            "tool".into(),
            serde_json::json!({}),
            false,
            "d".into(),
            None,
        )],
        None,
        HashMap::new(),
    )
    .unwrap();
    let result = rt.block_on(handler.handle(ExecuteInput {
        plan: Some(plan),
        template_name: None,
        execution_id: None,
        repository: None,
        author: None,
    }));
    assert!(result.is_ok());
    assert!(!result.unwrap().is_error);
}
