// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionFinding (consequence-gating module)
// Contract freeze: the envelope finding + `PreconditionChecked` event payload
// and the SpanPrivacy redaction boundary are frozen here; envelope emission
// lands in ISSUE-CONSEQUENCE-GATING-8.

use chrono::Utc;
use rigorix_engine::precondition::domain::{
    AttributionReason, PreconditionChecked, PreconditionFinding, PreconditionOutcome,
};
use serde_json::json;

fn finding(outcome: PreconditionOutcome, exit_code: Option<i32>) -> PreconditionFinding {
    PreconditionFinding {
        precondition_id: "beneficiary-eligible".to_string(),
        step: "pay".to_string(),
        outcome,
        exit_code,
        inputs_hash: "sha256:deadbeef".to_string(),
        checked_at: Utc::now(),
        summary: None,
        check_digest: None,
        authority_digest: None,
        check_writable: None,
        attribution: None,
    }
}

#[test]
fn test_preconditionfinding_is_defined() {
    let finding = finding(PreconditionOutcome::Failed, Some(3));
    assert_eq!(finding.precondition_id, "beneficiary-eligible");
    assert_eq!(finding.step, "pay");
    assert_eq!(finding.outcome, PreconditionOutcome::Failed);
    assert_eq!(finding.exit_code, Some(3));
}

#[test]
fn test_finding_records_outcome_exit_code_hash_and_timestamp() {
    let finding = finding(PreconditionOutcome::Passed, Some(0));
    let value = serde_json::to_value(&finding).expect("serialize");
    // Frozen evidence fields.
    assert_eq!(value["outcome"], "passed");
    assert_eq!(value["exit_code"], 0);
    assert_eq!(value["inputs_hash"], "sha256:deadbeef");
    assert!(value["checked_at"].is_string());
    // SpanPrivacy: no parameter values, no stdout by default.
    assert!(value.get("parameters").is_none());
    assert!(value.get("stdout").is_none());
}

#[test]
fn test_precondition_checked_event_payload_is_frozen() {
    let checked = PreconditionChecked {
        execution_id: uuid::Uuid::nil(),
        precondition_id: "beneficiary-eligible".to_string(),
        step: "pay".to_string(),
        outcome: PreconditionOutcome::Error,
        exit_code: None,
        inputs_hash: "sha256:deadbeef".to_string(),
        summary: "precondition 'beneficiary-eligible' error step 'pay'".to_string(),
        check_digest: None,
        authority_digest: None,
        check_writable: None,
        attribution: None,
        timestamp: Utc::now(),
    };
    let encoded = serde_json::to_string(&checked).expect("serialize");
    let decoded: PreconditionChecked = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, checked);
    // An indeterminate error carries no exit code, and is distinct from failed.
    assert_eq!(decoded.outcome, PreconditionOutcome::Error);
    assert_eq!(json!(decoded.outcome.as_str()), json!("error"));
}

#[test]
fn test_decision_summary_redacts_values() {
    let summary = finding(PreconditionOutcome::Failed, Some(1)).decision_summary();
    assert!(summary.contains("beneficiary-eligible"));
    assert!(summary.contains("failed"));
    assert!(summary.contains("exit 1"));
    assert!(!summary.contains("acct-"));
}

#[tokio::test]
async fn test_envelope_precondition_findings_records_evidence_and_redacts_values() {
    // AC #12: the signed envelope derives `precondition_findings[]` from the
    // run's `precondition_checked` events, carrying outcome + exit code +
    // inputs hash + timestamp, and NEVER parameter values or stdout.
    use rigorix_engine::audit::application::dto::BuildEnvelopeInput;
    use rigorix_engine::audit::application::envelope_factory_impl::AuditEnvelopeFactoryImpl;
    use rigorix_engine::audit::application::factory::AuditEnvelopeFactory;
    use rigorix_engine::audit::domain::{EventStatus, ExecutionEventRef};

    let factory = AuditEnvelopeFactoryImpl::default();
    let input = BuildEnvelopeInput {
        execution_id: uuid::Uuid::nil(),
        template_id: "payments".to_string(),
        planning_prompt: String::new(),
        events: vec![ExecutionEventRef {
            event_type: "precondition_checked".to_string(),
            summary: "Precondition 'beneficiary-eligible' failed for step 'pay'".to_string(),
            occurred_at: Utc::now(),
            correlation_id: None,
            status: EventStatus::Failure,
            payload: Some(json!({
                "precondition_id": "beneficiary-eligible",
                "step": "pay",
                "outcome": "failed",
                "exit_code": 3,
                "inputs_hash": "sha256:deadbeef",
                "summary": "precondition 'beneficiary-eligible' failed step 'pay' (exit 3)",
                "checked_at": "2026-10-01T00:00:00Z",
                "attribution": "recorded",
                // These must NOT be copied into the finding (SpanPrivacy):
                "parameters": { "beneficiary": "acct-secret" },
                "stdout": "secret output"
            })),
        }],
        source: None,
        total_tokens: 0,
        duration_ms: 0,
        git_commit: None,
        git_branch: None,
        model_version: None,
        planning_prompt_content: None,
        file_paths: vec![],
        metadata: None,
        scoring_results: std::collections::HashMap::new(),
        sign: false,
        repository: None,
        author: None,
        identity: None,
        effect_key: None,
        producer_id: None,
        sequence: None,
        prev_hash: None,
        history_policy: None,
    };

    let envelope = factory.build_envelope(input).await.expect("envelope");
    assert_eq!(envelope.precondition_findings.len(), 1);
    let finding = &envelope.precondition_findings[0];
    assert_eq!(finding.precondition_id, "beneficiary-eligible");
    assert_eq!(finding.step, "pay");
    assert_eq!(finding.outcome, "failed");
    assert_eq!(finding.exit_code, Some(3));
    assert_eq!(finding.inputs_hash, "sha256:deadbeef");
    assert!(finding.checked_at.to_rfc3339().starts_with("2026-10-01"));
    assert_eq!(finding.attribution.as_deref(), Some("recorded"));

    // SpanPrivacy: no parameter values, no stdout.
    let serialized = serde_json::to_string(finding).expect("serialize");
    assert!(!serialized.contains("acct-secret"));
    assert!(!serialized.contains("secret output"));
}

#[test]
fn attribution_reason_states_are_distinct_and_optional() {
    // ISSUE-ATTRIBUTION-ABSENCE-REASON AC #7: all states + the legacy-absent
    // case (a pre-attribution finding omits the key, so old bytes are stable).
    assert_eq!(AttributionReason::Recorded.as_str(), "recorded");
    assert_eq!(
        AttributionReason::RefusedBeforeCheck.as_str(),
        "refused_before_check"
    );
    assert_eq!(
        AttributionReason::ArtifactUnreadable.as_str(),
        "artifact_unreadable"
    );

    for reason in [
        AttributionReason::Recorded,
        AttributionReason::RefusedBeforeCheck,
        AttributionReason::ArtifactUnreadable,
    ] {
        let mut candidate = finding(PreconditionOutcome::Failed, Some(1));
        candidate.attribution = Some(reason);
        let value = serde_json::to_value(&candidate).expect("serialize");
        assert_eq!(value["attribution"], reason.as_str());
    }

    let legacy = finding(PreconditionOutcome::Passed, Some(0));
    let value = serde_json::to_value(&legacy).expect("serialize");
    assert!(
        value.get("attribution").is_none(),
        "a legacy finding must omit attribution (absent ≠ tampered)"
    );

    let encoded = serde_json::to_string(&AttributionReason::RefusedBeforeCheck).expect("serialize");
    assert_eq!(encoded, "\"refused_before_check\"");
}
