// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: ApprovalError (approval module)
// Contract freeze: the error enum, Display messages, and `is_retriable()`
// classification are implemented (frozen contract, AC #15 groundwork).

use rigorix_engine::approval::domain::ApprovalError;
use uuid::Uuid;

#[test]
fn test_approvalerror_all_variants_display() {
    let cases = [
        ApprovalError::NotFound(Uuid::nil()),
        ApprovalError::AlreadyConsumed(Uuid::nil()),
        ApprovalError::Expired(Uuid::nil()),
        ApprovalError::InvalidState("bad".into()),
        ApprovalError::ScopeVerificationUnavailable("git".into()),
        ApprovalError::Internal("boom".into()),
    ];
    for err in cases {
        assert!(!err.to_string().is_empty(), "Display must produce text");
    }
    let mismatch = ApprovalError::IntentMismatch {
        node_id: Uuid::nil(),
        expected: "abc".into(),
        actual: "def".into(),
    };
    assert!(mismatch.to_string().contains("abc"));
    assert!(mismatch.to_string().contains("def"));
}

#[test]
fn test_approvalerror_is_retriable_classification() {
    // IntentMismatch → non-retriable (re-approval is the only recovery).
    assert!(
        !ApprovalError::IntentMismatch {
            node_id: Uuid::nil(),
            expected: "e".into(),
            actual: "a".into(),
        }
        .is_retriable()
    );
    // NotFound / AlreadyConsumed / Expired → not retriable — re-approval required.
    assert!(!ApprovalError::NotFound(Uuid::nil()).is_retriable());
    assert!(!ApprovalError::AlreadyConsumed(Uuid::nil()).is_retriable());
    assert!(!ApprovalError::Expired(Uuid::nil()).is_retriable());
    assert!(!ApprovalError::InvalidState("x".into()).is_retriable());
    // Scope oracle unavailable / internal → retriable.
    assert!(ApprovalError::ScopeVerificationUnavailable("git".into()).is_retriable());
    assert!(ApprovalError::Internal("x".into()).is_retriable());
}

#[test]
fn test_approvalerror_implements_std_error() {
    fn assert_error<E: std::error::Error>() {}
    assert_error::<ApprovalError>();
}
