// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: GatingMode (consequence-gating module)
// Contract freeze: `release_dependents_on_failure` defaults to today's behavior
// (release) and is additive/opt-in; the release-dependents logic lands in
// ISSUE-CONSEQUENCE-GATING-7.

use rigorix_engine::precondition::domain::GatingMode;

#[test]
fn test_gatingmode_is_defined() {
    let mode = GatingMode::default();
    assert!(mode.release_dependents_on_failure);
    assert!(mode.releases_dependents_on_failure());
}

#[test]
fn test_gatingmode_absent_table_preserves_todays_behavior() {
    // Additive/opt-in: deserializing an empty `[gating]` table must not flip
    // the long-standing "release dependents" behavior.
    let mode: GatingMode = serde_json::from_value(serde_json::json!({})).expect("empty");
    assert!(mode.release_dependents_on_failure);
}

#[test]
fn test_gatingmode_false_round_trips() {
    let mode = GatingMode {
        release_dependents_on_failure: false,
    };
    let encoded = serde_json::to_string(&mode).expect("serialize");
    let decoded: GatingMode = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, mode);
    assert!(!decoded.releases_dependents_on_failure());
}

// ── AC #13: release_dependents_on_failure=false stops the failure ──────────

/// Build A → B → C.
fn chain() -> (
    rigorix_engine::dag_engine::domain::TaskGraph,
    uuid::Uuid,
    uuid::Uuid,
    uuid::Uuid,
) {
    use rigorix_engine::dag_engine::domain::{TaskGraph, TaskNode};
    let (a, b, c) = (
        uuid::Uuid::new_v4(),
        uuid::Uuid::new_v4(),
        uuid::Uuid::new_v4(),
    );
    let mut graph = TaskGraph::new();
    graph
        .add_unchecked(TaskNode::new(a, "a", "tool", vec![], "{}"))
        .unwrap();
    graph
        .add_unchecked(TaskNode::new(b, "b", "tool", vec![a], "{}"))
        .unwrap();
    graph
        .add_unchecked(TaskNode::new(c, "c", "tool", vec![b], "{}"))
        .unwrap();
    graph.seal().unwrap();
    (graph, a, b, c)
}

#[test]
fn test_release_false_stops_transitive_dependents_without_releasing() {
    let (mut graph, a, b, c) = chain();

    // The transitive dependents of the failed node.
    let mut expected = vec![b, c];
    let mut actual = graph.transitive_dependents(a);
    actual.sort();
    expected.sort();
    assert_eq!(actual, expected);

    // Simulate A's dispatch, then `release_dependents_on_failure = false`:
    // record A and its dependents as completed WITHOUT releasing them.
    graph.pop_ready_node();
    graph.mark_completed_without_release(a).unwrap();
    for dep in &[b, c] {
        graph.mark_completed_without_release(*dep).unwrap();
    }
    let ready = graph.ready_nodes();
    assert!(
        !ready.contains(&b) && !ready.contains(&c),
        "dependents must never enter the ready queue"
    );
    assert!(graph.is_execution_complete());
}

#[test]
fn test_release_true_releases_dependents_into_the_ready_queue() {
    let (mut graph, a, b, _c) = chain();
    graph.pop_ready_node();
    graph.mark_completed(a).unwrap();
    assert!(
        graph.ready_nodes().contains(&b),
        "default behavior releases the direct dependent"
    );
}
