// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: SequencePolicyError (sequence-policy module)
// Contract freeze: the error enum is fully implemented at freeze time — every
// variant, its Display message, and the `is_retriable()` classification are
// part of the frozen contract (AC #14).

use rigorix_engine::sequence_policy::domain::SequencePolicyError;

#[test]
fn test_sequencepolicyerror_is_defined() {
    // All five variants exist with structured context.
    assert!(matches!(
        SequencePolicyError::InvalidConfig("boom".into()),
        SequencePolicyError::InvalidConfig(_)
    ));
    assert!(matches!(
        SequencePolicyError::RuleExceedsCaps {
            rule: "r".into(),
            detail: "window > max".into(),
        },
        SequencePolicyError::RuleExceedsCaps { .. }
    ));
    assert!(matches!(
        SequencePolicyError::NotFound("r".into()),
        SequencePolicyError::NotFound(_)
    ));
    assert!(matches!(
        SequencePolicyError::InvalidState("x".into()),
        SequencePolicyError::InvalidState(_)
    ));
    assert!(matches!(
        SequencePolicyError::Internal("io".into()),
        SequencePolicyError::Internal(_)
    ));
}

#[test]
fn test_display_messages_are_frozen() {
    assert_eq!(
        SequencePolicyError::InvalidConfig("bad toml".into()).to_string(),
        "Rule config invalid: bad toml"
    );
    assert_eq!(
        SequencePolicyError::RuleExceedsCaps {
            rule: "registration-remove-then-reassign".into(),
            detail: "window 10 exceeds cap 5".into(),
        }
        .to_string(),
        "Rule 'registration-remove-then-reassign' exceeds safety caps: window 10 exceeds cap 5"
    );
    assert_eq!(
        SequencePolicyError::NotFound("registration-remove-then-reassign".into()).to_string(),
        "Rule not found: registration-remove-then-reassign"
    );
    assert_eq!(
        SequencePolicyError::InvalidState("run refused".into()).to_string(),
        "Invalid state: run refused"
    );
    let internal = SequencePolicyError::Internal("disk full".into());
    assert_eq!(internal.to_string(), "Internal error: disk full");

    // std::error::Error surface (library compatibility).
    let as_std: &dyn std::error::Error = &internal;
    assert!(as_std.to_string().contains("disk full"));
}

#[test]
fn test_is_retriable_classification_is_frozen() {
    // Config errors are operator-facing and non-retriable (fail-closed at plan
    // time); only Internal is retriable.
    assert!(!SequencePolicyError::InvalidConfig("x".into()).is_retriable());
    assert!(
        !SequencePolicyError::RuleExceedsCaps {
            rule: "r".into(),
            detail: "d".into(),
        }
        .is_retriable()
    );
    assert!(!SequencePolicyError::NotFound("r".into()).is_retriable());
    assert!(!SequencePolicyError::InvalidState("s".into()).is_retriable());
    assert!(SequencePolicyError::Internal("io".into()).is_retriable());
}

#[test]
fn test_error_is_send_sync_clone_eq_and_std_error() {
    // The error crosses async boundaries (Send + Sync), is cloned for
    // retriability bookkeeping, and compares by value (tests, dedupe).
    fn assert_traits<T: Send + Sync + Clone + PartialEq + Eq + std::error::Error>() {}
    assert_traits::<SequencePolicyError>();

    // Leaf errors have no source chain.
    let err = SequencePolicyError::InvalidConfig("x".into());
    let as_std: &dyn std::error::Error = &err;
    assert!(as_std.source().is_none());
}

#[test]
fn test_error_variants_compare_by_value_and_dedupe() {
    let a = SequencePolicyError::RuleExceedsCaps {
        rule: "r".into(),
        detail: "window too big".into(),
    };
    let b = SequencePolicyError::RuleExceedsCaps {
        rule: "r".into(),
        detail: "window too big".into(),
    };
    let c = SequencePolicyError::RuleExceedsCaps {
        rule: "r".into(),
        detail: "too many regex predicates".into(),
    };
    assert_eq!(a, b);
    assert_ne!(a, c);
}

#[test]
fn test_is_retriable_exhaustively_matches_all_variants() {
    // Exhaustive: any new variant must be classified here (compile-time
    // guard via match arm count when a variant is added).
    let cases: Vec<(SequencePolicyError, bool)> = vec![
        (SequencePolicyError::InvalidConfig("c".into()), false),
        (
            SequencePolicyError::RuleExceedsCaps {
                rule: "r".into(),
                detail: "d".into(),
            },
            false,
        ),
        (SequencePolicyError::NotFound("r".into()), false),
        (SequencePolicyError::InvalidState("s".into()), false),
        (SequencePolicyError::Internal("io".into()), true),
    ];
    for (err, expected) in cases {
        assert_eq!(err.is_retriable(), expected, "is_retriable({err})");
    }
}
