// Generated by Guardian TDD
// From: AuditQueryService (Aggregate Root) (audit-tools module)
// Tests the InMemoryAuditQueryService implementation.

#[cfg(test)]
mod tests {
    use chrono::{Duration, Utc};
    use uuid::Uuid;

    use rigorix_mcp::audit_tools::domain::entity::AuditQueryService;
    use rigorix_mcp::audit_tools::domain::value::{
        AuditEnvelope, AuditFilter,
    };
    use rigorix_mcp::audit_tools::infrastructure::InMemoryAuditQueryService;
    use rigorix_mcp::execution_tools::domain::value::{ExecutionId, ExecutionStatus};

    fn sample_envelope(id: Uuid, status: ExecutionStatus) -> AuditEnvelope {
        let now = Utc::now();
        InMemoryAuditQueryService::create_sample(
            id,
            status,
            Some("test-template".into()),
            now - Duration::hours(1),
            5000,
        )
    }

    #[tokio::test]
    async fn test_auditqueryservice_read_audit_found() {
        let service = InMemoryAuditQueryService::new();
        let id = Uuid::new_v4();
        let envelope = sample_envelope(id, ExecutionStatus::Completed);
        service.store(envelope).unwrap();

        let result = service.read_audit(&ExecutionId::from_uuid(id)).await;
        assert!(result.is_ok());
        assert_eq!(result.unwrap().execution_id(), id);
    }

    #[tokio::test]
    async fn test_auditqueryservice_read_audit_not_found() {
        let service = InMemoryAuditQueryService::new();
        let id = Uuid::new_v4();

        let result = service.read_audit(&ExecutionId::from_uuid(id)).await;
        assert!(result.is_err());
        match result.unwrap_err() {
            rigorix_mcp::audit_tools::domain::error::AuditError::NotFound(_) => {}
            e => panic!("Expected NotFound, got: {}", e),
        }
    }

    #[tokio::test]
    async fn test_auditqueryservice_list_audits_empty() {
        let service = InMemoryAuditQueryService::new();
        let result = service.list_audits(AuditFilter::new()).await;
        assert!(result.is_ok());
        assert!(result.unwrap().is_empty());
    }

    #[tokio::test]
    async fn test_auditqueryservice_list_audits_filter_by_status() {
        let service = InMemoryAuditQueryService::new();
        let id1 = Uuid::new_v4();
        let id2 = Uuid::new_v4();
        service.store(sample_envelope(id1, ExecutionStatus::Completed)).unwrap();
        service.store(sample_envelope(id2, ExecutionStatus::Failed)).unwrap();

        let filter = AuditFilter::with_all(
            Some(ExecutionStatus::Completed),
            None, None, None, 50, None,
        );
        let result = service.list_audits(filter).await.unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].execution_id(), id1);
    }

    #[tokio::test]
    async fn test_auditqueryservice_list_audits_pagination() {
        let service = InMemoryAuditQueryService::new();
        for i in 0..10 {
            let id = Uuid::new_v4();
            service.store(sample_envelope(id, ExecutionStatus::Completed)).unwrap();
        }

        let filter = AuditFilter::with_all(None, None, None, None, 3, Some(0));
        let result = service.list_audits(filter).await.unwrap();
        assert_eq!(result.len(), 3);
    }

    #[tokio::test]
    async fn test_auditqueryservice_audit_summary() {
        let service = InMemoryAuditQueryService::new();
        let now = Utc::now();

        // Add 3 completed and 2 failed within the time range
        for i in 0..5 {
            let status = if i < 3 {
                ExecutionStatus::Completed
            } else {
                ExecutionStatus::Failed
            };
            service.store(InMemoryAuditQueryService::create_sample(
                Uuid::new_v4(),
                status,
                Some("test".into()),
                now - Duration::hours(i as i64),
                1000,
            )).unwrap();
        }

        let since = now - Duration::days(1);
        let until = now + Duration::hours(1);
        let summary = service.audit_summary(since, until).await.unwrap();

        assert_eq!(summary.total_executions(), 5);
        assert_eq!(summary.success_count(), 3);
        assert_eq!(summary.failure_count(), 2);
        assert!((summary.success_rate() - 0.6).abs() < 0.001);
    }

    #[tokio::test]
    async fn test_auditqueryservice_audit_summary_empty_range() {
        let service = InMemoryAuditQueryService::new();
        let now = Utc::now();

        let since = now - Duration::days(30);
        let until = now - Duration::days(29);
        let summary = service.audit_summary(since, until).await.unwrap();

        assert_eq!(summary.total_executions(), 0);
        assert_eq!(summary.success_rate(), 0.0);
    }
}
