// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: SequencePolicyService (sequence-policy module)
// Contract freeze: the service trait + boundary DTOs are defined here;
// `evaluate_plan` behavior (finds remove-then-add pair in a runbook, returns
// the later step) lands in ISSUE-SEQUENCE-POLICY-2.

use rigorix_engine::sequence_policy::application::{
    DispatchedStep, PlannedStep, SequencePolicyService,
};
use serde_json::json;

/// A runbook step as the orchestrator feeds it to plan-time evaluation (R2).
fn planned(name: &str, tool: &str) -> PlannedStep {
    PlannedStep {
        name: name.to_string(),
        tool: tool.to_string(),
        parameters: json!({ "event_id": "conf-2026" }),
    }
}

#[test]
fn test_sequencepolicyservice_is_defined() {
    // The service trait must be dyn-compatible and Send + Sync (async-trait),
    // so the orchestrator / execution engine can hold Box<dyn SequencePolicyService>.
    fn assert_service<T: Send + Sync + ?Sized>() {}
    assert_service::<dyn SequencePolicyService>();
}

#[test]
fn test_planned_step_dto_carries_the_matching_relevant_fields() {
    let step = planned("registration_remove", "registration_remove");
    assert_eq!(step.name, "registration_remove");
    assert_eq!(step.tool, "registration_remove");
    assert_eq!(step.parameters["event_id"], "conf-2026");
}

#[test]
fn test_boundary_dtos_serde_round_trip() {
    let step = planned("registration_add", "registration_add");
    let encoded = serde_json::to_string(&step).expect("serialize");
    let decoded: PlannedStep = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, step);

    let dispatched = DispatchedStep {
        name: "registration_remove".to_string(),
        tool: "registration_remove".to_string(),
        parameters: json!({ "event_id": "conf-2026" }),
    };
    let encoded = serde_json::to_string(&dispatched).expect("serialize");
    let decoded: DispatchedStep = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, dispatched);
}
