// Generated by Guardian TDD — rewritten as behavioral tests (was an inert
// `assert!(false)` scaffold).
// From: CompanionStepObligation (consequence-gating module)
// AC #14: `require_companion_step` unmet → deny (or promote) with a finding;
// present → dispatches.

use rigorix_engine::precondition::application::{
    CompanionAction, CompanionStepObligation, CompanionStepObligationService,
    CompanionStepObligationServiceImpl, DispatchStep,
};
use serde_json::json;

fn obligation(action: &str) -> CompanionStepObligation {
    serde_json::from_value(json!({
        "id": "payout-needs-recheck",
        "match": { "tool": "payment_execute" },
        "require_companion_step": { "tool": "authority_recheck" },
        "action": action
    }))
    .expect("obligation parses")
}

fn step(name: &str, tool: &str) -> DispatchStep {
    DispatchStep {
        name: name.to_string(),
        tool: tool.to_string(),
        parameters: json!({}),
    }
}

#[test]
fn test_companionstepobligation_is_defined() {
    let obligation = obligation("deny");
    assert_eq!(obligation.id, "payout-needs-recheck");
    assert_eq!(obligation.r#match.tool, "payment_execute");
    assert_eq!(obligation.require_companion_step.tool, "authority_recheck");
    assert_eq!(obligation.action, CompanionAction::Deny);
}

#[tokio::test]
async fn test_companionstepobligation_interacts_with_precondition_via_service() {
    let service = CompanionStepObligationServiceImpl::new(vec![obligation("deny")]);
    let findings = service
        .evaluate_plan(&[step("pay", "payment_execute")])
        .await
        .expect("evaluate");
    assert_eq!(findings.len(), 1);
    assert_eq!(findings[0].obligation_id, "payout-needs-recheck");
    assert_eq!(findings[0].step, "pay");
    assert_eq!(findings[0].required_companion, "authority_recheck");
    assert_eq!(findings[0].action, CompanionAction::Deny);
}

#[tokio::test]
async fn test_unmet_deny_finding_and_present_dispatches() {
    let service = CompanionStepObligationServiceImpl::new(vec![obligation("deny")]);

    // Unmet → deny finding.
    let unmet = service
        .evaluate_plan(&[step("pay", "payment_execute")])
        .await
        .expect("evaluate");
    assert_eq!(unmet.len(), 1);
    assert_eq!(unmet[0].action, CompanionAction::Deny);

    // Present → no finding → the step dispatches.
    let present = service
        .evaluate_plan(&[
            step("recheck", "authority_recheck"),
            step("pay", "payment_execute"),
        ])
        .await
        .expect("evaluate");
    assert!(present.is_empty(), "companion present ⇒ dispatch");

    // Non-matching step → no finding.
    let other = service
        .evaluate_plan(&[step("backup", "run_backup")])
        .await
        .expect("evaluate");
    assert!(other.is_empty());
}

#[tokio::test]
async fn test_unmet_promote_reports_promote() {
    let service = CompanionStepObligationServiceImpl::new(vec![obligation("promote")]);
    let findings = service
        .evaluate_plan(&[step("pay", "payment_execute")])
        .await
        .expect("evaluate");
    assert_eq!(findings.len(), 1);
    assert_eq!(findings[0].action, CompanionAction::Promote);
    assert!(findings[0].decision_summary().contains("promoted"));
}
