// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: StepPredicate (sequence-policy module)
// Contract freeze: the predicate shape + wire kinds (`exact` | `glob` |
// `regex`) are frozen here; tool-glob + param matching behavior lands in
// ISSUE-SEQUENCE-POLICY-4.

use rigorix_engine::sequence_policy::domain::{ParamMatchKind, ParamPredicate, StepPredicate};
use serde_json::json;

fn removal_predicate() -> StepPredicate {
    StepPredicate {
        tool: "registration_remove".to_string(),
        params: vec![ParamPredicate {
            pointer: "/event_id".to_string(),
            kind: ParamMatchKind::Exact,
            value: "conf-2026".to_string(),
        }],
    }
}

#[test]
fn test_steppredicate_is_defined() {
    let predicate = removal_predicate();
    assert_eq!(predicate.tool, "registration_remove");
    assert_eq!(predicate.params.len(), 1);
    let param = &predicate.params[0];
    assert_eq!(param.pointer, "/event_id");
    assert_eq!(param.value, "conf-2026");
    // Exact / glob / regex are the three frozen comparison kinds.
    assert_eq!(param.kind, ParamMatchKind::Exact);
}

#[test]
fn test_steppredicate_serde_round_trip() {
    let predicate = removal_predicate();
    let encoded = serde_json::to_string(&predicate).expect("serialize");
    let decoded: StepPredicate = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, predicate);
}

#[test]
fn test_param_match_kind_wire_format_is_lowercase() {
    // Wire kinds are frozen lowercase — the .rigorix/sequence-policy.toml
    // schema writes `kind = "exact" | "glob" | "regex"`.
    let exact: ParamPredicate =
        serde_json::from_value(json!({"pointer": "/a", "kind": "exact", "value": "x"}))
            .expect("exact");
    let glob: ParamPredicate =
        serde_json::from_value(json!({"pointer": "/a", "kind": "glob", "value": "x*"}))
            .expect("glob");
    let regex: ParamPredicate =
        serde_json::from_value(json!({"pointer": "/a", "kind": "regex", "value": "^x$"}))
            .expect("regex");
    assert_eq!(exact.kind, ParamMatchKind::Exact);
    assert_eq!(glob.kind, ParamMatchKind::Glob);
    assert_eq!(regex.kind, ParamMatchKind::Regex);

    // Round-trips through the wire representation.
    assert_eq!(
        serde_json::to_value(glob.kind).expect("kind"),
        json!("glob")
    );
}

#[test]
fn test_steppredicate_params_default_to_empty() {
    // `params` omitted in config → no parameter predicates (tool-only match).
    let bare: StepPredicate =
        serde_json::from_value(json!({ "tool": "run_command" })).expect("params omitted");
    assert_eq!(bare.tool, "run_command");
    assert!(bare.params.is_empty());
}
