// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: Execution Engine (R3) (sequence-policy module)
// Contract freeze: the run-time prefix-gate data contract is frozen here —
// `evaluate_prefix(completed_prefix, next)` over a dynamic plan's dispatch
// prefix. The dynamic-plan integration behavior (step A completes, B is
// proposed → B promoted/denied per rule) lands in the execution-engine-r3
// issue.

use rigorix_engine::sequence_policy::application::{DispatchedStep, PlannedStep};
use rigorix_engine::sequence_policy::domain::{RuleAction, SequenceMatch};
use serde_json::json;

#[test]
fn test_execution_engine_r3_is_defined() {
    // Completed prefix: step A ("registration_remove") has already dispatched.
    let prefix = vec![DispatchedStep {
        name: "registration_remove".to_string(),
        tool: "registration_remove".to_string(),
        parameters: json!({ "event_id": "conf-2026" }),
    }];
    // Next ready node: step B would complete the forbidden sequence.
    let next = PlannedStep {
        name: "registration_add".to_string(),
        tool: "registration_add".to_string(),
        parameters: json!({ "event_id": "conf-2026" }),
    };

    assert_eq!(prefix.len(), 1);
    assert_eq!(prefix[0].tool, "registration_remove");
    assert_eq!(next.tool, "registration_add");
    assert_eq!(next.name, "registration_add");
}

#[test]
fn test_r3_promote_routes_to_the_existing_approval_pause() {
    // A prefix + next that would complete a forbidden sequence produces a
    // match whose later_step is the next node — routed into the existing
    // AwaitingApproval pause (approval module, ADR-011).
    let matched = SequenceMatch {
        rule_id: "registration-remove-then-reassign".to_string(),
        action: RuleAction::Promote,
        matched_indices: vec![0, 1],
        later_step: "registration_add".to_string(),
    };
    assert_eq!(matched.action, RuleAction::Promote);
    assert_eq!(matched.later_step, "registration_add");
    let routes_to_approval_pause = matches!(matched.action, RuleAction::Promote);
    assert!(routes_to_approval_pause);
}

#[test]
fn test_r3_deny_returns_a_structured_failure() {
    let matched = SequenceMatch {
        rule_id: "deny-dynamic-pair".to_string(),
        action: RuleAction::Deny,
        matched_indices: vec![0, 1],
        later_step: "registration_add".to_string(),
    };
    // Deny → structured node failure (SequencePolicyDenied), no dispatch.
    let structured_failure = matches!(matched.action, RuleAction::Deny);
    assert!(structured_failure);
    assert_eq!(matched.later_step, "registration_add");
}
