// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: GatingMode (consequence-gating module)
// Contract freeze: `release_dependents_on_failure` defaults to today's behavior
// (release) and is additive/opt-in; the release-dependents logic lands in
// ISSUE-CONSEQUENCE-GATING-7.

use rigorix_engine::precondition::domain::GatingMode;

#[test]
fn test_gatingmode_is_defined() {
    let mode = GatingMode::default();
    assert!(mode.release_dependents_on_failure);
    assert!(mode.releases_dependents_on_failure());
}

#[test]
fn test_gatingmode_absent_table_preserves_todays_behavior() {
    // Additive/opt-in: deserializing an empty `[gating]` table must not flip
    // the long-standing "release dependents" behavior.
    let mode: GatingMode = serde_json::from_value(serde_json::json!({})).expect("empty");
    assert!(mode.release_dependents_on_failure);
}

#[test]
fn test_gatingmode_false_round_trips() {
    let mode = GatingMode {
        release_dependents_on_failure: false,
    };
    let encoded = serde_json::to_string(&mode).expect("serialize");
    let decoded: GatingMode = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, mode);
    assert!(!decoded.releases_dependents_on_failure());
}
