// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionSurfaces (consequence-gating module)
// Contract freeze: the structured `policy_violation` refusal payload and the
// version capability are frozen here; the MCP/host wiring lands in
// ISSUE-CONSEQUENCE-GATING-10.

use rigorix_engine::precondition::application::{
    PreconditionPolicyViolation, PreconditionSurfaces,
};
use rigorix_engine::precondition::domain::{PreconditionOutcome, PreconditionVerdict};

struct McpSurfaces;

impl PreconditionSurfaces for McpSurfaces {}

#[test]
fn test_preconditionsurfaces_is_defined() {
    let surfaces = McpSurfaces;
    assert_eq!(surfaces.capability(), "precondition_gating");
}

#[test]
fn test_dispatch_verdict_has_no_policy_violation() {
    let surfaces = McpSurfaces;
    assert!(
        surfaces
            .refusal_payload(&PreconditionVerdict::Dispatch, "pay")
            .is_none()
    );
}

#[test]
fn test_refusal_maps_to_structured_policy_violation() {
    let surfaces = McpSurfaces;
    let verdict = PreconditionVerdict::Deny {
        precondition_id: "beneficiary-eligible".to_string(),
        outcome: PreconditionOutcome::Failed,
    };
    let violation = surfaces
        .refusal_payload(&verdict, "pay")
        .expect("a refusal is a structured violation");
    assert_eq!(
        violation,
        PreconditionPolicyViolation {
            precondition_id: "beneficiary-eligible".to_string(),
            step: "pay".to_string(),
            outcome: PreconditionOutcome::Failed,
        }
    );
    // The structured payload serializes with the frozen data keys.
    let value = serde_json::to_value(&violation).expect("serialize");
    assert_eq!(value["precondition_id"], "beneficiary-eligible");
    assert_eq!(value["step"], "pay");
    assert_eq!(value["outcome"], "failed");
}
