// Generated by Guardian TDD
// From: TokenProvider (Infrastructure) (auth module)
// TDD Contract: TokenProvider trait with current_access_token,
// set_access_token, access_token_expires_at, clear

#![allow(unused_imports)]

use async_trait::async_trait;
use chrono::{Duration, Utc};

use rigorix_mcp::auth::domain::error::AuthError;
use rigorix_mcp::auth::domain::value::Secret;
use rigorix_mcp::auth::infrastructure::token_provider::TokenProvider;
use rigorix_mcp::auth::infrastructure::InMemoryTokenProvider;

/// Minimal contract-conforming stub — proves the frozen TokenProvider trait
/// is implementable with the ISSUE-AUTH-4 method set. The real in-memory
/// provider lives in src/auth/infrastructure/token_provider_impl.rs.
struct TokenProviderTddContract;

#[async_trait]
impl TokenProvider for TokenProviderTddContract {
    async fn current_access_token(&self) -> Option<Secret<String>> {
        None
    }

    async fn set_access_token(
        &self,
        _token: Secret<String>,
        _expires_at: chrono::DateTime<Utc>,
    ) -> Result<(), AuthError> {
        Ok(())
    }

    async fn access_token_expires_at(&self) -> Option<chrono::DateTime<Utc>> {
        None
    }

    async fn clear(&self) {}
}

#[test]
fn test_tokenprovider_infrastructure_is_defined() {
    let provider = TokenProviderTddContract;
    let rt = tokio::runtime::Runtime::new().unwrap();
    rt.block_on(
        provider.set_access_token(
            Secret::new("t".into()),
            Utc::now() + Duration::seconds(900),
        ),
    )
    .unwrap();
    assert!(rt.block_on(provider.current_access_token()).is_none());
}

#[test]
fn test_in_memory_token_provider_contract() {
    let provider = InMemoryTokenProvider::new();
    let rt = tokio::runtime::Runtime::new().unwrap();
    rt.block_on(
        provider.set_access_token(
            Secret::new("access-token".into()),
            Utc::now() + Duration::seconds(900),
        ),
    )
    .unwrap();
    let token = rt.block_on(provider.current_access_token()).unwrap();
    assert_eq!(token.expose(), "access-token");
    assert!(rt.block_on(provider.access_token_expires_at()).unwrap() > Utc::now());
    rt.block_on(provider.clear());
    assert!(rt.block_on(provider.current_access_token()).is_none());
}
