// Generated by Guardian TDD
// From: identityclaim
// Corrected (GAP-A-24): the tested type is now implemented — the
// is_defined / interacts_with_none assertions exercise the real type.

#[cfg(test)]
mod tests {
    use rigorix_engine::identity::domain::{IdentityClaim, IdentitySource};

    #[test]
    fn test_identityclaim_is_defined() {
        let claim = IdentityClaim {
            subject: "user@org".to_string(),
            issuer: "https://idp.example.com".to_string(),
            authority: None,
            source: IdentitySource::LocalPrincipal,
            auth_method: None,
            issued_at: chrono::Utc::now(),
            expires_at: None,
            token_ref: None,
        };
        assert_eq!(claim.subject, "user@org");
    }

    #[test]
    fn test_identityclaim_interacts_with_none() {
        let claim = IdentityClaim {
            subject: "s".to_string(),
            issuer: "i".to_string(),
            authority: None,
            source: IdentitySource::Unverified,
            auth_method: None,
            issued_at: chrono::Utc::now(),
            expires_at: None,
            token_ref: None,
        };
        let json = serde_json::to_string(&claim).unwrap();
        assert!(serde_json::from_str::<IdentityClaim>(&json).is_ok());
    }
}
