// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionRunner (consequence-gating module)
// Contract freeze: argv-only execution, the `PreconditionRun` outcome shape,
// and the trust-boundary construction are frozen here; spawn/timeout behavior
// lands in ISSUE-CONSEQUENCE-GATING-3.

use rigorix_engine::precondition::domain::PreconditionOutcome;
use rigorix_engine::precondition::infrastructure::{
    PreconditionRun, PreconditionRunner, ProcessPreconditionRunner,
};

#[test]
fn test_preconditionrunner_is_defined() {
    let runner = ProcessPreconditionRunner::new("/workspace/agent-writable");
    assert_eq!(
        runner.workspace_root(),
        std::path::Path::new("/workspace/agent-writable")
    );
}

#[test]
fn test_preconditionrunner_is_object_safe() {
    let runner: Box<dyn PreconditionRunner> =
        Box::new(ProcessPreconditionRunner::new("/workspace/agent-writable"));
    let _ = &runner;
}

#[test]
fn test_run_outcome_taxonomy_distinguishes_failed_from_error() {
    // passed (exit 0) dispatches; failed (non-zero) and error (none) refuse and
    // are distinct — there is deliberately no allow-on-error mode.
    let passed = PreconditionRun {
        outcome: PreconditionOutcome::Passed,
        exit_code: Some(0),
        stdout: None,
    };
    let failed = PreconditionRun {
        outcome: PreconditionOutcome::Failed,
        exit_code: Some(3),
        stdout: None,
    };
    let error = PreconditionRun {
        outcome: PreconditionOutcome::Error,
        exit_code: None,
        stdout: None,
    };
    assert!(!passed.outcome.refuses());
    assert!(failed.outcome.refuses());
    assert!(error.outcome.refuses());
    assert_ne!(failed.outcome, error.outcome);
}
