// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: HardeningConfig (consequence-gating module)
// Contract freeze: `max_failures_before_abort` is additive (absent → today's
// unlimited behavior) and its threshold semantics are frozen here; threading it
// through `rigorix.toml` lands in ISSUE-CONSEQUENCE-GATING-11.

use rigorix_engine::precondition::application::HardeningConfig;

#[test]
fn test_hardeningconfig_is_defined() {
    let config = HardeningConfig::default();
    assert_eq!(config.max_failures_before_abort, None);
}

#[test]
fn test_hardeningconfig_absent_is_unlimited_today() {
    // Additive/opt-in: an omitted key preserves the executor's `0 = unlimited`
    // sentinel and must not change existing runs.
    let config = HardeningConfig::default();
    assert_eq!(config.effective_max_failures_before_abort(), 0);
    assert!(!config.aborts_after(u32::MAX));
}

#[test]
fn test_hardeningconfig_threshold_changes_abort_behavior() {
    let config = HardeningConfig {
        max_failures_before_abort: Some(3),
    };
    assert_eq!(config.effective_max_failures_before_abort(), 3);
    assert!(!config.aborts_after(2));
    assert!(config.aborts_after(3));
    // Explicit 0 is the same as absent (unlimited).
    assert!(
        !HardeningConfig {
            max_failures_before_abort: Some(0),
        }
        .aborts_after(u32::MAX)
    );
}

// ── AC #17: reachable from rigorix.toml and changes dispatch ───────────────

#[test]
fn test_max_failures_before_abort_settable_from_rigorix_toml() {
    use rigorix_engine::configuration::domain::Config;
    use rigorix_engine::execution_engine::domain::ParallelExecutorConfig;

    // Operator sets the top-level key in rigorix.toml.
    let config: Config = toml::from_str("max_failures_before_abort = 3\n")
        .expect("rigorix.toml with max_failures_before_abort parses");
    assert_eq!(config.max_failures_before_abort, Some(3));

    // Map to the epic's hardening contract and the executor threshold the
    // dispatch loop reads.
    let hardening = HardeningConfig {
        max_failures_before_abort: config.max_failures_before_abort,
    };
    assert!(hardening.aborts_after(3));
    assert!(!hardening.aborts_after(2));

    let executor = ParallelExecutorConfig {
        max_failures_before_abort: hardening.effective_max_failures_before_abort(),
        ..ParallelExecutorConfig::default()
    };
    assert_eq!(executor.max_failures_before_abort, 3);

    // Absent key → unlimited (today's behavior).
    let absent: Config = toml::from_str("").expect("empty config parses");
    assert_eq!(absent.max_failures_before_abort, None);
}
