// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: Audit (R6) (sequence-policy module)
// Contract freeze: the event-payload schema the audit stream records is
// frozen here — a matched rule + the action taken map 1:1 onto
// `SequenceRuleMatched { rule_id, action, later_step }`. Envelope recording
// (`sequence_policy_findings[]`) + default parameter-value redaction
// (SpanPrivacy pattern) land in the audit-r6 issue.

use rigorix_engine::sequence_policy::domain::{RuleAction, SequenceMatch};
use serde_json::{Value, json};

#[test]
fn test_audit_r6_is_defined() {
    // The R6 event payload: rule id, action taken, later step.
    let matched = SequenceMatch {
        rule_id: "registration-remove-then-reassign".to_string(),
        action: RuleAction::Promote,
        matched_indices: vec![0, 1],
        later_step: "registration_add".to_string(),
    };

    let value: Value = serde_json::to_value(&matched).expect("event payload");
    // SequenceRuleMatched { rule_id, action, later_step } — the fields the
    // envelope event carries verbatim.
    assert_eq!(value["rule_id"], json!("registration-remove-then-reassign"));
    assert_eq!(value["action"], json!("promote"));
    assert_eq!(value["later_step"], json!("registration_add"));
}

#[test]
fn test_deny_and_config_error_are_distinct_evidence() {
    // Deny-mode matches are recorded as SequencePolicyDenied — the action is
    // part of the payload, so the audit stream reconstructs what the engine
    // did ("why did the run stop") without re-reading the rule set.
    let denied = SequenceMatch {
        rule_id: "hard-deny-pair".to_string(),
        action: RuleAction::Deny,
        matched_indices: vec![0, 1],
        later_step: "registration_add".to_string(),
    };
    let value: Value = serde_json::to_value(&denied).expect("event payload");
    assert_eq!(value["action"], json!("deny"));
    assert_eq!(value["rule_id"], json!("hard-deny-pair"));
}

#[test]
fn test_match_evidence_is_deterministically_recordable() {
    // The same match serializes identically every time (deterministic R6
    // evidence — no LLM judgment, no nondeterministic fields in the payload).
    let matched = SequenceMatch {
        rule_id: "registration-remove-then-reassign".to_string(),
        action: RuleAction::Promote,
        matched_indices: vec![0, 1],
        later_step: "registration_add".to_string(),
    };
    let first = serde_json::to_string(&matched).expect("first");
    let second = serde_json::to_string(&matched).expect("second");
    assert_eq!(first, second);
}
