// Generated by Guardian TDD
// From: ReadAuditHandler (Domain Service) (audit-tools module)
// Tests the ReadAuditHandlerImpl.

#[cfg(test)]
mod tests {
    use std::sync::Arc;
    use uuid::Uuid;

    use rigorix_mcp::audit_tools::application::dto::ReadAuditInput;
    use rigorix_mcp::audit_tools::application::service::ReadAuditHandler;
    use rigorix_mcp::audit_tools::application::service_impl::ReadAuditHandlerImpl;
    use rigorix_mcp::audit_tools::domain::entity::AuditQueryService;
    use rigorix_mcp::audit_tools::domain::formatter_impl::AuditFormatterImpl;
    use rigorix_mcp::audit_tools::infrastructure::InMemoryAuditQueryService;
    use rigorix_mcp::execution_tools::domain::value::ExecutionStatus;

    #[tokio::test]
    async fn test_readaudithandler_reads_audit_text() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let id = Uuid::new_v4();
        let now = chrono::Utc::now();

        query_service
            .store(InMemoryAuditQueryService::create_sample(
                id,
                ExecutionStatus::Completed,
                Some("code-review".into()),
                now - chrono::Duration::hours(1),
                5000,
            ))
            .unwrap();

        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = ReadAuditHandlerImpl::new(query_service, formatter);

        let input = ReadAuditInput {
            execution_id: id.to_string(),
            format: Some("text".into()),
        };

        let result = handler.handle(input).await;
        assert!(result.is_ok());
        let tc = result.unwrap();
        assert!(!tc.is_error);
        assert!(!tc.content.is_empty());
        assert!(tc.content[0].text.contains(&id.to_string()));
    }

    #[tokio::test]
    async fn test_readaudithandler_reads_audit_json() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let id = Uuid::new_v4();
        let now = chrono::Utc::now();

        query_service
            .store(InMemoryAuditQueryService::create_sample(
                id,
                ExecutionStatus::Completed,
                None,
                now - chrono::Duration::hours(1),
                5000,
            ))
            .unwrap();

        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = ReadAuditHandlerImpl::new(query_service, formatter);

        let input = ReadAuditInput {
            execution_id: id.to_string(),
            format: Some("json".into()),
        };

        let result = handler.handle(input).await;
        assert!(result.is_ok());
        let tc = result.unwrap();
        assert!(!tc.is_error);
        assert!(tc.content[0].text.contains(&id.to_string()));
    }

    #[tokio::test]
    async fn test_readaudithandler_invalid_id() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = ReadAuditHandlerImpl::new(query_service, formatter);

        let input = ReadAuditInput {
            execution_id: "not-a-uuid".into(),
            format: None,
        };

        let result = handler.handle(input).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_readaudithandler_not_found() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = ReadAuditHandlerImpl::new(query_service, formatter);

        let input = ReadAuditInput {
            execution_id: Uuid::new_v4().to_string(),
            format: None,
        };

        let result = handler.handle(input).await;
        assert!(result.is_err());
    }
}
