// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: CompanionStepObligation (consequence-gating module)
// Contract freeze: the R3 `require_companion_step` config shape, its default
// action, and the redacted finding are frozen here; plan evaluation lands in
// ISSUE-CONSEQUENCE-GATING-9.

use async_trait::async_trait;
use rigorix_engine::precondition::application::{
    CompanionAction, CompanionFinding, CompanionStepObligation, CompanionStepObligationService,
    DispatchStep,
};
use rigorix_engine::precondition::domain::PreconditionError;
use serde_json::json;

struct NoCompanionObligations;

#[async_trait]
impl CompanionStepObligationService for NoCompanionObligations {
    async fn evaluate_plan(
        &self,
        _steps: &[DispatchStep],
    ) -> Result<Vec<CompanionFinding>, PreconditionError> {
        Ok(Vec::new())
    }
}

#[test]
fn test_companionstepobligation_is_defined() {
    let obligation: CompanionStepObligation = serde_json::from_value(json!({
        "id": "payout-needs-recheck",
        "match": { "tool": "payment_execute" },
        "require_companion_step": { "tool": "authority_recheck" }
    }))
    .expect("minimal obligation parses");
    assert_eq!(obligation.id, "payout-needs-recheck");
    assert_eq!(obligation.r#match.tool, "payment_execute");
    assert_eq!(obligation.require_companion_step.tool, "authority_recheck");
    // Default action is deny (a missing check stops the consequence).
    assert_eq!(obligation.action, CompanionAction::Deny);
}

#[test]
fn test_companionstepobligation_interacts_with_precondition_via_service() {
    let service: Box<dyn CompanionStepObligationService> = Box::new(NoCompanionObligations);
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("runtime");
    let findings = runtime
        .block_on(service.evaluate_plan(&[DispatchStep {
            name: "pay".to_string(),
            tool: "payment_execute".to_string(),
            parameters: json!({}),
        }]))
        .expect("no obligations configured");
    assert!(findings.is_empty());
}

#[test]
fn test_companion_finding_is_redacted() {
    let finding = CompanionFinding {
        obligation_id: "payout-needs-recheck".to_string(),
        step: "pay".to_string(),
        required_companion: "authority_recheck".to_string(),
        action: CompanionAction::Deny,
    };
    let summary = finding.decision_summary();
    assert!(summary.contains("payout-needs-recheck"));
    assert!(summary.contains("authority_recheck"));
    assert!(!summary.contains("acct-"));
}
