//! Implementation of `SymbolValidationService` for Phase 3 template validation.
//!
//! @canonical .pi/architecture/modules/template-generation.md#phase-3
//! Implements: SymbolValidationService — validates templates against indexed symbol graph
//! Issue: issue-phase-3-symbol-validation
//!
//! Scans generated template node actions for potential symbol references (type names,
//! function names, field accesses) and validates them against the symbol graph.
//! Catches hallucinated type references, field accesses on non-existent types,
//! and `any` type usage (LLM escape hatch).

use async_trait::async_trait;
use std::collections::BTreeSet;

use crate::planning::application::dto::{
    InvalidSymbolRef, SymbolValidationInput, SymbolValidationOutput,
};
use crate::planning::application::service::SymbolValidationService;
use crate::planning::domain::error::PlanningError;
use crate::repo_engine::application::service::SymbolGraphService;

/// Implementation of `SymbolValidationService` that validates templates
/// against the indexed Repo Engine symbol graph.
///
/// # Architecture
///
/// This service is part of the Template Generation pipeline (Phase 3).
/// It is called after a template has been generated by the LLM and
/// parsed/validated structurally, but before it is registered in the
/// TemplateEngine.
///
/// # Strategy
///
/// The validator extracts potential symbol references from template node
/// actions by scanning for patterns that look like type names (PascalCase)
/// or field accesses (dot notation). Each potential reference is looked up
/// in the symbol graph. Any reference not found is reported as invalid.
///
/// # Security
///
/// This is a critical security control against LLM hallucination:
/// - Prevents registration of templates referencing non-existent types
/// - Flags `any` type usage (LLM escape hatch for unknown types)
/// - Limits the number of reported invalid references to prevent DoS
pub struct SymbolValidationServiceImpl {
    /// The symbol graph service for reference lookups.
    symbol_graph: Box<dyn SymbolGraphService>,
}

impl SymbolValidationServiceImpl {
    /// Create a new SymbolValidationServiceImpl.
    pub fn new(symbol_graph: Box<dyn SymbolGraphService>) -> Self {
        Self { symbol_graph }
    }

    /// Check if a given name looks like a type reference (PascalCase or ALL_CAPS).
    fn looks_like_type(name: &str) -> bool {
        if name.is_empty() {
            return false;
        }
        // PascalCase: starts with uppercase
        name.starts_with(|c: char| c.is_uppercase())
            // Or ALL_CAPS: all uppercase with underscores
            || (name.chars().all(|c| c.is_uppercase() || c == '_' || c.is_numeric())
                && name.contains(|c: char| c.is_uppercase()))
    }

    /// Check if a name looks like a keyword or built-in path.
    fn is_reserved_name(name: &str) -> bool {
        matches!(
            name,
            "cargo"
                | "npm"
                | "pip"
                | "python"
                | "node"
                | "rustc"
                | "make"
                | "cmake"
                | "gradle"
                | "mvn"
                | "docker"
                | "git"
                | "ls"
                | "pwd"
                | "echo"
                | "cat"
                | "grep"
                | "find"
                | "mkdir"
                | "rm"
                | "cp"
                | "mv"
                | "chmod"
                | "chown"
                | "true"
                | "false"
                | "none"
                | "null"
                | "undefined"
                | "self"
                | "this"
                | "super"
                | "Some"
                | "None"
                | "Ok"
                | "Err"
                | "String"
                | "i32"
                | "i64"
                | "u32"
                | "u64"
                | "f32"
                | "f64"
                | "bool"
                | "usize"
                | "Vec"
                | "HashMap"
        )
    }
}

#[async_trait]
impl SymbolValidationService for SymbolValidationServiceImpl {
    async fn validate_template(
        &self,
        input: SymbolValidationInput,
    ) -> Result<SymbolValidationOutput, PlanningError> {
        let mut invalid_references: Vec<InvalidSymbolRef> = Vec::new();
        let mut references_checked: u32 = 0;
        let mut any_type_count: u32 = 0;

        // Extract all potential symbol references from the template
        let potential_refs = self
            .extract_symbol_references(&input.template)
            .await?;

        // Check each potential reference against the symbol graph
        for symbol_name in &potential_refs {
            references_checked += 1;

            // Skip reserved/built-in names
            if Self::is_reserved_name(symbol_name) {
                continue;
            }

            // Check for "any" type usage (LLM escape hatch)
            if symbol_name == "any" || symbol_name.contains("<any>") || symbol_name.contains("Any") {
                any_type_count += 1;
                if input.flag_any_type {
                    invalid_references.push(InvalidSymbolRef {
                        symbol: symbol_name.clone(),
                        usage: "type".to_string(),
                        reason: "'any' type used as escape hatch — should use actual type".to_string(),
                        is_any_type: true,
                    });
                }
                continue;
            }

            // Look up the symbol in the symbol graph
            let exists = self.symbol_exists(symbol_name).await?;

            if !exists {
                let usage = if Self::looks_like_type(symbol_name) {
                    "type".to_string()
                } else if symbol_name.contains('.') {
                    "field_access".to_string()
                } else {
                    "reference".to_string()
                };

                invalid_references.push(InvalidSymbolRef {
                    symbol: symbol_name.clone(),
                    usage,
                    reason: format!(
                        "Symbol '{}' not found in indexed symbol graph",
                        symbol_name
                    ),
                    is_any_type: false,
                });

                // Stop early if we've hit the limit
                if invalid_references.len() as u32 >= input.max_invalid_references {
                    break;
                }
            }
        }

        Ok(SymbolValidationOutput {
            execution_id: input.execution_id,
            valid: invalid_references.is_empty() && !(input.flag_any_type && any_type_count > 0),
            references_checked,
            invalid_references,
            any_type_detected: any_type_count > 0,
            any_type_count,
        })
    }

    async fn extract_symbol_references(
        &self,
        template: &crate::templates::domain::Template,
    ) -> Result<Vec<String>, PlanningError> {
        let mut refs = BTreeSet::new(); // BTreeSet for sorted, deduplicated results

        for node in &template.nodes {
            // Serialize the action to JSON to get the actual field values
            // (avoids Rust Debug formatting artifacts like field names and None)
            let action_json = serde_json::to_value(&node.action)
                .unwrap_or(serde_json::Value::Null);

            // Extract string values from the JSON
            Self::extract_strings_from_json(&action_json, &mut refs);

            // Also check intent and description fields
            if let Some(ref intent) = node.intent {
                Self::extract_pascal_case_words(intent, &mut refs);
            }
        }

        // Also check parameter default values for type references
        for param in &template.parameters {
            if let Some(ref default_val) = param.default {
                if let Some(s) = default_val.as_str() {
                    for word in s.split_whitespace() {
                        if Self::looks_like_type(word) {
                            refs.insert(word.to_string());
                        }
                    }
                }
            }
        }

        Ok(refs.into_iter().collect())
    }

    async fn get_symbol_graph_snapshot(&self) -> Result<serde_json::Value, PlanningError> {
        use crate::repo_engine::application::dto::GraphStatsInput;

        let stats = self
            .symbol_graph
            .graph_stats(GraphStatsInput {
                detailed: true,
            })
            .await
            .map_err(|e| PlanningError::DownstreamError {
                component: "SymbolGraphService".to_string(),
                detail: format!("Failed to get graph stats: {}", e),
            })?;

        Ok(serde_json::json!({
            "total_symbols": stats.total_symbols,
            "by_kind": stats.by_kind,
            "total_indexed": stats.total_indexed,
        }))
    }

    async fn symbol_exists(&self, name: &str) -> Result<bool, PlanningError> {
        use crate::repo_engine::application::dto::LookupSymbolInput;

        let input = LookupSymbolInput {
            name: name.to_string(),
            include_adjacency: false,
            reference_depth: 0,
        };

        let output = self
            .symbol_graph
            .lookup_symbol(input)
            .await
            .map_err(|e| PlanningError::DownstreamError {
                component: "SymbolGraphService".to_string(),
                detail: format!("Symbol lookup failed: {}", e),
            })?;

        Ok(output.found)
    }
}

// ---------------------------------------------------------------------------
// Internal helper methods on SymbolValidationServiceImpl
// ---------------------------------------------------------------------------

impl SymbolValidationServiceImpl {
    /// Recursively extract PascalCase words from a JSON value's string fields.
    fn extract_strings_from_json(value: &serde_json::Value, refs: &mut BTreeSet<String>) {
        match value {
            serde_json::Value::String(s) => {
                Self::extract_pascal_case_words(s, refs);
            }
            serde_json::Value::Object(map) => {
                for val in map.values() {
                    Self::extract_strings_from_json(val, refs);
                }
            }
            serde_json::Value::Array(arr) => {
                for val in arr {
                    Self::extract_strings_from_json(val, refs);
                }
            }
            _ => {}
        }
    }

    /// Extract potential symbol references from a string.
    ///
    /// Extracts:
    /// - PascalCase words (type names like "MyStruct")
    /// - ALL_CAPS words (constants like "MAX_SIZE")
    /// - "any" keyword (LLM escape hatch)
    /// - Dotted names (field accesses like "obj.field")
    fn extract_pascal_case_words(text: &str, refs: &mut BTreeSet<String>) {
        let mut current_word = String::new();
        for ch in text.chars() {
            if ch.is_alphanumeric() || ch == '_' || ch == '.' {
                current_word.push(ch);
            } else {
                if current_word.len() > 1 {
                    if Self::looks_like_type(&current_word)
                        || current_word.contains('.')
                        || current_word == "any"
                        || current_word == "Any"
                    {
                        refs.insert(current_word.clone());
                    }
                }
                current_word.clear();
            }
        }
        if current_word.len() > 1 {
            if Self::looks_like_type(&current_word)
                || current_word.contains('.')
                || current_word == "any"
                || current_word == "Any"
            {
                refs.insert(current_word);
            }
        }
    }


}
