// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionRepository (consequence-gating module)
// AC #2: malformed / over-cap → `Err` (fail closed); missing file → `Ok(None)`.

use rigorix_engine::precondition::domain::PreconditionError;
use rigorix_engine::precondition::infrastructure::repository::{
    PreconditionRepository, TomlPreconditionRepository,
};

fn temp_file(content: &str) -> std::path::PathBuf {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("preconditions.toml");
    std::fs::write(&path, content).expect("write temp config");
    std::mem::forget(dir);
    path
}

const VALID: &str = r#"
[[preconditions]]
id = "beneficiary-eligible"
match = { tool = "payment_execute" }
require_params = ["/beneficiary", "/amount"]
command = ["/opt/rigorix/checks/beneficiary-eligible"]
timeout_ms = 5000

[gating]
release_dependents_on_failure = false
"#;

#[test]
fn test_preconditionrepository_is_defined() {
    let repository = TomlPreconditionRepository::new(".rigorix/preconditions.toml");
    assert_eq!(
        repository.config_path(),
        std::path::Path::new(".rigorix/preconditions.toml")
    );
}

#[test]
fn test_preconditionrepository_is_object_safe() {
    let repository: Box<dyn PreconditionRepository> = Box::new(TomlPreconditionRepository::new(
        ".rigorix/preconditions.toml",
    ));
    let _ = &repository;
}

#[tokio::test]
async fn missing_file_is_ok_none_fail_open_absent() {
    let repository = TomlPreconditionRepository::new("/nonexistent/rigorix/preconditions.toml");
    assert!(matches!(repository.load_config().await, Ok(None)));
}

#[tokio::test]
async fn valid_file_loads_with_all_fields() {
    let repository = TomlPreconditionRepository::new(temp_file(VALID));
    let config = repository
        .load_config()
        .await
        .expect("load")
        .expect("present");
    assert_eq!(config.preconditions.len(), 1);
    assert_eq!(config.preconditions[0].id, "beneficiary-eligible");
    assert_eq!(
        config.preconditions[0].require_params,
        vec!["/beneficiary".to_string(), "/amount".to_string()]
    );
    assert!(!config.gating.release_dependents_on_failure);
}

#[tokio::test]
async fn malformed_file_fails_closed() {
    let repository = TomlPreconditionRepository::new(temp_file("this is not = valid toml [["));
    let error = repository.load_config().await.expect_err("fail closed");
    assert!(matches!(error, PreconditionError::ConfigInvalid(_)));
    assert!(!error.is_retriable());
}

#[tokio::test]
async fn over_cap_file_fails_closed() {
    let mut content = String::new();
    for i in 0..=100 {
        content.push_str(&format!(
            "[[preconditions]]\nid = \"p{i}\"\nmatch = {{ tool = \"payment_execute\" }}\ncommand = [\"/opt/rigorix/checks/p{i}\"]\n"
        ));
    }
    let repository = TomlPreconditionRepository::new(temp_file(&content));
    let error = repository.load_config().await.expect_err("fail closed");
    assert!(matches!(error, PreconditionError::ConfigInvalid(_)));
}
