// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionRepository (consequence-gating module)
// Contract freeze: the repository port + `.rigorix/preconditions.toml` loading
// semantics are frozen here; parse/fail-closed behavior lands in
// ISSUE-CONSEQUENCE-GATING-2.

use rigorix_engine::precondition::infrastructure::repository::{
    PreconditionRepository, TomlPreconditionRepository,
};

#[test]
fn test_preconditionrepository_is_defined() {
    // The filesystem repository is constructible over the operator config path.
    let repository = TomlPreconditionRepository::new(".rigorix/preconditions.toml");
    assert_eq!(
        repository.config_path(),
        std::path::Path::new(".rigorix/preconditions.toml")
    );
}

#[test]
fn test_preconditionrepository_is_object_safe() {
    // The port is injectable as a trait object (the service/factory contract).
    let repository: Box<dyn PreconditionRepository> = Box::new(TomlPreconditionRepository::new(
        ".rigorix/preconditions.toml",
    ));
    // Loading semantics (missing ⇒ Ok(None), malformed ⇒ Err) are behavior and
    // land in ISSUE-CONSEQUENCE-GATING-2; the freeze asserts the port shape.
    let _ = &repository;
}
