// Generated by Guardian TDD
// From: IdpClient (Infrastructure) (auth module)
// TDD Contract: IdpClient trait with discover, device_authorization,
// poll_token, refresh_token, revoke_token

#![allow(unused_imports)]

use async_trait::async_trait;

use rigorix_mcp::auth::domain::error::AuthError;
use rigorix_mcp::auth::domain::value::Secret;
use rigorix_mcp::auth::infrastructure::idp_client::{
    DeviceAuthorization, IdpClient, IdpMetadata, TokenPoll, TokenResponse,
};
use rigorix_mcp::auth::infrastructure::HttpIdpClient;

/// Minimal contract-conforming stub — proves the frozen IdpClient trait is
/// implementable with the ISSUE-AUTH-2 method set. The real HTTP client and
/// its unit tests live in src/auth/infrastructure/idp_client_impl.rs.
struct IdpClientTddContract;

#[async_trait]
impl IdpClient for IdpClientTddContract {
    async fn discover(&self) -> Result<IdpMetadata, AuthError> {
        Ok(IdpMetadata {
            issuer: "https://idp.example.com".into(),
            device_authorization_endpoint: "https://idp.example.com/device".into(),
            token_endpoint: "https://idp.example.com/token".into(),
            revocation_endpoint: None,
            jwks_uri: None,
        })
    }

    async fn device_authorization(
        &self,
        _client_id: &str,
    ) -> Result<DeviceAuthorization, AuthError> {
        Ok(DeviceAuthorization {
            device_code: Secret::new("device-code-1".into()),
            user_code: "ABCD-EFGH".into(),
            verification_uri: "https://idp.example.com/device".into(),
            expires_in: 600,
            interval_secs: 5,
            issued_at: chrono::Utc::now(),
        })
    }

    async fn poll_token(
        &self,
        _device_code: &Secret<String>,
        _client_id: &str,
    ) -> Result<TokenPoll, AuthError> {
        Ok(TokenPoll::Pending {
            retry_after_secs: Some(5),
        })
    }

    async fn refresh_token(
        &self,
        _refresh_token: &Secret<String>,
        _client_id: &str,
    ) -> Result<TokenResponse, AuthError> {
        Ok(TokenResponse {
            access_token: Secret::new("access-token-1".into()),
            refresh_token: None,
            expires_in: 900,
            token_type: "Bearer".into(),
            scope: None,
        })
    }

    async fn revoke_token(
        &self,
        _refresh_token: &Secret<String>,
        _client_id: &str,
    ) -> Result<(), AuthError> {
        Ok(())
    }
}

#[test]
fn test_idpclient_infrastructure_is_defined() {
    let client = IdpClientTddContract;
    let rt = tokio::runtime::Runtime::new().unwrap();
    let meta = rt.block_on(client.discover()).unwrap();
    assert_eq!(meta.issuer, "https://idp.example.com");
}

#[test]
fn test_idpclient_infrastructure_device_flow_methods() {
    let client = IdpClientTddContract;
    let rt = tokio::runtime::Runtime::new().unwrap();
    let auth = rt
        .block_on(client.device_authorization("rigorix-cli"))
        .unwrap();
    assert_eq!(auth.user_code, "ABCD-EFGH");
    assert_eq!(auth.expires_in, 600);

    let poll = rt
        .block_on(client.poll_token(&auth.device_code, "rigorix-cli"))
        .unwrap();
    assert!(matches!(poll, TokenPoll::Pending { .. }));
}

#[test]
fn test_http_idp_client_is_constructible() {
    // HTTPS issuers are accepted; plain-HTTP issuers are rejected unless
    // loopback (transport security policy, ISSUE-AUTH-2).
    assert!(HttpIdpClient::new("https://idp.example.com").is_ok());
    assert!(HttpIdpClient::new("http://idp.example.com").is_err());
}
