// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: Orchestrator (R2) (sequence-policy module)
// Contract freeze: the data contract consumed at the plan-time insertion
// point (before `build_graph_from_steps` seals the graph) is frozen here —
// a matched `promote` step is built `requires_approval = true`, a matched
// `deny` step fails with `SequencePolicyDenied`. The integration behavior
// (pause → approve → executes / reject → skipped) lands in the
// orchestrator-r2 issue.

use rigorix_engine::sequence_policy::application::PlannedStep;
use rigorix_engine::sequence_policy::domain::{RuleAction, SequenceMatch, StepPredicate};
use serde_json::json;

/// The ordered runbook (remove then add) that must produce a promotion.
fn remove_then_add_runbook() -> Vec<PlannedStep> {
    vec![
        PlannedStep {
            name: "registration_remove".to_string(),
            tool: "registration_remove".to_string(),
            parameters: json!({ "event_id": "conf-2026" }),
        },
        PlannedStep {
            name: "registration_add".to_string(),
            tool: "registration_add".to_string(),
            parameters: json!({ "event_id": "conf-2026" }),
        },
    ]
}

#[test]
fn test_orchestrator_r2_is_defined() {
    // A runbook containing remove-then-add yields a match naming the LATER
    // step — the step the orchestrator builds with requires_approval = true.
    let runbook = remove_then_add_runbook();
    assert_eq!(runbook.len(), 2);
    assert_eq!(runbook[0].tool, "registration_remove");
    assert_eq!(runbook[1].tool, "registration_add");
    // runbook[0] precedes runbook[1] in the ordered list — the adjacency the
    // matcher consumes (matching behavior in ISSUE-SEQUENCE-POLICY-5).
    assert_eq!(runbook[1].name, "registration_add");
}

#[test]
fn test_r2_promote_contract_pauses_the_later_step_for_human_decision() {
    let matched = SequenceMatch {
        rule_id: "registration-remove-then-reassign".to_string(),
        action: RuleAction::Promote,
        matched_indices: vec![0, 1],
        later_step: "registration_add".to_string(),
    };

    // Orchestrator branch at the graph-build site: promote → requires_approval.
    let requires_approval = match matched.action {
        RuleAction::Promote => true,
        RuleAction::Deny => false,
    };
    assert!(requires_approval);
    // The later step is the one gated — never the first step of the pair.
    assert_eq!(matched.later_step, "registration_add");
    assert!(matched.matched_indices.contains(&1));
}

#[test]
fn test_r2_deny_contract_never_calls_the_tool() {
    let matched = SequenceMatch {
        rule_id: "no-deny-pair".to_string(),
        action: RuleAction::Deny,
        matched_indices: vec![0, 1],
        later_step: "registration_add".to_string(),
    };

    // Orchestrator/engine branch: deny → later step fails before dispatch with
    // SequencePolicyDenied; the spy tool must never be invoked (integration
    // assertion lands in the orchestrator-r2 issue).
    let denied = matches!(matched.action, RuleAction::Deny);
    assert!(denied);
    assert_eq!(matched.later_step, "registration_add");
}

#[test]
fn test_r2_predicates_describe_the_pairs_an_operator_authors() {
    // The deny rule's later predicate is a plain StepPredicate pair — the
    // config schema the operator writes is frozen.
    let rule_steps = vec![
        StepPredicate {
            tool: "registration_remove".to_string(),
            params: vec![],
        },
        StepPredicate {
            tool: "registration_add".to_string(),
            params: vec![],
        },
    ];
    assert_eq!(rule_steps[0].tool, "registration_remove");
    assert_eq!(rule_steps[1].tool, "registration_add");
}
