// Generated by Guardian TDD
// From: ListTemplatesHandler (Domain Service) (template-tools module)
// Tests the frozen contract for ListTemplatesHandler trait.

#[cfg(test)]
mod tests {
    use rigorix_mcp::template_tools::application::service::ListTemplatesHandler;
    use rigorix_mcp::template_tools::domain::error::{HandlerError, ToolCallResult};
    use rigorix_mcp::template_tools::domain::value::TemplateFilter;

    /// Mock handler for testing the ListTemplatesHandler contract.
    struct MockListTemplatesHandler;

    #[async_trait::async_trait]
    impl ListTemplatesHandler for MockListTemplatesHandler {
        async fn handle(&self, filter: &TemplateFilter) -> Result<ToolCallResult, HandlerError> {
            let result = serde_json::json!({
                "templates": [],
                "filter": {
                    "tags": filter.tags(),
                    "search": filter.search(),
                    "limit": filter.limit()
                }
            });
            Ok(ToolCallResult::success(result))
        }
    }

    #[tokio::test]
    async fn test_list_templates_handler_is_defined() {
        let handler = MockListTemplatesHandler;
        let filter = TemplateFilter::default();
        let result = handler.handle(&filter).await;
        assert!(result.is_ok(), "Handler should succeed");
    }

    #[tokio::test]
    async fn test_list_templates_handler_with_filter() {
        let handler = MockListTemplatesHandler;
        let filter = TemplateFilter::new(
            Some(vec!["test".into()]),
            Some("search-term".into()),
            Some(10),
        );
        let result = handler.handle(&filter).await.expect("Handler should succeed");
        assert!(!result.is_error, "Result should not be an error");

        // Verify filter was passed through
        let content: serde_json::Value =
            serde_json::from_str(&result.content[0].text).expect("Should be valid JSON");
        assert_eq!(content["filter"]["limit"], 10);
    }

    #[tokio::test]
    async fn test_list_templates_handler_returns_tool_call_result() {
        let handler = MockListTemplatesHandler;
        let filter = TemplateFilter::default();
        let result = handler.handle(&filter).await;
        assert!(result.is_ok(), "Should return Ok(ToolCallResult)");
        let tool_result = result.unwrap();
        assert!(!tool_result.content.is_empty(), "Should have content");
        assert_eq!(tool_result.content[0].r#type, "text");
    }

    #[tokio::test]
    async fn test_list_templates_handler_is_send_sync() {
        let handler = MockListTemplatesHandler;
        // Verify it can be boxed and sent across threads
        let boxed: Box<dyn ListTemplatesHandler> = Box::new(handler);
        let _ = boxed;
    }
}
