// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: Precondition (consequence-gating module)
// Contract freeze: the aggregate fields + TOML/serde wire format are frozen
// here; matching + cap validation behavior lands in
// ISSUE-CONSEQUENCE-GATING-1/-2.

use rigorix_engine::precondition::domain::{
    DEFAULT_TIMEOUT_MS, FailureAction, GatingMode, Precondition, PreconditionConfig,
};
use serde_json::json;

/// The canonical operator entry from the module spec.
const PRECONDITION_TOML: &str = r#"
[[preconditions]]
id = "beneficiary-eligible"
match = { tool = "payment_execute" }
require_params = ["/beneficiary", "/amount"]
command = ["/opt/rigorix/checks/beneficiary-eligible"]
timeout_ms = 5000
failure = "deny"
capture_output = false

[gating]
release_dependents_on_failure = false
"#;

#[test]
fn test_precondition_is_defined() {
    let config: PreconditionConfig = toml::from_str(PRECONDITION_TOML).expect("operator TOML");
    assert_eq!(config.preconditions.len(), 1);
    let precondition = &config.preconditions[0];
    assert_eq!(precondition.id, "beneficiary-eligible");
    assert_eq!(precondition.r#match.tool, "payment_execute");
    assert_eq!(
        precondition.require_params,
        vec!["/beneficiary".to_string(), "/amount".to_string()]
    );
    assert_eq!(
        precondition.command,
        vec!["/opt/rigorix/checks/beneficiary-eligible".to_string()]
    );
    assert_eq!(precondition.timeout_ms, DEFAULT_TIMEOUT_MS);
    assert_eq!(precondition.failure, FailureAction::Deny);
    assert!(!precondition.capture_output);
}

#[test]
fn test_precondition_serde_round_trip_preserves_all_fields() {
    let config: PreconditionConfig = toml::from_str(PRECONDITION_TOML).expect("parse");
    let encoded = serde_json::to_string(&config).expect("serialize");
    let decoded: PreconditionConfig = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, config);
}

#[test]
fn test_precondition_defaults_are_fail_closed_deny_and_release_dependents() {
    // A minimal precondition omits timeout/failure/capture/require_params.
    let minimal: Precondition = serde_json::from_value(json!({
        "id": "minimal",
        "match": { "tool": "payment_execute" },
        "command": ["/opt/rigorix/checks/minimal"]
    }))
    .expect("minimal parses");
    assert_eq!(minimal.timeout_ms, DEFAULT_TIMEOUT_MS);
    assert_eq!(minimal.failure, FailureAction::Deny);
    assert!(!minimal.capture_output);
    assert!(minimal.require_params.is_empty());

    // An absent config is fail-closed and preserves today's dependents behavior.
    let default_config = PreconditionConfig::default();
    assert!(default_config.fail_closed);
    assert!(default_config.is_empty());
    assert_eq!(default_config.gating, GatingMode::default());
}

#[test]
fn test_command_is_an_argv_array_never_a_shell_string() {
    // The frozen schema types `command` as an array; a bare string must not
    // deserialize (no shell, no interpolation).
    let err = serde_json::from_value::<Precondition>(json!({
        "id": "shell",
        "match": { "tool": "payment_execute" },
        "command": "payment_execute --beneficiary $X"
    }));
    assert!(err.is_err(), "a shell string must not be a valid command");
}

#[test]
fn test_precondition_matches_via_reused_steppredicate() {
    // AC #1 behavior: the parsed precondition matches with the frozen
    // ADR-013 predicate semantics (tool exact/glob + param predicates).
    let config: PreconditionConfig = toml::from_str(PRECONDITION_TOML).expect("parse");
    let precondition = &config.preconditions[0];
    let params = json!({ "beneficiary": "acct-1", "amount": 100 });
    assert!(precondition.matches("payment_execute", &params).expect("m"));
    assert!(!precondition.matches("payment_cancel", &params).expect("m"));

    let glob: Precondition = serde_json::from_value(json!({
        "id": "glob",
        "match": { "tool": "payment_*" },
        "command": ["/opt/rigorix/checks/glob"]
    }))
    .expect("glob parses");
    assert!(glob.matches("payment_execute", &json!({})).expect("m"));
}
