// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionError (consequence-gating module)
// Contract freeze: the error taxonomy, its `Display`, and the "all variants
// non-retriable" rule are frozen here.

use rigorix_engine::precondition::domain::PreconditionError;

fn all_variants() -> Vec<PreconditionError> {
    vec![
        PreconditionError::ConfigInvalid("bad toml".to_string()),
        PreconditionError::NotArmed {
            precondition_id: "beneficiary-eligible".to_string(),
            detail: "missing executable".to_string(),
        },
        PreconditionError::Match {
            precondition_id: "beneficiary-eligible".to_string(),
            detail: "regex failed to compile".to_string(),
        },
        PreconditionError::Spawn {
            precondition_id: "beneficiary-eligible".to_string(),
            detail: "ENOENT".to_string(),
        },
        PreconditionError::Timeout {
            precondition_id: "beneficiary-eligible".to_string(),
            timeout_ms: 5000,
        },
        PreconditionError::Denied {
            precondition_id: "beneficiary-eligible".to_string(),
            step: "pay".to_string(),
        },
        PreconditionError::TrustBoundary {
            precondition_id: "beneficiary-eligible".to_string(),
            command: "./check".to_string(),
        },
    ]
}

#[test]
fn test_preconditionerror_is_defined() {
    assert_eq!(all_variants().len(), 7);
}

#[test]
fn test_all_variants_display() {
    for variant in all_variants() {
        let rendered = variant.to_string();
        assert!(!rendered.is_empty(), "empty Display for {variant:?}");
    }
    // Spot-check the operator-facing messages.
    assert!(
        PreconditionError::Timeout {
            precondition_id: "beneficiary-eligible".to_string(),
            timeout_ms: 5000,
        }
        .to_string()
        .contains("5000")
    );
    assert!(
        PreconditionError::NotArmed {
            precondition_id: "beneficiary-eligible".to_string(),
            detail: "missing executable".to_string(),
        }
        .to_string()
        .contains("unarmed")
    );
}

#[test]
fn test_all_variants_are_non_retriable() {
    // A denied authority is not retriable; no precondition error ever is.
    for variant in all_variants() {
        assert!(
            !variant.is_retriable(),
            "precondition error must be non-retriable: {variant:?}"
        );
    }
}
