// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionFinding (consequence-gating module)
// Contract freeze: the envelope finding + `PreconditionChecked` event payload
// and the SpanPrivacy redaction boundary are frozen here; envelope emission
// lands in ISSUE-CONSEQUENCE-GATING-8.

use chrono::Utc;
use rigorix_engine::precondition::domain::{
    PreconditionChecked, PreconditionFinding, PreconditionOutcome,
};
use serde_json::json;

fn finding(outcome: PreconditionOutcome, exit_code: Option<i32>) -> PreconditionFinding {
    PreconditionFinding {
        precondition_id: "beneficiary-eligible".to_string(),
        step: "pay".to_string(),
        outcome,
        exit_code,
        inputs_hash: "sha256:deadbeef".to_string(),
        checked_at: Utc::now(),
        summary: None,
    }
}

#[test]
fn test_preconditionfinding_is_defined() {
    let finding = finding(PreconditionOutcome::Failed, Some(3));
    assert_eq!(finding.precondition_id, "beneficiary-eligible");
    assert_eq!(finding.step, "pay");
    assert_eq!(finding.outcome, PreconditionOutcome::Failed);
    assert_eq!(finding.exit_code, Some(3));
}

#[test]
fn test_finding_records_outcome_exit_code_hash_and_timestamp() {
    let finding = finding(PreconditionOutcome::Passed, Some(0));
    let value = serde_json::to_value(&finding).expect("serialize");
    // Frozen evidence fields.
    assert_eq!(value["outcome"], "passed");
    assert_eq!(value["exit_code"], 0);
    assert_eq!(value["inputs_hash"], "sha256:deadbeef");
    assert!(value["checked_at"].is_string());
    // SpanPrivacy: no parameter values, no stdout by default.
    assert!(value.get("parameters").is_none());
    assert!(value.get("stdout").is_none());
}

#[test]
fn test_precondition_checked_event_payload_is_frozen() {
    let checked = PreconditionChecked {
        execution_id: uuid::Uuid::nil(),
        precondition_id: "beneficiary-eligible".to_string(),
        step: "pay".to_string(),
        outcome: PreconditionOutcome::Error,
        exit_code: None,
        inputs_hash: "sha256:deadbeef".to_string(),
        summary: "precondition 'beneficiary-eligible' error step 'pay'".to_string(),
        timestamp: Utc::now(),
    };
    let encoded = serde_json::to_string(&checked).expect("serialize");
    let decoded: PreconditionChecked = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, checked);
    // An indeterminate error carries no exit code, and is distinct from failed.
    assert_eq!(decoded.outcome, PreconditionOutcome::Error);
    assert_eq!(json!(decoded.outcome.as_str()), json!("error"));
}

#[test]
fn test_decision_summary_redacts_values() {
    let summary = finding(PreconditionOutcome::Failed, Some(1)).decision_summary();
    assert!(summary.contains("beneficiary-eligible"));
    assert!(summary.contains("failed"));
    assert!(summary.contains("exit 1"));
    assert!(!summary.contains("acct-"));
}
