//! EngineFacade — Aggregate Root interface for the Execution Tools bounded context.
//!
//! @canonical .pi/architecture/modules/execution-tools.md#enginefacade
//! Implements: Contract Freeze — EngineFacade trait
//!
//! The EngineFacade is the aggregate root providing a thin async facade over
//! rigorix-engine public APIs. All execution/audit/template MCP tools call
//! through this interface.
//!
//! # Invariants (Frozen)
//!
//! - All method calls are governed by configurable timeout
//! - Never panics — errors are wrapped in `EngineFacadeError`
//! - Enforcement status is always fresh (never cached — queries engine on each call)
//! - Execution IDs are generated by rigorix-engine, not the gateway
//!
//! # Contract (Frozen)
//!
//! - All methods are async (use async-trait)
//! - All methods return Result with EngineFacadeError
//! - No implementation logic — pure interface
//! - Thread-safe (Send + Sync)

use async_trait::async_trait;
use std::sync::Arc;

use super::error::EngineFacadeError;
use super::value::{
    ApprovalResult, CostBreakdown, EnforcementStatus, ExecutionId, ExecutionResult, PlanTemplate,
    ValidationResult,
};

/// Thin async facade over rigorix-engine public APIs.
///
/// All methods are governed by configurable timeout. Enforcement status
/// is always fresh (never cached). Execution IDs are generated by
/// rigorix-engine, not the gateway.
#[async_trait]
pub trait EngineFacade: Send + Sync {
    /// Execute a plan against the rigorix-engine.
    ///
    /// Delegates to the execution engine's DAG executor.
    /// Returns execution result with per-step outcomes.
    ///
    /// # Errors
    /// - `EngineFacadeError::EngineNotAvailable` if engine is unreachable
    /// - `EngineFacadeError::Timeout` if execution exceeds configured duration
    /// - `EngineFacadeError::BudgetExceeded` if enforcement budget is exhausted
    /// - `EngineFacadeError::EnforcementBlocked` if policy blocks execution
    async fn execute(
        &self,
        plan: PlanTemplate,
        repository: Option<String>,
        author: Option<String>,
    ) -> Result<ExecutionResult, EngineFacadeError>;

    /// Validate a plan against enforcement policies.
    ///
    /// Checks the plan against the policy engine without executing it.
    /// Returns validation results with warnings, errors, and cost estimates.
    ///
    /// # Errors
    /// - `EngineFacadeError::EngineNotAvailable` if engine is unreachable
    /// - `EngineFacadeError::InvalidPlan` if plan structure is invalid
    async fn validate_plan(
        &self,
        plan: PlanTemplate,
    ) -> Result<ValidationResult, EngineFacadeError>;

    /// Check current enforcement status.
    ///
    /// Queries the policy engine for active enforcement preset,
    /// remaining budget, and circuit breaker states.
    /// Always returns fresh data (never cached).
    ///
    /// # Errors
    /// - `EngineFacadeError::EngineNotAvailable` if engine is unreachable
    async fn check_enforcement(&self) -> Result<EnforcementStatus, EngineFacadeError>;

    /// Get detailed cost breakdown for a completed execution.
    ///
    /// Retrieves per-step token usage, total tool calls, and optional
    /// monetary cost from the audit engine.
    ///
    /// # Errors
    /// - `EngineFacadeError::ExecutionNotFound` if execution_id doesn't exist
    async fn get_execution_cost(
        &self,
        execution_id: &ExecutionId,
    ) -> Result<CostBreakdown, EngineFacadeError>;

    /// Run a named template through the orchestrator's full `run()` path.
    ///
    /// Uses the template name as the intent string, goes through the planning
    /// pipeline (template loading, graph generation, validation rules), then
    /// executes the DAG. This is the same path the CLI uses.
    ///
    /// Returns execution results with per-step outcomes.
    async fn run_template(
        &self,
        template_name: &str,
        repository: Option<String>,
        author: Option<String>,
    ) -> Result<ExecutionResult, EngineFacadeError>;

    /// Approve steps of an execution paused for human sign-off and resume it.
    ///
    /// Grants approval for steps that declared `requires_approval: true` in
    /// the plan (see [`ExecutionResult::status`]). If no steps remain pending,
    /// the paused execution resumes automatically.
    ///
    /// # Errors
    /// - `EngineFacadeError::ExecutionNotFound` if `execution_id` doesn't exist
    async fn approve_execution(
        &self,
        execution_id: &ExecutionId,
        step_names: Vec<String>,
        identity: Option<crate::execution_tools::domain::value::ApprovalIdentity>,
    ) -> Result<ApprovalResult, EngineFacadeError>;

    /// Get the per-node state of an execution after it ran or resumed.
    ///
    /// Used to refresh the audit envelope after a resumed approval so the
    /// evidence reflects the FINAL run state (all steps, statuses) rather
    /// than the paused snapshot.
    async fn execution_state(
        &self,
        execution_id: &ExecutionId,
    ) -> Result<crate::execution_tools::domain::value::ExecutionStateInfo, EngineFacadeError>;
}

/// Shared ownership of an EngineFacade implementation.
pub type SharedEngineFacade = Arc<dyn EngineFacade>;
