// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: ExecutionIntent (approval module)
// Contract freeze: the value object is defined; canonical serialization
// behavior lands in ISSUE-EXECUTIONINTENT (#787).

use rigorix_engine::approval::domain::ExecutionIntent;
use serde_json::json;

#[test]
fn test_executionintent_is_defined() {
    let intent = ExecutionIntent {
        tool: "run_command".to_string(),
        intent: json!({"command": "cargo test", "cwd": "/repo"}),
        declared_scope: vec!["src/".to_string(), "Cargo.toml".to_string()],
    };
    assert_eq!(intent.tool, "run_command");
    assert_eq!(intent.declared_scope.len(), 2);
}

#[test]
fn test_executionintent_serde_round_trip() {
    let intent = ExecutionIntent {
        tool: "file_write".to_string(),
        intent: json!({"path": "docs/x.md", "content": "hi"}),
        declared_scope: vec!["docs/x.md".to_string()],
    };
    let encoded = serde_json::to_string(&intent).expect("serialize");
    let decoded: ExecutionIntent = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, intent);
}
