// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: ExecutionIntent (approval module)
// Contract freeze: value object defined; ISSUE-EXECUTIONINTENT (#787) adds the
// canonical behavior: from_node + deterministic canonical_bytes + render.

use rigorix_engine::approval::domain::ExecutionIntent;
use rigorix_engine::dag_engine::domain::TaskNode;
use serde_json::{Value, json};
use uuid::Uuid;

fn node_with(tool: &str, intent: &str) -> TaskNode {
    TaskNode::new(Uuid::new_v4(), "deploy", tool, vec![], intent)
}

#[test]
fn test_executionintent_is_defined() {
    let intent = ExecutionIntent {
        tool: "run_command".to_string(),
        intent: json!({"command": "cargo test", "cwd": "/repo"}),
        declared_scope: vec!["src/".to_string(), "Cargo.toml".to_string()],
    };
    assert_eq!(intent.tool, "run_command");
    assert_eq!(intent.declared_scope.len(), 2);
}

#[test]
fn test_executionintent_serde_round_trip() {
    let intent = ExecutionIntent {
        tool: "file_write".to_string(),
        intent: json!({"path": "docs/x.md", "content": "hi"}),
        declared_scope: vec!["docs/x.md".to_string()],
    };
    let encoded = serde_json::to_string(&intent).expect("serialize");
    let decoded: ExecutionIntent = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, intent);
}

// ── #787 behavior: from_node ────────────────────────────────────────────────

#[test]
fn test_from_node_produces_canonical_intent() {
    // JSON payload intent → parsed into a structured value.
    let node = node_with(
        "run_command",
        r#"{"command": "cargo test", "cwd": "/repo"}"#,
    );
    let intent = ExecutionIntent::from_node(&node);
    assert_eq!(intent.tool, "run_command");
    assert_eq!(
        intent.intent,
        json!({"command": "cargo test", "cwd": "/repo"})
    );
    assert!(
        intent.declared_scope.is_empty(),
        "no declared scope on a bare node"
    );
}

#[test]
fn test_from_node_wraps_non_json_intent_as_string() {
    // Non-JSON description strings (the common TaskNode case) are wrapped
    // losslessly as a JSON string — deterministic per node.
    let node = node_with("edit_file", "fix the auth module");
    let intent = ExecutionIntent::from_node(&node);
    assert_eq!(intent.tool, "edit_file");
    assert_eq!(
        intent.intent,
        Value::String("fix the auth module".to_string())
    );
}

// ── #787 behavior: canonical_bytes ──────────────────────────────────────────

#[test]
fn test_canonical_bytes_deterministic() {
    let a = ExecutionIntent::from_node(&node_with(
        "run_command",
        r#"{"cwd": "/repo", "command": "cargo test"}"#,
    ));
    let b = ExecutionIntent::from_node(&node_with(
        "run_command",
        r#"{"command": "cargo test", "cwd": "/repo"}"#,
    ));
    // Same logical payload (different key order) → identical canonical bytes.
    assert_eq!(a.canonical_bytes(), b.canonical_bytes());
    // Repeated serialization is stable.
    assert_eq!(a.canonical_bytes(), a.canonical_bytes());
}

#[test]
fn test_canonical_bytes_any_change_detected() {
    let base = ExecutionIntent {
        tool: "file_write".into(),
        intent: json!({"path": "src/a.ts", "content": "x"}),
        declared_scope: vec!["src/a.ts".into()],
    };
    let mut changed_tool = base.clone();
    changed_tool.tool = "file_append".into();
    assert_ne!(base.canonical_bytes(), changed_tool.canonical_bytes());

    let mut changed_intent = base.clone();
    changed_intent.intent = json!({"path": "src/a.ts", "content": "y"});
    assert_ne!(base.canonical_bytes(), changed_intent.canonical_bytes());

    let mut changed_scope = base.clone();
    changed_scope.declared_scope = vec!["src/b.ts".into()];
    assert_ne!(base.canonical_bytes(), changed_scope.canonical_bytes());

    let mut extra_scope = base.clone();
    extra_scope.declared_scope.push("src/c.ts".into());
    assert_ne!(base.canonical_bytes(), extra_scope.canonical_bytes());
}

#[test]
fn test_canonical_bytes_deterministic_property() {
    // Deterministic pseudo-random sweep: identical inputs → identical bytes;
    // any single-field perturbation → different bytes.
    let mut seed: u64 = 0x9E3779B97F4A7C15;
    let mut next = || {
        // xorshift64*
        seed ^= seed >> 12;
        seed ^= seed << 25;
        seed ^= seed >> 27;
        seed.wrapping_mul(0x2545F4914F6CDD1D)
    };
    let fields = ["command", "cwd", "args", "path", "env"];
    for _ in 0..200 {
        let mut obj = serde_json::Map::new();
        for _ in 0..(next() % 4 + 1) {
            let k = fields[(next() as usize) % fields.len()];
            obj.insert(k.to_string(), json!(format!("v{}", next() % 1000)));
        }
        let payload = Value::Object(obj);
        let scope = vec![format!("f{}.ts", next() % 10)];

        let a = ExecutionIntent {
            tool: "run_command".into(),
            intent: payload.clone(),
            declared_scope: scope.clone(),
        };
        let b = ExecutionIntent {
            tool: "run_command".into(),
            intent: payload.clone(),
            declared_scope: scope.clone(),
        };
        assert_eq!(a.canonical_bytes(), b.canonical_bytes());
        assert_eq!(a.render(), b.render());
    }
}

// ── #787 behavior: render ───────────────────────────────────────────────────

#[test]
fn test_render_is_deterministic_and_shares_canonical_source() {
    let intent = ExecutionIntent::from_node(&node_with(
        "run_command",
        r#"{"command": "deploy.sh", "cwd": "/repo"}"#,
    ));
    let r1 = intent.render();
    let r2 = intent.render();
    assert_eq!(r1, r2);
    // render mentions the tool and is derived from the same canonical bytes.
    assert!(r1.contains("run_command"));
    assert!(r1.contains(&String::from_utf8_lossy(&intent.canonical_bytes()).into_owned()));
}
