// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: MCP surface (sequence-policy module)
// Contract freeze: the structured finding that `rigorix_validate_plan` must
// return pre-run for a matched sequence is frozen here (a serialized
// `SequenceMatch` — rule id, action, matched indices, later step). The MCP
// tool surface itself lands in the mcp-surface issue (execution-tools crate).

use rigorix_engine::sequence_policy::domain::{RuleAction, SequenceMatch};
use serde_json::{Value, json};

#[test]
fn test_mcp_surface_is_defined() {
    // A plan with a matched sequence produces a structured finding before run.
    let finding = SequenceMatch {
        rule_id: "registration-remove-then-reassign".to_string(),
        action: RuleAction::Promote,
        matched_indices: vec![0, 2],
        later_step: "registration_add".to_string(),
    };
    let value: Value = serde_json::to_value(&finding).expect("structured finding");
    assert_eq!(value["rule_id"], "registration-remove-then-reassign");
    assert_eq!(value["action"], json!("promote"));
    assert_eq!(value["later_step"], "registration_add");
    assert_eq!(value["matched_indices"], json!([0, 2]));
}

#[test]
fn test_validate_plan_finding_is_round_trippable() {
    // The finding is JSON — serializable into the validate_plan response and
    // deserializable by tooling/UI.
    let finding = SequenceMatch {
        rule_id: "registration-remove-then-reassign".to_string(),
        action: RuleAction::Promote,
        matched_indices: vec![0, 2],
        later_step: "registration_add".to_string(),
    };
    let encoded = serde_json::to_string(&finding).expect("serialize");
    let decoded: SequenceMatch = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, finding);
}
