// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: Fail-closed (sequence-policy module)
// Contract freeze: corrupt rule config refuses the plan — the error surface
// and `fail_closed` default are frozen here. The integration behavior
// (corrupt config → plan refused, no steps execute) lands in the fail-closed
// issue via `TomlSequencePolicyRepository::load_config`.

use rigorix_engine::sequence_policy::domain::{
    SafetyCaps, SequencePolicyConfig, SequencePolicyError,
};

#[test]
fn test_fail_closed_is_defined() {
    // The typed error a corrupt config surfaces at plan time. Non-retriable:
    // the operator fixes the file; no plan runs under an unparseable rule set.
    let err =
        SequencePolicyError::InvalidConfig("parse error at line 3: expected `[[rules]]`".into());
    assert!(!err.is_retriable());
    assert_eq!(
        err.to_string(),
        "Rule config invalid: parse error at line 3: expected `[[rules]]`"
    );
}

#[test]
fn test_fail_closed_default_is_on() {
    // `fail_closed` defaults to true — a corrupt rule file must refuse the
    // plan rather than silently degrade. The config schema (operator file)
    // round-trips it.
    let empty: SequencePolicyConfig = serde_json::from_str("{}").expect("empty config object");
    assert!(empty.fail_closed, "fail_closed must default to true");

    let explicit: SequencePolicyConfig =
        serde_json::from_str(r#"{"fail_closed": false, "rules": []}"#)
            .expect("explicit fail_closed");
    assert!(!explicit.fail_closed);
}

#[test]
fn test_safety_caps_are_part_of_the_config_contract() {
    // Over-cap rules surface as RuleExceedsCaps (non-retriable, operator
    // action). Caps live on SafetyCaps; enforcement lands with the
    // fail-closed issue (SequencePolicyConfig::validate).
    let caps = SafetyCaps {
        max_rules_per_file: 100,
        max_steps_per_rule: 8,
        max_window: 5,
        max_regex_predicates_per_file: 8,
    };
    let over_cap = SequencePolicyError::RuleExceedsCaps {
        rule: "registration-remove-then-reassign".into(),
        detail: format!("window 10 exceeds cap {}", caps.max_window),
    };
    assert!(!over_cap.is_retriable());
    assert!(over_cap.to_string().contains("exceeds safety caps"));
}
