// Generated by Guardian TDD
// From: ListAuditsHandler (Domain Service) (audit-tools module)
// Tests the ListAuditsHandlerImpl.

#[cfg(test)]
mod tests {
    use std::sync::Arc;
    use uuid::Uuid;

    use rigorix_mcp::audit_tools::application::dto::ListAuditsInput;
    use rigorix_mcp::audit_tools::application::service::ListAuditsHandler;
    use rigorix_mcp::audit_tools::application::service_impl::ListAuditsHandlerImpl;
    use rigorix_mcp::audit_tools::domain::formatter_impl::AuditFormatterImpl;
    use rigorix_mcp::audit_tools::infrastructure::InMemoryAuditQueryService;
    use rigorix_mcp::execution_tools::domain::value::ExecutionStatus;

    #[tokio::test]
    async fn test_listauditshandler_empty() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = ListAuditsHandlerImpl::new(query_service, formatter);

        let input = ListAuditsInput {
            status: None,
            since: None,
            until: None,
            template: None,
            limit: Some(50),
        };

        let result = handler.handle(input).await;
        assert!(result.is_ok());
        let tc = result.unwrap();
        assert!(!tc.is_error);
        assert!(tc.content[0].text.contains("No audit records"));
    }

    #[tokio::test]
    async fn test_listauditshandler_with_results() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let now = chrono::Utc::now();

        for i in 0..3 {
            query_service
                .store(InMemoryAuditQueryService::create_sample(
                    Uuid::new_v4(),
                    ExecutionStatus::Completed,
                    Some("test".into()),
                    now - chrono::Duration::hours(i as i64),
                    1000,
                ))
                .unwrap();
        }

        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = ListAuditsHandlerImpl::new(query_service, formatter);

        let input = ListAuditsInput {
            status: None,
            since: None,
            until: None,
            template: None,
            limit: Some(50),
        };

        let result = handler.handle(input).await;
        assert!(result.is_ok());
        let tc = result.unwrap();
        assert!(!tc.is_error);
        assert!(tc.content[0].text.contains("3 total"));
    }

    #[tokio::test]
    async fn test_listauditshandler_invalid_limit() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = ListAuditsHandlerImpl::new(query_service, formatter);

        let input = ListAuditsInput {
            status: None,
            since: None,
            until: None,
            template: None,
            limit: Some(0),
        };

        let result = handler.handle(input).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_listauditshandler_filter_by_status() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let now = chrono::Utc::now();

        query_service
            .store(InMemoryAuditQueryService::create_sample(
                Uuid::new_v4(),
                ExecutionStatus::Completed,
                None,
                now - chrono::Duration::hours(2),
                1000,
            ))
            .unwrap();
        query_service
            .store(InMemoryAuditQueryService::create_sample(
                Uuid::new_v4(),
                ExecutionStatus::Failed,
                None,
                now - chrono::Duration::hours(1),
                1000,
            ))
            .unwrap();

        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = ListAuditsHandlerImpl::new(query_service, formatter);

        let input = ListAuditsInput {
            status: Some("Failed".into()),
            since: None,
            until: None,
            template: None,
            limit: Some(50),
        };

        let result = handler.handle(input).await;
        assert!(result.is_ok());
    }
}
