//! Data Transfer Objects for the Execution Tools module.
//!
//! @canonical .pi/architecture/modules/execution-tools.md#dto
//! Implements: Contract Freeze — all input/output DTO schemas
//!
//! DTOs define the input/output contracts for all service operations.
//! They carry documentation and validation metadata but no behavior.
//!
//! # Contract (Frozen)
//!
//! - Every service operation has a dedicated input and output DTO
//! - DTOs are serializable (JSON for API)
//! - Validation constraints are documented in field docs
//! - Fields use reasonable Rust types

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::execution_tools::domain::value::PlanTemplate;

// ---------------------------------------------------------------------------
// Execute DTOs
// ---------------------------------------------------------------------------

/// Input for the `rigorix_execute` tool call.
///
/// Contains the plan to execute with optional template name and execution ID.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecuteInput {
    /// The plan to execute (structured plan with steps).
    pub plan: PlanTemplate,

    /// Optional template name for audit trail enrichment.
    pub template_name: Option<String>,

    /// Optional pre-generated execution ID (for idempotency).
    /// If not provided, generated by rigorix-engine.
    pub execution_id: Option<Uuid>,
}

// ---------------------------------------------------------------------------
// Validate DTOs
// ---------------------------------------------------------------------------

/// Input for the `rigorix_validate_plan` tool call.
///
/// Contains the plan to validate against enforcement policies.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidateInput {
    /// The plan to validate (structured plan with steps).
    pub plan: PlanTemplate,
}

// ---------------------------------------------------------------------------
// Check Enforcement DTOs
// ---------------------------------------------------------------------------

/// Output from `rigorix_check_enforcement` formatted as JSON for MCP response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckEnforcementOutput {
    /// Whether enforcement is currently active.
    pub active: bool,

    /// Name of the active enforcement preset.
    pub preset: String,

    /// Current budget status.
    pub budget: BudgetDto,

    /// Active circuit breaker states.
    pub circuit_breakers: Vec<CircuitBreakerDto>,
}

/// Budget information DTO for enforcement responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetDto {
    /// Total tool call limit.
    pub tool_calls_total: u64,
    /// Remaining tool calls.
    pub tool_calls_remaining: u64,
    /// Total token limit.
    pub tokens_total: u64,
    /// Remaining tokens.
    pub tokens_remaining: u64,
}

/// Circuit breaker status DTO for enforcement responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircuitBreakerDto {
    /// Circuit breaker name.
    pub name: String,
    /// Whether the circuit breaker is tripped (open).
    pub is_tripped: bool,
    /// Human-readable description.
    pub description: String,
}

// ---------------------------------------------------------------------------
// Execution Result DTOs
// ---------------------------------------------------------------------------

/// Output from `rigorix_execute` formatted for MCP response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecuteOutput {
    /// Unique execution identifier.
    pub execution_id: Uuid,

    /// Overall execution status.
    pub status: String,

    /// Per-step results in plan order.
    pub steps: Vec<StepResultDto>,

    /// Total execution duration in milliseconds.
    pub duration_ms: u64,

    /// Optional token usage count.
    pub tokens_used: Option<u64>,

    /// URI to the persistent audit record.
    pub audit_uri: String,
}

/// Per-step result DTO.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StepResultDto {
    /// Step name.
    pub step_name: String,

    /// Whether the step succeeded.
    pub success: bool,

    /// Optional error message if step failed.
    pub error: Option<String>,

    /// Step output data.
    pub output: serde_json::Value,

    /// Duration in milliseconds.
    pub duration_ms: u64,
}

// ---------------------------------------------------------------------------
// Validation Result DTOs
// ---------------------------------------------------------------------------

/// Output from `rigorix_validate_plan` formatted for MCP response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidateOutput {
    /// Whether the plan is valid.
    pub valid: bool,

    /// Warning messages (non-blocking issues).
    pub warnings: Vec<String>,

    /// Error messages (blocking issues).
    pub errors: Vec<String>,

    /// Optional estimated cost of execution.
    pub estimated_cost: Option<CostEstimateDto>,
}

/// Cost estimate DTO.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CostEstimateDto {
    /// Estimated token count.
    pub estimated_tokens: u64,
    /// Estimated tool calls.
    pub estimated_tool_calls: u64,
    /// Optional monetary estimate.
    pub estimated_cost_micro: Option<u64>,
}
