// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: DecisionContext (approval module)
// Contract freeze: the R4 context type is defined and serde round-trip;
// summary redaction (SpanPrivacy reuse) lands in ISSUE-DECISIONCONTEXT (#790).

use rigorix_engine::approval::domain::DecisionContext;
use serde_json::json;

fn full_context() -> DecisionContext {
    DecisionContext {
        rendered_step: "edit_file src/auth.rs".to_string(),
        upstream_evidence: Some(json!({"tests": 42, "passed": 40})),
        state_snapshot: Some(json!({"git": "abc123", "branch": "main"})),
        summary: "edit auth module".to_string(),
        full_payload: Some(json!({"rendered_step": "edit_file src/auth.rs"})),
    }
}

#[test]
fn test_decisioncontext_is_defined() {
    let ctx = full_context();
    assert_eq!(ctx.summary, "edit auth module");
    assert!(ctx.full_payload.is_some());
    assert!(ctx.upstream_evidence.is_some());
}

#[test]
fn test_decisioncontext_degraded_summary_only() {
    // Degraded state: rendered step + summary only (evidence unavailable).
    let degraded = DecisionContext {
        rendered_step: "run_command cargo test".to_string(),
        upstream_evidence: None,
        state_snapshot: None,
        summary: "run tests".to_string(),
        full_payload: None,
    };
    assert!(degraded.upstream_evidence.is_none());
    assert!(degraded.full_payload.is_none());
    let encoded = serde_json::to_string(&degraded).expect("serialize");
    let decoded: DecisionContext = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, degraded);
}

#[test]
fn test_decisioncontext_serde_round_trip() {
    let ctx = full_context();
    let encoded = serde_json::to_string(&ctx).expect("serialize");
    let decoded: DecisionContext = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, ctx);
}
