// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: DecisionContext (approval module)
// Contract freeze: the R4 context type is defined and serde round-trip;
// summary redaction (SpanPrivacy reuse) lands in ISSUE-DECISIONCONTEXT (#790).

use rigorix_engine::approval::domain::DecisionContext;
use serde_json::json;

fn full_context() -> DecisionContext {
    DecisionContext {
        rendered_step: "edit_file src/auth.rs".to_string(),
        upstream_evidence: Some(json!({"tests": 42, "passed": 40})),
        state_snapshot: Some(json!({"git": "abc123", "branch": "main"})),
        summary: "edit auth module".to_string(),
        full_payload: Some(json!({"rendered_step": "edit_file src/auth.rs"})),
    }
}

#[test]
fn test_decisioncontext_is_defined() {
    let ctx = full_context();
    assert_eq!(ctx.summary, "edit auth module");
    assert!(ctx.full_payload.is_some());
    assert!(ctx.upstream_evidence.is_some());
}

#[test]
fn test_decisioncontext_degraded_summary_only() {
    // Degraded state: rendered step + summary only (evidence unavailable).
    let degraded = DecisionContext {
        rendered_step: "run_command cargo test".to_string(),
        upstream_evidence: None,
        state_snapshot: None,
        summary: "run tests".to_string(),
        full_payload: None,
    };
    assert!(degraded.upstream_evidence.is_none());
    assert!(degraded.full_payload.is_none());
    let encoded = serde_json::to_string(&degraded).expect("serialize");
    let decoded: DecisionContext = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, degraded);
}

#[test]
fn test_decisioncontext_serde_round_trip() {
    let ctx = full_context();
    let encoded = serde_json::to_string(&ctx).expect("serialize");
    let decoded: DecisionContext = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, ctx);
}

// ── #790 behavior: envelope-safe summary + SpanPrivacy redaction ────────────

#[test]
fn test_summary_redacts_api_key_using_span_privacy() {
    // AC #14: an api_key inside decision_context must be redacted in the summary.
    let ctx = DecisionContext {
        rendered_step: "call openai".to_string(),
        upstream_evidence: Some(json!({
            "api_key": "sk-0123456789abcdef",
            "model": "gpt-4",
            "nested": {"secret": "hunter2", "ok": "visible"}
        })),
        state_snapshot: Some(json!({"git": "abc123"})),
        summary: String::new(), // will be derived
        full_payload: None,
    };
    let summary = ctx.summarize();
    assert!(
        !summary.contains("sk-0123456789abcdef"),
        "raw api_key leaked: {summary}"
    );
    assert!(!summary.contains("hunter2"), "raw secret leaked: {summary}");
    assert!(
        summary.contains("<redacted>"),
        "summary must mark redaction"
    );
    assert!(summary.contains("visible"), "non-sensitive fields survive");
    assert!(summary.contains("gpt-4"));
}

#[test]
fn test_summarize_excludes_full_payload_by_default() {
    // AC #13: full payload is opt-in — the summary never embeds it.
    let ctx = DecisionContext {
        rendered_step: "deploy".to_string(),
        upstream_evidence: None,
        state_snapshot: None,
        summary: String::new(),
        full_payload: Some(json!({"very": "long", "private": {"api_key": "x"}})),
    };
    let summary = ctx.summarize();
    assert!(!summary.contains("very"));
    assert!(!summary.contains("private"));
    assert!(summary.contains("deploy"));
}

#[test]
fn test_summarize_is_deterministic_and_redaction_util_reused() {
    let ctx = DecisionContext {
        rendered_step: "run tests".to_string(),
        upstream_evidence: Some(json!({"results": {"passed": 3}, "api_token": "tok-1"})),
        state_snapshot: Some(json!({"branch": "main"})),
        summary: String::new(),
        full_payload: None,
    };
    let s1 = ctx.summarize();
    let s2 = ctx.summarize();
    assert_eq!(s1, s2, "summarize must be deterministic");
    assert!(!s1.contains("tok-1"));

    // The redaction helper is the same span_privacy classification used by
    // observability — reuse, not a parallel implementation.
    let redacted =
        DecisionContext::redact_value(&json!({"authorization": "Bearer x", "user": "u"}));
    assert_eq!(redacted["authorization"], json!("<redacted>"));
    assert_eq!(redacted["user"], json!("u"));
    assert!(rigorix_engine::observability::span_privacy::is_sensitive_field("api_key"));
}
