// Generated by Guardian TDD — rewritten as behavioral tests (was an inert
// `assert!(false)` scaffold).
// From: PreconditionService (consequence-gating module)
// AC #6: matched step exit 0 → Dispatch; non-zero → Deny.
// AC #7: require_params absent → Deny before the command runs.
// AC #8: non-matching step is unaffected (no process spawned).
// AC #9: determinism — same step + config + process → same verdict.

use std::sync::{Arc, Mutex};

use async_trait::async_trait;
use rigorix_engine::precondition::application::{
    DispatchStep, PreconditionCheckInput, PreconditionService, PreconditionServiceImpl,
};
use rigorix_engine::precondition::domain::{
    GatingMode, Precondition, PreconditionConfig, PreconditionError, PreconditionOutcome,
    PreconditionVerdict,
};
use rigorix_engine::precondition::infrastructure::repository::PreconditionRepository;
use rigorix_engine::precondition::infrastructure::{PreconditionRun, PreconditionRunner};
use serde_json::json;

struct StubRepository {
    outcome: Result<Option<PreconditionConfig>, PreconditionError>,
}

#[async_trait]
impl PreconditionRepository for StubRepository {
    async fn load_config(&self) -> Result<Option<PreconditionConfig>, PreconditionError> {
        self.outcome.clone()
    }
}

/// Records every precondition id it is asked to run.
struct RecordingRunner {
    calls: Arc<Mutex<Vec<String>>>,
    outcome: PreconditionOutcome,
}

#[async_trait]
impl PreconditionRunner for RecordingRunner {
    async fn run(
        &self,
        precondition: &Precondition,
        _input: &PreconditionCheckInput,
    ) -> Result<PreconditionRun, PreconditionError> {
        self.calls.lock().unwrap().push(precondition.id.clone());
        let exit_code = match self.outcome {
            PreconditionOutcome::Passed => Some(0),
            PreconditionOutcome::Failed => Some(1),
            PreconditionOutcome::Error => None,
        };
        Ok(PreconditionRun {
            outcome: self.outcome,
            exit_code,
            stdout: None,
        })
    }
}

/// Always fails to run (timeout/spawn/trust boundary).
struct FailingRunner;

#[async_trait]
impl PreconditionRunner for FailingRunner {
    async fn run(
        &self,
        precondition: &Precondition,
        _input: &PreconditionCheckInput,
    ) -> Result<PreconditionRun, PreconditionError> {
        Err(PreconditionError::Timeout {
            precondition_id: precondition.id.clone(),
            timeout_ms: 100,
        })
    }
}

fn precondition(id: &str, tool: &str, require_params: &[&str]) -> Precondition {
    serde_json::from_value(json!({
        "id": id,
        "match": { "tool": tool },
        "require_params": require_params,
        "command": ["/opt/rigorix/checks/x"]
    }))
    .expect("precondition parses")
}

fn config(preconditions: Vec<Precondition>) -> PreconditionConfig {
    PreconditionConfig {
        fail_closed: true,
        preconditions,
        gating: GatingMode::default(),
    }
}

fn service(
    repository_outcome: Result<Option<PreconditionConfig>, PreconditionError>,
    runner: Box<dyn PreconditionRunner>,
) -> PreconditionServiceImpl {
    PreconditionServiceImpl::new(
        Box::new(StubRepository {
            outcome: repository_outcome,
        }),
        runner,
    )
}

fn step(tool: &str, parameters: serde_json::Value) -> DispatchStep {
    DispatchStep {
        name: "pay".to_string(),
        tool: tool.to_string(),
        parameters,
    }
}

#[tokio::test]
async fn matched_exit_zero_dispatches_and_non_zero_denies() {
    let calls = Arc::new(Mutex::new(Vec::new()));
    let pass = service(
        Ok(Some(config(vec![precondition(
            "p1",
            "payment_execute",
            &[],
        )]))),
        Box::new(RecordingRunner {
            calls: calls.clone(),
            outcome: PreconditionOutcome::Passed,
        }),
    );
    let verdict = pass
        .evaluate(
            uuid::Uuid::nil(),
            &step("payment_execute", json!({ "beneficiary": "acct-1" })),
        )
        .await
        .expect("evaluate");
    assert_eq!(verdict, PreconditionVerdict::Dispatch);
    assert_eq!(calls.lock().unwrap().as_slice(), ["p1"]);

    let deny = service(
        Ok(Some(config(vec![precondition(
            "p1",
            "payment_execute",
            &[],
        )]))),
        Box::new(RecordingRunner {
            calls: Arc::new(Mutex::new(Vec::new())),
            outcome: PreconditionOutcome::Failed,
        }),
    );
    let verdict = deny
        .evaluate(
            uuid::Uuid::nil(),
            &step("payment_execute", json!({ "beneficiary": "acct-1" })),
        )
        .await
        .expect("evaluate");
    assert_eq!(
        verdict,
        PreconditionVerdict::Deny {
            precondition_id: "p1".to_string(),
            outcome: PreconditionOutcome::Failed,
        }
    );
}

#[tokio::test]
async fn missing_required_param_denies_before_the_command_runs() {
    let calls = Arc::new(Mutex::new(Vec::new()));
    let svc = service(
        Ok(Some(config(vec![precondition(
            "p1",
            "payment_execute",
            &["/beneficiary", "/amount"],
        )]))),
        Box::new(RecordingRunner {
            calls: calls.clone(),
            outcome: PreconditionOutcome::Passed,
        }),
    );
    let verdict = svc
        .evaluate(
            uuid::Uuid::nil(),
            &step("payment_execute", json!({ "beneficiary": "acct-1" })),
        )
        .await
        .expect("evaluate");
    assert!(matches!(
        verdict,
        PreconditionVerdict::Deny { ref precondition_id, .. } if precondition_id == "p1"
    ));
    assert!(
        calls.lock().unwrap().is_empty(),
        "the command must not run when require_params is absent"
    );
}

#[tokio::test]
async fn null_required_param_is_absent() {
    let svc = service(
        Ok(Some(config(vec![precondition(
            "p1",
            "payment_execute",
            &["/amount"],
        )]))),
        Box::new(FailingRunner),
    );
    let verdict = svc
        .evaluate(
            uuid::Uuid::nil(),
            &step("payment_execute", json!({ "amount": null })),
        )
        .await
        .expect("evaluate");
    assert!(matches!(verdict, PreconditionVerdict::Deny { .. }));
}

#[tokio::test]
async fn non_matching_step_spawns_nothing_and_dispatches() {
    let calls = Arc::new(Mutex::new(Vec::new()));
    let svc = service(
        Ok(Some(config(vec![precondition(
            "p1",
            "payment_execute",
            &[],
        )]))),
        Box::new(RecordingRunner {
            calls: calls.clone(),
            outcome: PreconditionOutcome::Failed,
        }),
    );
    let verdict = svc
        .evaluate(uuid::Uuid::nil(), &step("payment_cancel", json!({})))
        .await
        .expect("evaluate");
    assert_eq!(verdict, PreconditionVerdict::Dispatch);
    assert!(
        calls.lock().unwrap().is_empty(),
        "no process must be spawned"
    );
}

#[tokio::test]
async fn indeterminate_runner_failure_refuses_as_error() {
    let svc = service(
        Ok(Some(config(vec![precondition(
            "p1",
            "payment_execute",
            &[],
        )]))),
        Box::new(FailingRunner),
    );
    let verdict = svc
        .evaluate(uuid::Uuid::nil(), &step("payment_execute", json!({})))
        .await
        .expect("evaluate");
    assert_eq!(
        verdict,
        PreconditionVerdict::Deny {
            precondition_id: "p1".to_string(),
            outcome: PreconditionOutcome::Error,
        }
    );
}

#[tokio::test]
async fn absent_config_is_fail_open_absent() {
    let svc = service(Ok(None), Box::new(FailingRunner));
    assert_eq!(
        svc.evaluate(uuid::Uuid::nil(), &step("payment_execute", json!({})))
            .await
            .expect("evaluate"),
        PreconditionVerdict::Dispatch
    );
    assert!(!svc.is_configured().await.expect("configured"));
}

#[tokio::test]
async fn corrupt_config_fails_closed() {
    let svc = service(
        Err(PreconditionError::ConfigInvalid("bad".to_string())),
        Box::new(FailingRunner),
    );
    let error = svc
        .evaluate(uuid::Uuid::nil(), &step("payment_execute", json!({})))
        .await
        .expect_err("fail closed");
    assert!(!error.is_retriable());
}

#[tokio::test]
async fn determinism_same_input_same_verdict() {
    // AC #9: identical step + config + deterministic check → identical verdict.
    let svc = service(
        Ok(Some(config(vec![precondition(
            "p1",
            "payment_execute",
            &[],
        )]))),
        Box::new(RecordingRunner {
            calls: Arc::new(Mutex::new(Vec::new())),
            outcome: PreconditionOutcome::Passed,
        }),
    );
    let step = step("payment_execute", json!({ "beneficiary": "acct-1" }));
    let first = svc
        .evaluate(uuid::Uuid::nil(), &step)
        .await
        .expect("evaluate");
    for _ in 0..50 {
        assert_eq!(
            svc.evaluate(uuid::Uuid::nil(), &step)
                .await
                .expect("evaluate"),
            first
        );
    }
}

#[tokio::test]
async fn is_configured_reports_precondition_presence() {
    let configured = service(
        Ok(Some(config(vec![precondition(
            "p1",
            "payment_execute",
            &[],
        )]))),
        Box::new(FailingRunner),
    );
    assert!(configured.is_configured().await.expect("configured"));
    let empty = service(Ok(Some(config(vec![]))), Box::new(FailingRunner));
    assert!(!empty.is_configured().await.expect("configured"));
}
