// Generated by Guardian TDD
// From: identitysource
// Corrected (GAP-A-24): the tested type is now implemented — the
// is_defined / interacts_with_none assertions exercise the real type.

#[cfg(test)]
mod tests {
    use rigorix_engine::identity::domain::IdentitySource;

    #[test]
    fn test_identitysource_is_defined() {
        assert_ne!(IdentitySource::IdpToken, IdentitySource::LocalPrincipal);
        assert_ne!(IdentitySource::LocalPrincipal, IdentitySource::Unverified);
    }

    #[test]
    fn test_identitysource_interacts_with_none() {
        assert!(matches!(IdentitySource::IdpToken, IdentitySource::IdpToken));
    }
}
