// Generated by Guardian TDD — rewritten as behavioral/integration tests (was an
// inert `assert!(false)` scaffold).
// From: DispatchGate (consequence-gating module)
// AC #10: a refused step's tool is never called (spy asserts); node marked failed.
// AC #11: a configured-but-unarmed precondition refuses a matching step (unarmed).

use std::sync::atomic::{AtomicUsize, Ordering};

use async_trait::async_trait;
use rigorix_engine::precondition::application::{
    DispatchGate, DispatchStep, PreconditionCheckInput, PreconditionDispatchGate,
    PreconditionService, PreconditionServiceImpl,
};
use rigorix_engine::precondition::domain::{
    GatingMode, Precondition, PreconditionConfig, PreconditionError, PreconditionOutcome,
    PreconditionVerdict,
};
use rigorix_engine::precondition::infrastructure::repository::PreconditionRepository;
use rigorix_engine::precondition::infrastructure::{PreconditionRun, PreconditionRunner};
use serde_json::json;

/// The downstream tool spy. Incremented ONLY when a step actually dispatches.
#[derive(Default)]
struct ToolSpy {
    calls: AtomicUsize,
}

impl ToolSpy {
    fn dispatch(&self) {
        self.calls.fetch_add(1, Ordering::SeqCst);
    }
    fn calls(&self) -> usize {
        self.calls.load(Ordering::SeqCst)
    }
}

/// A fixed-verdict precondition service.
struct StubService {
    verdict: PreconditionVerdict,
}

#[async_trait]
impl PreconditionService for StubService {
    async fn evaluate(
        &self,
        _execution_id: uuid::Uuid,
        _step: &DispatchStep,
    ) -> Result<PreconditionVerdict, PreconditionError> {
        Ok(self.verdict.clone())
    }

    async fn is_configured(&self) -> Result<bool, PreconditionError> {
        Ok(true)
    }
}

struct StubRepository {
    outcome: Result<Option<PreconditionConfig>, PreconditionError>,
}

#[async_trait]
impl PreconditionRepository for StubRepository {
    async fn load_config(&self) -> Result<Option<PreconditionConfig>, PreconditionError> {
        self.outcome.clone()
    }
}

/// A runner whose check always fails (non-zero exit).
struct FailingRunner;

#[async_trait]
impl PreconditionRunner for FailingRunner {
    async fn run(
        &self,
        _precondition: &Precondition,
        _input: &PreconditionCheckInput,
    ) -> Result<PreconditionRun, PreconditionError> {
        Ok(PreconditionRun {
            outcome: PreconditionOutcome::Failed,
            exit_code: Some(1),
            stdout: None,
        })
    }
}

fn step() -> DispatchStep {
    DispatchStep {
        name: "pay".to_string(),
        tool: "payment_execute".to_string(),
        parameters: json!({ "beneficiary": "acct-1" }),
    }
}

/// Mirror the dispatch-loop choke point: the tool is called ONLY on `Dispatch`.
async fn dispatch(gate: &dyn DispatchGate, spy: &ToolSpy) -> &'static str {
    match gate.assess(uuid::Uuid::nil(), &step()).await {
        Ok(PreconditionVerdict::Dispatch) => {
            spy.dispatch();
            "dispatched"
        }
        Ok(PreconditionVerdict::Deny { .. }) => "precondition_denied",
        Err(PreconditionError::NotArmed { .. }) => "precondition_unarmed",
        Err(_) => "precondition_error",
    }
}

#[test]
fn test_dispatchgate_is_defined() {
    let gate = PreconditionDispatchGate::new(Box::new(StubService {
        verdict: PreconditionVerdict::Dispatch,
    }));
    assert!(gate.is_armed_sync());
}

#[tokio::test]
async fn refused_step_never_calls_the_tool_and_marks_failed() {
    // AC #10: a denial at the gate must never reach the tool.
    let spy = ToolSpy::default();
    let gate = PreconditionDispatchGate::new(Box::new(StubService {
        verdict: PreconditionVerdict::Deny {
            precondition_id: "beneficiary-eligible".to_string(),
            outcome: PreconditionOutcome::Failed,
        },
    }));
    let outcome = dispatch(&gate, &spy).await;
    assert_eq!(outcome, "precondition_denied");
    assert_eq!(spy.calls(), 0, "the tool must never be called on a refusal");
}

#[tokio::test]
async fn allowed_step_calls_the_tool() {
    // Control: a passing verdict dispatches.
    let spy = ToolSpy::default();
    let gate = PreconditionDispatchGate::new(Box::new(StubService {
        verdict: PreconditionVerdict::Dispatch,
    }));
    assert_eq!(dispatch(&gate, &spy).await, "dispatched");
    assert_eq!(spy.calls(), 1);
}

#[tokio::test]
async fn configured_but_unarmed_refuses_matching_step() {
    // AC #11: configured-but-unarmed is fail-closed, never a silent downgrade.
    let spy = ToolSpy::default();
    let gate = PreconditionDispatchGate::unarmed(
        Box::new(StubService {
            verdict: PreconditionVerdict::Dispatch,
        }),
        "missing executable",
    );
    let outcome = dispatch(&gate, &spy).await;
    assert_eq!(outcome, "precondition_unarmed");
    assert_eq!(spy.calls(), 0);
    assert!(!gate.is_armed().await.expect("armed check"));

    // Direct gate contract: `assess` returns the structured NotArmed error.
    let error = gate
        .assess(uuid::Uuid::nil(), &step())
        .await
        .expect_err("unarmed must refuse");
    assert!(matches!(error, PreconditionError::NotArmed { .. }));
    assert!(!error.is_retriable());
}

#[tokio::test]
async fn real_service_denial_through_the_gate_never_calls_the_tool() {
    // End-to-end through PreconditionServiceImpl: a matching precondition whose
    // check fails refuses at the gate.
    let config = PreconditionConfig {
        fail_closed: true,
        preconditions: vec![
            serde_json::from_value(json!({
                "id": "beneficiary-eligible",
                "match": { "tool": "payment_execute" },
                "command": ["/opt/rigorix/checks/beneficiary-eligible"]
            }))
            .expect("precondition"),
        ],
        gating: GatingMode::default(),
    };
    let service = PreconditionServiceImpl::new(
        Box::new(StubRepository {
            outcome: Ok(Some(config)),
        }),
        Box::new(FailingRunner),
    );
    let gate = PreconditionDispatchGate::new(Box::new(service));
    let spy = ToolSpy::default();
    assert_eq!(dispatch(&gate, &spy).await, "precondition_denied");
    assert_eq!(spy.calls(), 0);
    assert!(gate.is_armed().await.expect("armed"));
}
