// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: DispatchGate (consequence-gating module)
// Contract freeze: the single choke-point trait and the fail-closed arming
// contract are frozen here; the execution_engine wiring lands in
// ISSUE-CONSEQUENCE-GATING-5.

use async_trait::async_trait;
use rigorix_engine::precondition::application::{DispatchGate, DispatchStep};
use rigorix_engine::precondition::domain::{PreconditionError, PreconditionVerdict};
use serde_json::json;

/// A no-op gate: no preconditions configured → always Dispatch, not armed.
struct NoopGate;

#[async_trait]
impl DispatchGate for NoopGate {
    async fn assess(
        &self,
        _execution_id: uuid::Uuid,
        _step: &DispatchStep,
    ) -> Result<PreconditionVerdict, PreconditionError> {
        Ok(PreconditionVerdict::Dispatch)
    }

    async fn is_armed(&self) -> Result<bool, PreconditionError> {
        Ok(false)
    }
}

/// A configured-but-unarmed gate: refuses fail-closed.
struct UnarmedGate;

#[async_trait]
impl DispatchGate for UnarmedGate {
    async fn assess(
        &self,
        _execution_id: uuid::Uuid,
        _step: &DispatchStep,
    ) -> Result<PreconditionVerdict, PreconditionError> {
        Err(PreconditionError::NotArmed {
            precondition_id: "beneficiary-eligible".to_string(),
            detail: "missing executable".to_string(),
        })
    }

    async fn is_armed(&self) -> Result<bool, PreconditionError> {
        Ok(true)
    }
}

fn step() -> DispatchStep {
    DispatchStep {
        name: "pay".to_string(),
        tool: "payment_execute".to_string(),
        parameters: json!({}),
    }
}

#[test]
fn test_dispatchgate_is_defined() {
    let gate: Box<dyn DispatchGate> = Box::new(NoopGate);
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("runtime");
    let verdict = runtime
        .block_on(gate.assess(uuid::Uuid::nil(), &step()))
        .expect("no preconditions configured");
    assert!(verdict.allows_dispatch());
    assert!(!runtime.block_on(gate.is_armed()).expect("armed check"));
}

#[test]
fn test_dispatchgate_refuses_fail_closed_when_unarmed() {
    let gate: Box<dyn DispatchGate> = Box::new(UnarmedGate);
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("runtime");
    let err = runtime
        .block_on(gate.assess(uuid::Uuid::nil(), &step()))
        .expect_err("configured-but-unarmed must refuse");
    assert!(matches!(err, PreconditionError::NotArmed { .. }));
    assert!(!err.is_retriable());
}
