// Generated by Guardian TDD
// From: CreateTemplateHandler (Domain Service) (template-tools module)
// Tests the frozen contract for CreateTemplateHandler trait.

#[cfg(test)]
mod tests {
    use rigorix_mcp::template_tools::application::service::CreateTemplateHandler;
    use rigorix_mcp::template_tools::domain::error::{HandlerError, ToolCallResult};
    use rigorix_mcp::template_tools::domain::value::{
        CreateTemplateInput, PlanTemplate, StepDefinition,
    };

    /// Helper: create a minimal valid PlanTemplate for testing.
    fn make_test_template(name: &str) -> PlanTemplate {
        let step = StepDefinition::new(
            "step-1".into(),
            "test_tool".into(),
            serde_json::json!({}),
            false,
            "Test step".into(),
            None,
        );
        let now = chrono::Utc::now();
        PlanTemplate::new(
            name.into(),
            "Test description".into(),
            "1.0.0".into(),
            vec![],
            vec![step],
            None,
            std::collections::HashMap::new(),
            now,
            now,
        )
        .expect("Failed to create test template")
    }

    /// Mock handler for testing the CreateTemplateHandler contract.
    struct MockCreateTemplateHandler;

    #[async_trait::async_trait]
    impl CreateTemplateHandler for MockCreateTemplateHandler {
        async fn handle(
            &self,
            input: &CreateTemplateInput,
        ) -> Result<ToolCallResult, HandlerError> {
            let result = serde_json::json!({
                "name": input.name,
                "path": format!(".rigorix/templates/{}.toml", input.name),
                "status": "created"
            });
            Ok(ToolCallResult::success(result))
        }
    }

    #[tokio::test]
    async fn test_create_template_handler_is_defined() {
        let handler = MockCreateTemplateHandler;
        let input = CreateTemplateInput {
            name: "new-template".into(),
            plan: make_test_template("new-template"),
            overwrite: false,
        };
        let result = handler.handle(&input).await;
        assert!(result.is_ok(), "Handler should succeed");
    }

    #[tokio::test]
    async fn test_create_template_handler_with_overwrite() {
        let handler = MockCreateTemplateHandler;
        let input = CreateTemplateInput {
            name: "existing-template".into(),
            plan: make_test_template("existing-template"),
            overwrite: true,
        };
        let result = handler.handle(&input).await.expect("Handler should succeed");
        assert!(!result.is_error, "Result should not be an error");

        let content: serde_json::Value =
            serde_json::from_str(&result.content[0].text).expect("Should be valid JSON");
        assert_eq!(content["name"], "existing-template");
        assert_eq!(content["status"], "created");
    }

    #[tokio::test]
    async fn test_create_template_handler_returns_tool_call_result() {
        let handler = MockCreateTemplateHandler;
        let input = CreateTemplateInput {
            name: "new".into(),
            plan: make_test_template("new"),
            overwrite: false,
        };
        let result = handler.handle(&input).await;
        assert!(result.is_ok(), "Should return Ok(ToolCallResult)");
        let tool_result = result.unwrap();
        assert!(!tool_result.content.is_empty(), "Should have content");
    }

    #[tokio::test]
    async fn test_create_template_handler_is_send_sync() {
        let handler = MockCreateTemplateHandler;
        let boxed: Box<dyn CreateTemplateHandler> = Box::new(handler);
        let _ = boxed;
    }
}
