// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: Fail-open-absent (sequence-policy module)
// Contract freeze: no config file → `Ok(None)` from the repository → no rules
// → no gating (status quo). The repository interface + empty-config semantics
// are frozen here; the filesystem behavior (missing file → `Ok(None)`, run
// executes unchanged) lands in the fail-open-absent issue via
// `TomlSequencePolicyRepository::load_config`.

use rigorix_engine::sequence_policy::domain::{SequencePolicyConfig, SequencePolicyError};
use rigorix_engine::sequence_policy::infrastructure::SequencePolicyRepository;

#[test]
fn test_fail_open_absent_is_defined() {
    // The repository trait must be dyn-compatible and Send + Sync
    // (async-trait), so the service can hold Box<dyn SequencePolicyRepository>.
    fn assert_repository<T: Send + Sync + ?Sized>() {}
    assert_repository::<dyn SequencePolicyRepository>();

    // A missing optional config file is Ok(None) — not an error.
    let absent: Result<Option<SequencePolicyConfig>, SequencePolicyError> = Ok(None);
    assert!(absent.is_ok());
    assert!(absent.expect("ok").is_none());
}

#[test]
fn test_no_rules_means_no_gating() {
    // Empty rule set → no matches → status quo (run executes unchanged).
    let config = SequencePolicyConfig::default();
    assert!(config.rules.is_empty());
    // Default == an operator file with fail_closed set and no rules yet.
    let from_wire: SequencePolicyConfig =
        serde_json::from_str(r#"{"fail_closed": true, "rules": []}"#).expect("config");
    assert_eq!(config, from_wire);
}

#[test]
fn test_repository_error_is_never_silently_swallowed() {
    // Distinguish the two degradations at the type level: absence is Ok(None),
    // corruption is Err(...) (fail-closed). A load error must surface to the
    // caller — never a silent pass-through to "no rules".
    let corrupt: Result<Option<SequencePolicyConfig>, SequencePolicyError> =
        Err(SequencePolicyError::InvalidConfig("bad toml".into()));
    assert!(corrupt.is_err());
    match corrupt {
        Ok(_) => panic!("corrupt config must surface as Err, not Ok(None)"),
        Err(e) => assert!(!e.is_retriable()),
    }
}
