// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: Matcher (sequence-policy module)
// Contract freeze: the `SequenceMatch` result shape is frozen here (rule id,
// action, matched indices, later step); adjacent-pair / windowed / determinism
// *matching behavior* lands in ISSUE-SEQUENCE-POLICY-5.

use rigorix_engine::sequence_policy::domain::{RuleAction, SequenceMatch};
use serde_json::{Value, json};

fn remove_then_add_match(action: RuleAction) -> SequenceMatch {
    SequenceMatch {
        rule_id: "registration-remove-then-reassign".to_string(),
        action,
        matched_indices: vec![0, 3], // "registration_remove" then, 2 steps later, "registration_add"
        later_step: "registration_add_conf_2026".to_string(),
    }
}

#[test]
fn test_matcher_is_defined() {
    let matched = remove_then_add_match(RuleAction::Promote);
    assert_eq!(matched.rule_id, "registration-remove-then-reassign");
    assert_eq!(matched.matched_indices, vec![0, 3]);
    // later_step is the step the engine must promote or deny.
    assert_eq!(matched.later_step, "registration_add_conf_2026");
    assert_eq!(matched.action, RuleAction::Promote);
}

#[test]
fn test_sequence_match_serde_round_trip() {
    let matched = remove_then_add_match(RuleAction::Deny);
    let encoded = serde_json::to_string(&matched).expect("serialize");
    let decoded: SequenceMatch = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, matched);

    let value: Value = serde_json::from_str(&encoded).expect("value");
    assert_eq!(value["rule_id"], "registration-remove-then-reassign");
    assert_eq!(value["matched_indices"], json!([0, 3]));
    assert_eq!(value["later_step"], "registration_add_conf_2026");
    assert_eq!(value["action"], json!("deny"));
}

#[test]
fn test_match_action_drives_the_enforcement_branch() {
    // The orchestrator / execution-engine choke point branches on the
    // denormalized action without re-reading the rule set:
    //   Promote → later step built requires_approval = true
    //   Deny    → later step fails with SequencePolicyDenied, tool never called
    let promote = remove_then_add_match(RuleAction::Promote);
    let deny = remove_then_add_match(RuleAction::Deny);

    let action_taken = |m: &SequenceMatch| match m.action {
        RuleAction::Promote => "promote",
        RuleAction::Deny => "deny",
    };
    assert_eq!(action_taken(&promote), "promote");
    assert_eq!(action_taken(&deny), "deny");
}

#[test]
fn test_match_set_is_deterministic_over_the_same_input() {
    // Determinism property (R4): the same rule + ordered plan must produce the
    // same match set. Frozen here at the data level — the property test over
    // the real matcher lands with ISSUE-SEQUENCE-POLICY-5.
    let a = remove_then_add_match(RuleAction::Promote);
    let b = remove_then_add_match(RuleAction::Promote);
    assert_eq!(a, b);
    assert_eq!(
        serde_json::to_string(&a).unwrap(),
        serde_json::to_string(&b).unwrap()
    );
}
