// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: Permission (R5) (sequence-policy module)
// Contract freeze: the rule-config file the engine reads is operator-authored
// (R5) — never agent-writable. The frozen `fail_closed = true` default and
// the read-only config schema are asserted here; the `.rigorix/**` agent
// write-denial in the default permission config lands in the permission-r5
// issue (permission module).

use rigorix_engine::sequence_policy::domain::{
    ParamMatchKind, ParamPredicate, SequencePolicyConfig, StepPredicate,
};

#[test]
fn test_permission_r5_is_defined() {
    // Rule authorship is admin-controlled: the config is *parsed* (Deserialize)
    // by the engine, never written by the executing agent. The engine's
    // default posture is fail-closed (`fail_closed = true`), so an agent that
    // somehow corrupts the file cannot silently disable gating.
    let config = SequencePolicyConfig::default();
    assert!(config.fail_closed);
}

#[test]
fn test_operator_authored_config_schema_round_trips() {
    // The .rigorix/sequence-policy.toml schema (operator file) deserializes
    // into the frozen config contract.
    let config: SequencePolicyConfig = serde_json::from_str(
        r#"{
            "fail_closed": true,
            "rules": [{
                "id": "registration-remove-then-reassign",
                "name": "No remove-then-reassign",
                "description": "Removing to free a seat then registering is never autonomous",
                "steps": [
                    { "tool": "registration_remove" },
                    { "tool": "registration_add", "params": [{ "pointer": "/event_id", "kind": "exact", "value": "conf-2026" }] }
                ],
                "window": 3,
                "action": "promote"
            }]
        }"#,
    )
    .expect("operator config parses");
    assert!(config.fail_closed);
    assert_eq!(config.rules.len(), 1);
    let rule = &config.rules[0];
    assert_eq!(rule.steps.len(), 2);
    assert_eq!(rule.steps[1].params[0].kind, ParamMatchKind::Exact);

    // The parsed config survives a round trip unchanged.
    let encoded = serde_json::to_string(&config).expect("serialize");
    let decoded: SequencePolicyConfig = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, config);
}

#[test]
fn test_rule_predicates_are_data_not_agent_judgment() {
    // Predicates carry static strings — no free-form code, no conversation
    // content: an agent cannot smuggle judgment into the rule it is judged by.
    let predicate = StepPredicate {
        tool: "registration_add".to_string(),
        params: vec![ParamPredicate {
            pointer: "/event_id".to_string(),
            kind: ParamMatchKind::Exact,
            value: "conf-2026".to_string(),
        }],
    };
    let encoded = serde_json::to_string(&predicate).expect("serialize");
    assert!(!encoded.contains("llm"));
    assert!(!encoded.contains("conversation"));
}
