// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionRunner (consequence-gating module)
// AC #3/#4/#5: argv execution, JSON stdin, env set, exit-code mapping, no shell;
// a program inside the agent-writable workspace is refused; timeout and spawn
// failure map to refuse (`error`), never pass.

use rigorix_engine::precondition::application::PreconditionCheckInput;
use rigorix_engine::precondition::domain::{Precondition, PreconditionError, PreconditionOutcome};
use rigorix_engine::precondition::infrastructure::{
    PreconditionRun, PreconditionRunner, ProcessPreconditionRunner,
};
use serde_json::json;

fn precondition(id: &str, command: Vec<&str>) -> Precondition {
    serde_json::from_value(json!({
        "id": id,
        "match": { "tool": "payment_execute" },
        "command": command
    }))
    .expect("precondition parses")
}

fn input() -> PreconditionCheckInput {
    PreconditionCheckInput {
        precondition_id: "p1".to_string(),
        execution_id: uuid::Uuid::nil(),
        step: "pay".to_string(),
        tool: "payment_execute".to_string(),
        parameters: json!({ "beneficiary": "acct-1" }),
    }
}

fn runner() -> ProcessPreconditionRunner {
    ProcessPreconditionRunner::new(std::env::temp_dir())
}

#[test]
fn test_preconditionrunner_is_defined() {
    let runner = ProcessPreconditionRunner::new("/workspace/agent-writable");
    assert_eq!(
        runner.workspace_root(),
        std::path::Path::new("/workspace/agent-writable")
    );
}

#[test]
fn test_preconditionrunner_is_object_safe() {
    let runner: Box<dyn PreconditionRunner> =
        Box::new(ProcessPreconditionRunner::new("/workspace/agent-writable"));
    let _ = &runner;
}

#[test]
fn test_run_outcome_taxonomy_distinguishes_failed_from_error() {
    let failed = PreconditionRun {
        outcome: PreconditionOutcome::Failed,
        exit_code: Some(3),
        stdout: None,
        check_writable: None,
        authority_writable: None,
    };
    let error = PreconditionRun {
        outcome: PreconditionOutcome::Error,
        exit_code: None,
        stdout: None,
        check_writable: None,
        authority_writable: None,
    };
    assert!(failed.outcome.refuses());
    assert!(error.outcome.refuses());
    assert_ne!(failed.outcome, error.outcome);
}

#[tokio::test]
async fn argv_exit_codes_are_mapped() {
    let pass = runner()
        .run(
            &precondition("p1", vec!["/bin/sh", "-c", "exit 0"]),
            &input(),
        )
        .await
        .expect("run");
    assert_eq!(pass.outcome, PreconditionOutcome::Passed);
    assert_eq!(pass.exit_code, Some(0));

    let fail = runner()
        .run(
            &precondition("p1", vec!["/bin/sh", "-c", "exit 4"]),
            &input(),
        )
        .await
        .expect("run");
    assert_eq!(fail.outcome, PreconditionOutcome::Failed);
    assert_eq!(fail.exit_code, Some(4));
}

#[tokio::test]
async fn json_stdin_and_env_are_provided() {
    let run = runner()
        .run(
            &precondition(
                "p1",
                vec![
                    "/bin/sh",
                    "-c",
                    "read -r line || exit 9; [ \"$RIGORIX_TOOL\" = payment_execute ] || exit 9",
                ],
            ),
            &input(),
        )
        .await
        .expect("run");
    assert_eq!(run.outcome, PreconditionOutcome::Passed);
}

#[tokio::test]
async fn command_inside_workspace_is_refused() {
    let workspace = tempfile::tempdir().expect("tempdir");
    let check = workspace.path().join("check.sh");
    std::fs::write(&check, "#!/bin/sh\nexit 0\n").expect("write");
    let runner = ProcessPreconditionRunner::new(workspace.path());
    let error = runner
        .run(&precondition("p1", vec![check.to_str().unwrap()]), &input())
        .await
        .expect_err("trust boundary");
    assert!(matches!(error, PreconditionError::TrustBoundary { .. }));
}

#[tokio::test]
async fn timeout_and_spawn_failure_refuse_never_pass() {
    let mut slow = precondition("p1", vec!["/bin/sh", "-c", "sleep 5"]);
    slow.timeout_ms = 100;
    let timeout = runner().run(&slow, &input()).await.expect_err("timeout");
    assert!(matches!(timeout, PreconditionError::Timeout { .. }));
    assert!(!timeout.is_retriable());

    let spawn = runner()
        .run(
            &precondition("p1", vec!["/nonexistent/rigorix-check-xyz"]),
            &input(),
        )
        .await
        .expect_err("spawn");
    assert!(matches!(spawn, PreconditionError::Spawn { .. }));
    assert!(!spawn.is_retriable());
}
