// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: ApprovalService (approval module)
// Contract freeze: the service trait and IntentVerification verdict are
// defined; lifecycle behavior lands in ISSUE-APPROVALSERVICE (#792).

use rigorix_engine::approval::application::{ApprovalService, IntentVerification};
use rigorix_engine::approval::domain::{ApprovalStatus, IntentHash};

#[test]
fn test_approvalservice_is_defined() {
    // The service trait must be dyn-compatible and Send + Sync (async-trait).
    fn assert_service<T: Send + Sync + ?Sized>() {}
    assert_service::<dyn ApprovalService>();
}

#[test]
fn test_intent_verification_verdicts_are_frozen() {
    // R2 verdicts: Matched → dispatch; Mismatched → HALT; Invalid → never dispatch.
    assert!(matches!(
        IntentVerification::Matched,
        IntentVerification::Matched
    ));
    let mismatch = IntentVerification::Mismatched {
        expected: IntentHash("expected".into()),
        actual: IntentHash("actual".into()),
    };
    assert!(matches!(mismatch, IntentVerification::Mismatched { .. }));
    let invalid = IntentVerification::Invalid(ApprovalStatus::Expired);
    assert!(matches!(
        invalid,
        IntentVerification::Invalid(ApprovalStatus::Expired)
    ));
    // Verdict is serializable (recorded in audit/UI surfaces).
    let encoded = serde_json::to_string(&mismatch).expect("serialize");
    let decoded: IntentVerification = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, mismatch);
}
