// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: ApprovalService (approval module)
// Contract freeze: service trait + IntentVerification verdicts defined.
// ISSUE-APPROVALSERVICE (#792): lifecycle behavior — approve/verify/consume,
// mismatch halt, cross-process resume, retry-vs-replay, TTL, migration.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use chrono::Utc;
use rigorix_engine::approval::application::service_impl::{
    ApprovalServiceImpl, legacy_approvals_requiring_reapproval,
};
use rigorix_engine::approval::application::{
    ApprovalService, ApproveInput, IntentVerification, NodeIntentResolver, ResolvedNode,
};
use rigorix_engine::approval::domain::{
    ApprovalError, ApprovalStatus, DecisionContext, ExecutionIntent, IntentHash, ScopeViolation,
};
use rigorix_engine::approval::infrastructure::repository::{
    ApprovalRepository, FileBackedApprovalRepository, InMemoryApprovalRepository,
};
use serde_json::json;
use uuid::Uuid;

// ── mocks ────────────────────────────────────────────────────────────────────

struct MockResolver {
    // step name -> (node id, intent); interior mutability lets tests simulate
    // upstream state changes (tampering) between approve and dispatch.
    inner: std::sync::RwLock<HashMap<String, (Uuid, ExecutionIntent)>>,
}

impl MockResolver {
    fn from(intents: Vec<(&str, ExecutionIntent)>) -> Self {
        let mut by_name = HashMap::new();
        for (name, intent) in intents {
            by_name.insert(name.to_string(), (Uuid::new_v4(), intent));
        }
        Self {
            inner: std::sync::RwLock::new(by_name),
        }
    }

    /// Resolver with caller-controlled node ids — a resumed process must keep
    /// the SAME node ids as the pausing process (persisted graph identity).
    fn from_fixed(nodes: Vec<(Uuid, &str, ExecutionIntent)>) -> Self {
        let mut by_name = HashMap::new();
        for (id, name, intent) in nodes {
            by_name.insert(name.to_string(), (id, intent));
        }
        Self {
            inner: std::sync::RwLock::new(by_name),
        }
    }

    fn tamper(&self, name: &str, intent: ExecutionIntent) {
        if let Some(entry) = self.inner.write().unwrap().get_mut(name) {
            entry.1 = intent;
        }
    }
}

#[async_trait::async_trait]
impl NodeIntentResolver for MockResolver {
    async fn resolve_by_step_name(&self, step_name: &str) -> Option<ResolvedNode> {
        let map = self.inner.read().unwrap();
        map.get(step_name).map(|(id, intent)| ResolvedNode {
            node_id: *id,
            step_name: step_name.to_string(),
            intent: intent.clone(),
        })
    }
    async fn resolve_by_node_id(&self, node_id: Uuid) -> Option<ResolvedNode> {
        let map = self.inner.read().unwrap();
        map.iter()
            .find(|(_, (id, _))| *id == node_id)
            .map(|(name, (id, intent))| ResolvedNode {
                node_id: *id,
                step_name: name.clone(),
                intent: intent.clone(),
            })
    }
}

fn run_command(command: &str) -> ExecutionIntent {
    ExecutionIntent {
        tool: "run_command".into(),
        intent: json!({"command": command}),
        declared_scope: vec![],
    }
}

fn service(
    resolver: Arc<MockResolver>,
    repo: Arc<dyn ApprovalRepository>,
    ttl: Duration,
) -> ApprovalServiceImpl {
    ApprovalServiceImpl::new(repo, resolver, b"run-key".to_vec(), ttl)
}

fn approve_input(dag: Uuid, step: &str, approver: &str) -> ApproveInput {
    ApproveInput {
        dag_id: dag,
        step_names: vec![step.to_string()],
        approver_id: approver.to_string(),
        authority: Some("role:operator".into()),
        decision_context: None,
        token_claims_ref: Some("tok-ref".into()),
    }
}

#[tokio::test]
async fn test_approvalservice_is_defined() {
    fn assert_service<T: Send + Sync + ?Sized>() {}
    assert_service::<dyn ApprovalService>();
}

#[tokio::test]
async fn test_intent_verification_verdicts_are_frozen() {
    assert!(matches!(
        IntentVerification::Matched,
        IntentVerification::Matched
    ));
    let mismatch = IntentVerification::Mismatched {
        expected: IntentHash("expected".into()),
        actual: IntentHash("actual".into()),
    };
    assert!(matches!(mismatch, IntentVerification::Mismatched { .. }));
    let invalid = IntentVerification::Invalid(ApprovalStatus::Expired);
    assert!(matches!(
        invalid,
        IntentVerification::Invalid(ApprovalStatus::Expired)
    ));
    let encoded = serde_json::to_string(&mismatch).expect("serialize");
    let decoded: IntentVerification = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, mismatch);
}

// ── #792 AC #4: approve → identical intent verifies (dispatch proceeds) ─────

#[tokio::test]
async fn test_approve_then_identical_intent_verifies_matched() {
    let resolver = Arc::new(MockResolver::from(vec![(
        "deploy",
        run_command("deploy.sh"),
    )]));
    let repo = Arc::new(InMemoryApprovalRepository::new()) as Arc<dyn ApprovalRepository>;
    let svc = service(resolver.clone(), repo.clone(), Duration::from_secs(3600));

    let dag = Uuid::new_v4();
    let out = svc
        .approve(approve_input(dag, "deploy", "user@org"))
        .await
        .unwrap();
    assert_eq!(out.approved, vec!["deploy".to_string()]);
    assert!(out.not_found.is_empty());
    assert_eq!(out.approval_records.len(), 1);

    let record = out.approval_records[0].clone();
    assert_eq!(record.approver_id, "user@org");
    assert_eq!(record.authority.as_deref(), Some("role:operator"));
    assert_eq!(record.token_claims_ref.as_deref(), Some("tok-ref"));
    assert_eq!(record.status, ApprovalStatus::Pending);
    assert!(record.expires_at > record.decided_at);
    // R1: the record binds the exact dispatch payload (hash + payload).
    assert_eq!(
        record.intent_hash,
        IntentHash::compute(&run_command("deploy.sh"), b"run-key")
    );
    assert_eq!(
        record.intent_payload["intent"]["command"],
        json!("deploy.sh")
    );

    // R2: identical re-derived intent → Matched → the choke point dispatches.
    let verdict = svc.verify_intent(record.node_id).await.unwrap();
    assert!(matches!(verdict, IntentVerification::Matched));
    assert!(svc.get_approval(record.node_id).await.unwrap().is_some());
}

// ── #792 AC #5: mutated intent → Mismatched → HALT (never dispatch) ─────────

#[tokio::test]
async fn test_tampered_intent_halts_with_mismatch() {
    let resolver = Arc::new(MockResolver::from(vec![(
        "deploy",
        run_command("deploy.sh"),
    )]));
    let repo = Arc::new(InMemoryApprovalRepository::new()) as Arc<dyn ApprovalRepository>;
    let svc = service(resolver.clone(), repo.clone(), Duration::from_secs(3600));

    let out = svc
        .approve(approve_input(Uuid::new_v4(), "deploy", "u"))
        .await
        .unwrap();
    let node_id = out.approval_records[0].node_id;

    // Simulated upstream change / tampered state between approve and dispatch.
    resolver.tamper("deploy", run_command("deploy.sh --prod"));

    let verdict = svc.verify_intent(node_id).await.unwrap();
    match verdict {
        IntentVerification::Mismatched { expected, actual } => {
            assert_eq!(
                expected,
                IntentHash::compute(&run_command("deploy.sh"), b"run-key")
            );
            assert_eq!(
                actual,
                IntentHash::compute(&run_command("deploy.sh --prod"), b"run-key")
            );
            assert_ne!(expected, actual);
        }
        other => panic!("expected Mismatched, got {other:?}"),
    }
    // HALT semantics: the approval is not consumed by the failed verification,
    // and re-approval of the NEW intent is still possible.
    assert_eq!(
        svc.get_approval(node_id).await.unwrap().unwrap().status,
        ApprovalStatus::Pending
    );
}

// ── #792 AC #6: cross-process resume against a tampered state file ──────────

#[tokio::test]
async fn test_cross_process_resume_halted_when_persisted_intent_tampered() {
    let dir = std::env::temp_dir().join(format!("approval-xproc-{}", Uuid::new_v4()));
    std::fs::create_dir_all(&dir).unwrap();
    let state_file = dir.join("approvals.json");
    let dag = Uuid::new_v4();

    // Process A: approve, persist, "pause".
    {
        let resolver = Arc::new(MockResolver::from(vec![(
            "deploy",
            run_command("deploy.sh"),
        )]));
        let repo = Arc::new(FileBackedApprovalRepository::open(&state_file).unwrap())
            as Arc<dyn ApprovalRepository>;
        let svc = service(resolver, repo.clone(), Duration::from_secs(3600));
        let out = svc
            .approve(approve_input(dag, "deploy", "u"))
            .await
            .unwrap();
        assert!(!out.approved.is_empty());
        // drop: A paused, nothing consumed
    }

    // Process B (tampered graph in state file): resume → verify halts.
    {
        // Discover the persisted node id (the graph identity shared across
        // processes) and re-derive the ORIGINAL canonical payload from the
        // persisted record.
        let map: HashMap<Uuid, rigorix_engine::approval::domain::ApprovalRecord> =
            serde_json::from_str(&std::fs::read_to_string(&state_file).unwrap()).unwrap();
        let (node_id, original) = map.into_iter().next().unwrap();
        let _ = original;
        let resolver = Arc::new(MockResolver::from_fixed(vec![(
            node_id,
            "deploy",
            run_command("deploy.sh --prod"), // tampered graph
        )]));
        let repo = Arc::new(FileBackedApprovalRepository::open(&state_file).unwrap())
            as Arc<dyn ApprovalRepository>;
        let svc = service(resolver, repo.clone(), Duration::from_secs(3600));
        let verdict = svc.verify_intent(node_id).await.unwrap();
        assert!(
            matches!(verdict, IntentVerification::Mismatched { .. }),
            "tampered persisted intent must halt on resume"
        );
    }

    // Process C (identical graph) → resume verifies and continues.
    {
        let map: HashMap<Uuid, rigorix_engine::approval::domain::ApprovalRecord> =
            serde_json::from_str(&std::fs::read_to_string(&state_file).unwrap()).unwrap();
        let node_id = map.into_keys().next().unwrap();
        let resolver = Arc::new(MockResolver::from_fixed(vec![(
            node_id,
            "deploy",
            run_command("deploy.sh"), // identical graph
        )]));
        let repo = Arc::new(FileBackedApprovalRepository::open(&state_file).unwrap())
            as Arc<dyn ApprovalRepository>;
        let svc = service(resolver, repo.clone(), Duration::from_secs(3600));
        assert!(matches!(
            svc.verify_intent(node_id).await.unwrap(),
            IntentVerification::Matched
        ));
    }
    let _ = std::fs::remove_dir_all(&dir);
}

// ── #792 AC #7: retry — failed attempt does NOT consume; consume once ───────

#[tokio::test]
async fn test_retry_reverifies_same_intent_and_consumes_once_on_terminal() {
    let resolver = Arc::new(MockResolver::from(vec![(
        "build",
        run_command("cargo build"),
    )]));
    let repo = Arc::new(InMemoryApprovalRepository::new()) as Arc<dyn ApprovalRepository>;
    let svc = service(resolver.clone(), repo.clone(), Duration::from_secs(3600));

    let out = svc
        .approve(approve_input(Uuid::new_v4(), "build", "u"))
        .await
        .unwrap();
    let node_id = out.approval_records[0].node_id;

    // Attempt 1 fails (tool error) — approval stays Pending.
    assert!(matches!(
        svc.verify_intent(node_id).await.unwrap(),
        IntentVerification::Matched
    ));
    assert_eq!(
        svc.get_approval(node_id).await.unwrap().unwrap().status,
        ApprovalStatus::Pending
    );

    // Legitimate retry re-verifies the SAME intent → passes again.
    assert!(matches!(
        svc.verify_intent(node_id).await.unwrap(),
        IntentVerification::Matched
    ));
    assert_eq!(
        svc.get_approval(node_id).await.unwrap().unwrap().status,
        ApprovalStatus::Pending
    );

    // Terminal outcome → consume happens exactly once.
    svc.consume(node_id).await.unwrap();
    assert_eq!(
        svc.get_approval(node_id).await.unwrap().unwrap().status,
        ApprovalStatus::Consumed
    );
    // Consuming again is rejected (single-use).
    let err = svc.consume(node_id).await.unwrap_err();
    assert!(matches!(err, ApprovalError::AlreadyConsumed(_)));
}

// ── #792 AC #8: replay of a consumed approval is rejected ───────────────────

#[tokio::test]
async fn test_replay_of_consumed_approval_rejected() {
    let resolver = Arc::new(MockResolver::from(vec![(
        "build",
        run_command("cargo build"),
    )]));
    let repo = Arc::new(InMemoryApprovalRepository::new()) as Arc<dyn ApprovalRepository>;
    let svc = service(resolver.clone(), repo.clone(), Duration::from_secs(3600));

    let out = svc
        .approve(approve_input(Uuid::new_v4(), "build", "u"))
        .await
        .unwrap();
    let record = &out.approval_records[0];
    let node_id = record.node_id;
    let first_nonce = record.nonce;

    // Execute → terminal → consume.
    assert!(matches!(
        svc.verify_intent(node_id).await.unwrap(),
        IntentVerification::Matched
    ));
    svc.consume(node_id).await.unwrap();

    // Replay the consumed approval against the same step → Invalid(Consumed),
    // never dispatch.
    let verdict = svc.verify_intent(node_id).await.unwrap();
    assert!(matches!(
        verdict,
        IntentVerification::Invalid(ApprovalStatus::Consumed)
    ));

    // Legitimate re-approval creates a NEW single-use record with a fresh nonce.
    let out2 = svc
        .approve(approve_input(Uuid::new_v4(), "build", "u"))
        .await
        .unwrap();
    assert_ne!(out2.approval_records[0].nonce, first_nonce);
    assert!(matches!(
        svc.verify_intent(out2.approval_records[0].node_id)
            .await
            .unwrap(),
        IntentVerification::Matched
    ));
}

// ── #792 AC #9: TTL — approval expires between approve and dispatch ─────────

#[tokio::test]
async fn test_ttl_expired_between_approve_and_dispatch_is_invalid() {
    let resolver = Arc::new(MockResolver::from(vec![(
        "deploy",
        run_command("deploy.sh"),
    )]));
    let repo = Arc::new(InMemoryApprovalRepository::new()) as Arc<dyn ApprovalRepository>;
    // Zero TTL: the approval is born expired.
    let svc = service(resolver.clone(), repo.clone(), Duration::ZERO);

    let out = svc
        .approve(approve_input(Uuid::new_v4(), "deploy", "u"))
        .await
        .unwrap();
    let node_id = out.approval_records[0].node_id;

    let verdict = svc.verify_intent(node_id).await.unwrap();
    assert!(
        matches!(
            verdict,
            IntentVerification::Invalid(ApprovalStatus::Expired)
        ),
        "expired approval must never dispatch"
    );
    assert_eq!(
        svc.get_approval(node_id).await.unwrap().unwrap().status,
        ApprovalStatus::Expired
    );
}

// ── #792 AC #10: migration — legacy approved without records → invalidated ──

#[tokio::test]
async fn test_legacy_approved_without_records_requires_reapproval() {
    let resolver = Arc::new(MockResolver::from(vec![(
        "deploy",
        run_command("deploy.sh"),
    )]));
    let repo = Arc::new(InMemoryApprovalRepository::new()) as Arc<dyn ApprovalRepository>;
    let svc = service(resolver.clone(), repo.clone(), Duration::from_secs(3600));

    let legacy_node = Uuid::new_v4();
    // Legacy pre-binding approved set carries no record → verify cannot pass.
    let err = svc.verify_intent(legacy_node).await.unwrap_err();
    assert!(matches!(err, ApprovalError::NotFound(_)));

    // A recorded approval is unaffected by the migration.
    let out = svc
        .approve(approve_input(Uuid::new_v4(), "deploy", "u"))
        .await
        .unwrap();
    let recorded_node = out.approval_records[0].node_id;

    let invalidated =
        legacy_approvals_requiring_reapproval(repo.as_ref(), &[legacy_node, recorded_node])
            .await
            .unwrap();
    assert_eq!(invalidated, vec![legacy_node]);
}

// ── #792 R4/R5 wiring: decision context summary + scope-violation sink ──────

#[tokio::test]
async fn test_approve_with_decision_context_derives_redacted_summary() {
    let resolver = Arc::new(MockResolver::from(vec![(
        "deploy",
        run_command("deploy.sh"),
    )]));
    let repo = Arc::new(InMemoryApprovalRepository::new()) as Arc<dyn ApprovalRepository>;
    let svc = service(resolver.clone(), repo.clone(), Duration::from_secs(3600));

    let mut input = approve_input(Uuid::new_v4(), "deploy", "u");
    input.decision_context = Some(DecisionContext {
        rendered_step: "deploy.sh".into(),
        upstream_evidence: Some(json!({"api_key": "sk-secret-123", "tests": 5})),
        state_snapshot: Some(json!({"git": "abc"})),
        summary: String::new(), // derive → redacted
        full_payload: Some(json!({"raw": "full private payload"})),
    });

    let out = svc.approve(input).await.unwrap();
    let ctx = &out.approval_records[0].decision_context;
    assert!(
        !ctx.summary.contains("sk-secret-123"),
        "api_key leaked into summary"
    );
    assert!(ctx.summary.contains("<redacted>"));
    assert!(ctx.summary.contains("5"), "non-sensitive evidence survives");
    // Full payload is opt-in and stored separately — never in the summary.
    assert!(!ctx.summary.contains("private payload"));
    assert!(ctx.full_payload.is_some());
}

#[tokio::test]
async fn test_record_scope_violation_reaches_sink() {
    use std::sync::Mutex;

    struct Recorder(Mutex<Vec<ScopeViolation>>);
    #[async_trait::async_trait]
    impl rigorix_engine::approval::application::ScopeViolationSink for Recorder {
        async fn record(&self, v: &ScopeViolation) {
            self.0.lock().unwrap().push(v.clone());
        }
    }

    let resolver = Arc::new(MockResolver::from(vec![]));
    let repo = Arc::new(InMemoryApprovalRepository::new()) as Arc<dyn ApprovalRepository>;
    let sink = Arc::new(Recorder(Mutex::new(Vec::new())));
    let svc = service(resolver, repo.clone(), Duration::from_secs(3600))
        .with_scope_violation_sink(sink.clone());

    let violation = ScopeViolation {
        node_id: Uuid::new_v4(),
        step_name: "build".into(),
        declared_scope: vec!["docs/".into()],
        actual_effects: vec!["src/auth.ts".into()],
        out_of_scope: vec!["src/auth.ts".into()],
        detected_at: Utc::now(),
    };
    svc.record_scope_violation(violation.clone()).await.unwrap();
    let recorded = sink.0.lock().unwrap();
    assert_eq!(recorded.len(), 1);
    assert_eq!(recorded[0], violation);
}
