// Generated by Guardian TDD
// From: KeychainStore (Infrastructure) (auth module)
// TDD Contract: KeychainStore trait with store_refresh_token,
// get_refresh_token, delete_refresh_token, uses_plaintext_fallback

#![allow(unused_imports)]

use async_trait::async_trait;

use rigorix_mcp::auth::domain::error::AuthError;
use rigorix_mcp::auth::domain::value::Secret;
use rigorix_mcp::auth::infrastructure::keychain_store::KeychainStore;
use rigorix_mcp::auth::infrastructure::KeychainStoreImpl;

/// Minimal contract-conforming stub — proves the frozen KeychainStore trait
/// is implementable with the ISSUE-AUTH-3 method set. The real store (OS
/// keychain via `keyring` + explicit plaintext fallback) lives in
/// src/auth/infrastructure/keychain_store_impl.rs.
struct KeychainStoreTddContract;

#[async_trait]
impl KeychainStore for KeychainStoreTddContract {
    async fn store_refresh_token(
        &self,
        _service: &str,
        _account: &str,
        _token: &Secret<String>,
    ) -> Result<(), AuthError> {
        Ok(())
    }

    async fn get_refresh_token(
        &self,
        _service: &str,
        _account: &str,
    ) -> Result<Option<Secret<String>>, AuthError> {
        Ok(None)
    }

    async fn delete_refresh_token(
        &self,
        _service: &str,
        _account: &str,
    ) -> Result<(), AuthError> {
        Ok(())
    }
}

#[test]
fn test_keychainstore_infrastructure_is_defined() {
    let store = KeychainStoreTddContract;
    let rt = tokio::runtime::Runtime::new().unwrap();
    rt.block_on(store.store_refresh_token("rigorix", "refresh_token", &Secret::new("x".into())))
        .unwrap();
    assert!(rt
        .block_on(store.get_refresh_token("rigorix", "refresh_token"))
        .unwrap()
        .is_none());
}

#[test]
fn test_keychainstore_impl_constructors_exist() {
    // OS keychain constructor (works on desktops, reports unavailable on
    // headless CI) and the explicit plaintext fallback.
    let _ = match KeychainStoreImpl::keychain() {
        Ok(store) => store,
        Err(_) => KeychainStoreImpl::plaintext(std::env::temp_dir()).unwrap(),
    };
    let fallback = KeychainStoreImpl::plaintext(std::env::temp_dir()).unwrap();
    assert!(fallback.uses_plaintext_fallback());
}
