// Generated by Guardian TDD
// From: GetTemplateHandler (Domain Service) (template-tools module)
// Tests the frozen contract for GetTemplateHandler trait.

#[cfg(test)]
mod tests {
    use rigorix_mcp::template_tools::application::service::GetTemplateHandler;
    use rigorix_mcp::template_tools::domain::error::{HandlerError, ToolCallResult};
    use rigorix_mcp::template_tools::domain::value::GetTemplateInput;

    /// Mock handler for testing the GetTemplateHandler contract.
    struct MockGetTemplateHandler;

    #[async_trait::async_trait]
    impl GetTemplateHandler for MockGetTemplateHandler {
        async fn handle(&self, input: &GetTemplateInput) -> Result<ToolCallResult, HandlerError> {
            let result = serde_json::json!({
                "name": input.name,
                "format": input.format,
                "description": "Mock template",
                "version": "1.0.0"
            });
            Ok(ToolCallResult::success(result))
        }
    }

    #[tokio::test]
    async fn test_get_template_handler_is_defined() {
        let handler = MockGetTemplateHandler;
        let input = GetTemplateInput {
            name: "test-template".into(),
            format: None,
        };
        let result = handler.handle(&input).await;
        assert!(result.is_ok(), "Handler should succeed");
    }

    #[tokio::test]
    async fn test_get_template_handler_with_format() {
        let handler = MockGetTemplateHandler;
        let input = GetTemplateInput {
            name: "test-template".into(),
            format: Some("toml".into()),
        };
        let result = handler.handle(&input).await.expect("Handler should succeed");
        assert!(!result.is_error, "Result should not be an error");

        let content: serde_json::Value =
            serde_json::from_str(&result.content[0].text).expect("Should be valid JSON");
        assert_eq!(content["name"], "test-template");
        assert_eq!(content["format"], "toml");
    }

    #[tokio::test]
    async fn test_get_template_handler_returns_tool_call_result() {
        let handler = MockGetTemplateHandler;
        let input = GetTemplateInput {
            name: "test".into(),
            format: None,
        };
        let result = handler.handle(&input).await;
        assert!(result.is_ok(), "Should return Ok(ToolCallResult)");
        let tool_result = result.unwrap();
        assert!(!tool_result.content.is_empty(), "Should have content");
    }

    #[tokio::test]
    async fn test_get_template_handler_is_send_sync() {
        let handler = MockGetTemplateHandler;
        let boxed: Box<dyn GetTemplateHandler> = Box::new(handler);
        let _ = boxed;
    }
}
