// Generated by Guardian TDD
// From: AuditSummaryHandler (Domain Service) (audit-tools module)
// Tests the AuditSummaryHandlerImpl.

#[cfg(test)]
mod tests {
    use std::sync::Arc;
    use uuid::Uuid;

    use rigorix_mcp::audit_tools::application::dto::AuditSummaryInput;
    use rigorix_mcp::audit_tools::application::service::AuditSummaryHandler;
    use rigorix_mcp::audit_tools::application::service_impl::AuditSummaryHandlerImpl;
    use rigorix_mcp::audit_tools::domain::formatter_impl::AuditFormatterImpl;
    use rigorix_mcp::audit_tools::infrastructure::InMemoryAuditQueryService;
    use rigorix_mcp::execution_tools::domain::value::ExecutionStatus;

    #[tokio::test]
    async fn test_auditsummaryhandler_with_data() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let now = chrono::Utc::now();

        // Add 5 executions
        for i in 0..5 {
            let status = if i < 3 {
                ExecutionStatus::Completed
            } else {
                ExecutionStatus::Failed
            };
            query_service
                .store(InMemoryAuditQueryService::create_sample(
                    Uuid::new_v4(),
                    status,
                    Some("test-template".into()),
                    now - chrono::Duration::hours(i as i64 * 10),
                    1000,
                ))
                .unwrap();
        }

        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = AuditSummaryHandlerImpl::new(query_service, formatter);

        let since = (now - chrono::Duration::days(7))
            .format("%Y-%m-%dT%H:%M:%SZ")
            .to_string();
        let until = (now + chrono::Duration::hours(1))
            .format("%Y-%m-%dT%H:%M:%SZ")
            .to_string();

        let input = AuditSummaryInput {
            since: Some(since),
            until: Some(until),
        };

        let result = handler.handle(input).await;
        assert!(result.is_ok());
        let tc = result.unwrap();
        assert!(!tc.is_error);
        assert!(tc.content[0].text.contains("5"));
        assert!(tc.content[0].text.contains("3"));
        assert!(tc.content[0].text.contains("2"));
    }

    #[tokio::test]
    async fn test_auditsummaryhandler_no_data() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = AuditSummaryHandlerImpl::new(query_service, formatter);

        let now = chrono::Utc::now();
        let since = (now - chrono::Duration::days(7))
            .format("%Y-%m-%dT%H:%M:%SZ")
            .to_string();
        let until = (now + chrono::Duration::hours(1))
            .format("%Y-%m-%dT%H:%M:%SZ")
            .to_string();

        let input = AuditSummaryInput {
            since: Some(since),
            until: Some(until),
        };

        let result = handler.handle(input).await;
        assert!(result.is_ok());
        let tc = result.unwrap();
        assert!(!tc.is_error);
        assert!(tc.content[0].text.contains("0"));
    }

    #[tokio::test]
    async fn test_auditsummaryhandler_default_range() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = AuditSummaryHandlerImpl::new(query_service, formatter);

        let input = AuditSummaryInput {
            since: None,
            until: None,
        };

        let result = handler.handle(input).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_auditsummaryhandler_invalid_since() {
        let query_service = Arc::new(InMemoryAuditQueryService::new());
        let formatter = Arc::new(AuditFormatterImpl::new());
        let handler = AuditSummaryHandlerImpl::new(query_service, formatter);

        let input = AuditSummaryInput {
            since: Some("invalid-date".into()),
            until: None,
        };

        let result = handler.handle(input).await;
        assert!(result.is_err());
    }
}
