// Generated by Guardian TDD
// From: tokenverifier
// Corrected (GAP-A-24): the tested type is now implemented — the
// is_defined / interacts_with_none assertions exercise the real type.

#[cfg(test)]
mod tests {
    use rigorix_engine::identity::application::service::VerificationOutcome;
    use rigorix_engine::identity::domain::claim::IdentityClaim;
    use rigorix_engine::identity::domain::{IdentityError, IdentitySource};
    use rigorix_engine::identity::infrastructure::verifier::TokenVerifier;

    struct MockVerifier;
    #[async_trait::async_trait]
    impl TokenVerifier for MockVerifier {
        async fn verify(
            &self,
            _token: &str,
            _claim: &IdentityClaim,
        ) -> Result<VerificationOutcome, IdentityError> {
            Ok(VerificationOutcome::Unverified {
                reason: "mock".to_string(),
            })
        }
    }

    #[tokio::test]
    async fn test_tokenverifier_is_defined() {
        let claim = IdentityClaim {
            subject: "s".to_string(),
            issuer: "i".to_string(),
            authority: None,
            source: IdentitySource::Unverified,
            auth_method: None,
            issued_at: chrono::Utc::now(),
            expires_at: None,
            token_ref: None,
        };
        let verifier: Box<dyn TokenVerifier> = Box::new(MockVerifier);
        assert!(verifier.verify("token", &claim).await.is_ok());
    }

    #[tokio::test]
    async fn test_tokenverifier_interacts_with_none() {
        let verifier: Box<dyn TokenVerifier> = Box::new(MockVerifier);
        let _: &dyn TokenVerifier = verifier.as_ref();
    }
}
