// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: IntentHash (approval module)
// ISSUE-INTENTHASH (#788): HMAC-SHA256 compute/verify over canonical intent
// bytes. Same tool+intent+scope → same hash; any byte change → different hash.

use rigorix_engine::approval::domain::{ExecutionIntent, IntentHash};
use serde_json::json;

fn intent(tool: &str, command: &str, scope: &[&str]) -> ExecutionIntent {
    ExecutionIntent {
        tool: tool.to_string(),
        intent: json!({"command": command}),
        declared_scope: scope.iter().map(|s| s.to_string()).collect(),
    }
}

const RUN_KEY: &[u8] = b"run-key-0000";

#[test]
fn test_intenthash_is_defined() {
    let hash = IntentHash("deadbeef".to_string());
    assert_eq!(hash.0, "deadbeef");
}

#[test]
fn test_intenthash_serde_round_trip() {
    let hash = IntentHash("abc123".to_string());
    let encoded = serde_json::to_string(&hash).expect("serialize");
    let decoded: IntentHash = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, hash);
    // Deterministic equality contract: identical digests compare equal.
    assert_eq!(IntentHash("x".into()), IntentHash("x".into()));
    assert_ne!(IntentHash("x".into()), IntentHash("y".into()));
}

// ── #788 behavior: compute / verify ─────────────────────────────────────────

#[test]
fn test_same_tool_intent_scope_produces_same_hash() {
    let a = intent("run_command", "cargo test", &["src/", "Cargo.toml"]);
    let b = intent("run_command", "cargo test", &["src/", "Cargo.toml"]);
    assert_eq!(
        IntentHash::compute(&a, RUN_KEY),
        IntentHash::compute(&b, RUN_KEY)
    );
    // Deterministic: recomputing the same intent yields the same digest.
    assert_eq!(
        IntentHash::compute(&a, RUN_KEY),
        IntentHash::compute(&a, RUN_KEY)
    );
    // Digest is the canonical 64-char lowercase hex (HMAC-SHA256).
    let digest = IntentHash::compute(&a, RUN_KEY);
    assert_eq!(digest.0.len(), 64);
    assert!(digest.0.chars().all(|c| c.is_ascii_hexdigit()));
}

#[test]
fn test_any_byte_change_produces_different_hash() {
    let base = intent("run_command", "deploy.sh", &["src/"]);
    let base_hash = IntentHash::compute(&base, RUN_KEY);

    let mut tool_changed = base.clone();
    tool_changed.tool = "file_write".into();
    assert_ne!(base_hash, IntentHash::compute(&tool_changed, RUN_KEY));

    let mut intent_changed = base.clone();
    intent_changed.intent = json!({"command": "deploy.sh --prod"});
    assert_ne!(base_hash, IntentHash::compute(&intent_changed, RUN_KEY));

    let mut scope_changed = base.clone();
    scope_changed.declared_scope = vec!["other/".into()];
    assert_ne!(base_hash, IntentHash::compute(&scope_changed, RUN_KEY));

    // Extra declared-scope entry is a byte change too.
    let mut extra_scope = base.clone();
    extra_scope.declared_scope.push("docs/".into());
    assert_ne!(base_hash, IntentHash::compute(&extra_scope, RUN_KEY));
}

#[test]
fn test_verify_matches_only_the_exact_approved_intent() {
    let approved = intent("edit_file", "fix auth", &["src/auth.rs"]);
    let hash = IntentHash::compute(&approved, RUN_KEY);

    // Identical intent + key → verified.
    let replay = intent("edit_file", "fix auth", &["src/auth.rs"]);
    assert!(hash.verify(&replay, RUN_KEY));

    // Tampered intent (simulated upstream mutation) → rejected.
    let tampered = intent("edit_file", "fix auth -- --all", &["src/auth.rs"]);
    assert!(!hash.verify(&tampered, RUN_KEY));

    // Wrong run key → rejected.
    assert!(!hash.verify(&replay, b"another-run-key"));
}

#[test]
fn test_verify_rejects_malformed_digest() {
    let approved = intent("run_command", "x", &[]);
    let bad = IntentHash("not-hex!!".into());
    assert!(!bad.verify(&approved, RUN_KEY));
}
