// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: IntentHash (approval module)
// Contract freeze: the digest newtype is defined; HMAC-SHA256 computation
// lands in ISSUE-INTENTHASH (#788).

use rigorix_engine::approval::domain::IntentHash;

#[test]
fn test_intenthash_is_defined() {
    let hash = IntentHash("deadbeef".to_string());
    assert_eq!(hash.0, "deadbeef");
}

#[test]
fn test_intenthash_serde_round_trip() {
    let hash = IntentHash("abc123".to_string());
    let encoded = serde_json::to_string(&hash).expect("serialize");
    let decoded: IntentHash = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, hash);
    // Deterministic equality contract: identical digests compare equal.
    assert_eq!(IntentHash("x".into()), IntentHash("x".into()));
    assert_ne!(IntentHash("x".into()), IntentHash("y".into()));
}
