// Generated by Guardian TDD
// From: TemplateConverter (Domain Service) (template-tools module)
// Tests the frozen contract for TemplateConverter trait.

#[cfg(test)]
mod tests {
    use rigorix_mcp::template_tools::domain::entity::TemplateConverter;
    use rigorix_mcp::template_tools::domain::error::TemplateError;
    use rigorix_mcp::template_tools::domain::value::{PlanTemplate, StepDefinition};
    use std::sync::Arc;

    /// Helper: create a minimal valid PlanTemplate for testing.
    fn make_test_template(name: &str) -> PlanTemplate {
        let step = StepDefinition::new(
            "step-1".into(),
            "test_tool".into(),
            serde_json::json!({}),
            false,
            "Test step".into(),
            None,
        );
        let now = chrono::Utc::now();
        PlanTemplate::new(
            name.into(),
            "Test description".into(),
            "1.0.0".into(),
            vec![],
            vec![step],
            None,
            std::collections::HashMap::new(),
            now,
            now,
        )
        .expect("Failed to create test template")
    }

    /// Mock converter for testing the TemplateConverter contract.
    struct MockTemplateConverter;

    #[async_trait::async_trait]
    impl TemplateConverter for MockTemplateConverter {
        async fn to_toml(&self, template: &PlanTemplate) -> Result<String, TemplateError> {
            Ok(format!(
                r#"name = "{}"
description = "{}"
version = "{}"
"#,
                template.name(),
                template.description(),
                template.version()
            ))
        }

        async fn to_json(&self, template: &PlanTemplate) -> Result<serde_json::Value, TemplateError> {
            Ok(serde_json::json!({
                "name": template.name(),
                "description": template.description(),
                "version": template.version(),
                "tags": template.tags(),
                "step_count": template.steps().len(),
            }))
        }

        async fn from_toml(&self, toml_str: &str) -> Result<PlanTemplate, TemplateError> {
            let name = toml_str
                .lines()
                .find(|l| l.starts_with("name = "))
                .and_then(|l| l.split('"').nth(1))
                .unwrap_or("unknown")
                .to_string();

            // Produce a valid template from the TOML metadata
            let step = StepDefinition::new(
                "step-1".into(),
                "test_tool".into(),
                serde_json::json!({}),
                false,
                "Parsed step".into(),
                None,
            );
            let now = chrono::Utc::now();
            PlanTemplate::new(
                name,
                "Parsed from TOML".into(),
                "0.1.0".into(),
                vec![],
                vec![step],
                None,
                std::collections::HashMap::new(),
                now,
                now,
            )
        }

        async fn from_json(
            &self,
            json: serde_json::Value,
        ) -> Result<PlanTemplate, TemplateError> {
            PlanTemplate::from_json(json)
        }

        async fn validate_toml(&self, _toml_str: &str) -> Result<(), TemplateError> {
            Ok(())
        }

        async fn validate_and_convert(
            &self,
            json: serde_json::Value,
        ) -> Result<PlanTemplate, TemplateError> {
            PlanTemplate::from_json(json)
        }
    }

    #[tokio::test]
    async fn test_template_converter_is_defined() {
        let converter = MockTemplateConverter;
        let template = make_test_template("test");
        let result = converter.to_json(&template).await;
        assert!(result.is_ok(), "Converter should produce JSON");
    }

    #[tokio::test]
    async fn test_template_converter_to_json() {
        let converter = MockTemplateConverter;
        let template = make_test_template("my-template");
        let json = converter
            .to_json(&template)
            .await
            .expect("Should convert to JSON");
        assert_eq!(json["name"], "my-template");
        assert!(json["step_count"].as_u64().unwrap_or(0) > 0);
    }

    #[tokio::test]
    async fn test_template_converter_to_toml() {
        let converter = MockTemplateConverter;
        let template = make_test_template("toml-test");
        let toml = converter
            .to_toml(&template)
            .await
            .expect("Should convert to TOML");
        assert!(toml.contains("toml-test"), "TOML should contain the template name");
    }

    #[tokio::test]
    async fn test_template_converter_from_json_valid() {
        let converter = MockTemplateConverter;
        let json = serde_json::json!({
            "name": "from-json",
            "description": "Created from JSON",
            "version": "1.0.0",
            "tags": ["test"],
            "steps": [{
                "name": "step-1",
                "tool": "test_tool",
                "parameters": {},
                "requires_approval": false,
                "description": "Test step"
            }],
            "constraints": null,
            "metadata": {},
            "created_at": "2026-01-01T00:00:00Z",
            "updated_at": "2026-01-01T00:00:00Z"
        });
        let template = converter
            .from_json(json)
            .await
            .expect("Should deserialize valid JSON");
        assert_eq!(template.name(), "from-json");
        assert_eq!(template.steps().len(), 1);
    }

    #[tokio::test]
    async fn test_template_converter_from_json_invalid_empty_steps() {
        let converter = MockTemplateConverter;
        let json = serde_json::json!({
            "name": "invalid",
            "description": "No steps",
            "version": "1.0.0",
            "tags": [],
            "steps": [],
            "metadata": {},
            "created_at": "2026-01-01T00:00:00Z",
            "updated_at": "2026-01-01T00:00:00Z"
        });
        let err = converter.from_json(json).await.unwrap_err();
        assert!(
            matches!(err, TemplateError::ValidationError(_)),
            "Expected ValidationError for empty steps, got: {:?}",
            err
        );
    }

    #[tokio::test]
    async fn test_template_converter_validate_toml() {
        let converter = MockTemplateConverter;
        let valid_toml = r#"
name = "test"
description = "test"
version = "1.0.0"
"#;
        let result = converter.validate_toml(valid_toml).await;
        assert!(result.is_ok(), "Valid TOML should pass validation");
    }

    #[tokio::test]
    async fn test_template_converter_is_send_sync() {
        let converter = MockTemplateConverter;
        // Verify TemplateConverter trait is Send + Sync by wrapping in Arc
        let shared: Arc<dyn TemplateConverter> = Arc::new(converter);
        let _ = shared;
    }
}
