// Generated by Guardian TDD
// From: identityerror
// Corrected (GAP-A-24): the tested type is now implemented — the
// is_defined / interacts_with_none assertions exercise the real type.

#[cfg(test)]
mod tests {
    use rigorix_engine::identity::domain::IdentityError;

    #[test]
    fn test_identityerror_is_defined() {
        let err = IdentityError::InvalidToken("bad".to_string());
        assert!(err.to_string().to_lowercase().contains("token"));
    }

    #[test]
    fn test_identityerror_interacts_with_none() {
        assert!(matches!(IdentityError::Expired, IdentityError::Expired));
        assert!(matches!(
            IdentityError::Internal("x".into()),
            IdentityError::Internal(_)
        ));
    }
}
