// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: ApproveInput / ApproveOutput (approval module)
// Contract freeze: boundary DTO schemas are defined and serde round-trip;
// service wiring lands in ISSUE-APPROVEINPUT-APPROVEOUTPUT (#793).

use chrono::{Duration, Utc};
use rigorix_engine::approval::application::{ApproveInput, ApproveOutput};
use rigorix_engine::approval::domain::{
    ApprovalRecord, ApprovalStatus, DecisionContext, IntentHash,
};
use serde_json::json;
use uuid::Uuid;

fn sample_input() -> ApproveInput {
    ApproveInput {
        dag_id: Uuid::new_v4(),
        step_names: vec!["deploy".to_string()],
        approver_id: "user@org".to_string(),
        authority: Some("role:operator".to_string()),
        decision_context: Some(DecisionContext {
            rendered_step: "deploy.sh --env prod".to_string(),
            upstream_evidence: None,
            state_snapshot: None,
            summary: "deploy to prod".to_string(),
            full_payload: None,
        }),
        token_claims_ref: Some("tok-ref".to_string()),
    }
}

fn sample_output() -> ApproveOutput {
    let record = ApprovalRecord {
        step_name: "deploy".to_string(),
        node_id: Uuid::new_v4(),
        intent_hash: IntentHash("intent-digest".to_string()),
        intent_payload: json!({"tool": "run_command", "command": "deploy.sh"}),
        approver_id: "user@org".to_string(),
        authority: Some("role:operator".to_string()),
        decided_at: Utc::now(),
        expires_at: Utc::now() + Duration::minutes(30),
        nonce: Uuid::new_v4(),
        token_claims_ref: Some("tok-ref".to_string()),
        status: ApprovalStatus::Pending,
        decision_context: DecisionContext {
            rendered_step: "deploy.sh --env prod".to_string(),
            upstream_evidence: None,
            state_snapshot: None,
            summary: "deploy to prod".to_string(),
            full_payload: None,
        },
    };
    ApproveOutput {
        dag_id: Uuid::new_v4(),
        approved: vec!["deploy".to_string()],
        not_found: vec![],
        still_pending: vec![],
        approval_records: vec![record],
    }
}

#[test]
fn test_approveinput_is_defined() {
    let input = sample_input();
    assert_eq!(input.approver_id, "user@org");
    assert_eq!(input.step_names, vec!["deploy".to_string()]);
    assert!(input.decision_context.is_some());
}

#[test]
fn test_approveinput_serde_round_trip() {
    let input = sample_input();
    let encoded = serde_json::to_string(&input).expect("serialize");
    let decoded: ApproveInput = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, input);
}

#[test]
fn test_approveoutput_serde_round_trip() {
    let output = sample_output();
    let encoded = serde_json::to_string(&output).expect("serialize");
    let decoded: ApproveOutput = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, output);
}

// ── #793 behavior: boundary validation ───────────────────────────────────────

#[test]
fn test_approveinput_requires_approver_and_steps() {
    use rigorix_engine::approval::domain::ApprovalError;

    // Missing approver → rejected at the boundary.
    let mut no_approver = sample_input();
    no_approver.approver_id.clear();
    assert!(matches!(
        no_approver.validate(),
        Err(ApprovalError::InvalidState(_))
    ));

    // No steps → rejected.
    let mut no_steps = sample_input();
    no_steps.step_names.clear();
    assert!(matches!(
        no_steps.validate(),
        Err(ApprovalError::InvalidState(_))
    ));

    // Valid input passes.
    assert!(sample_input().validate().is_ok());
}

#[test]
fn test_approveinput_dedupes_and_preserves_order() {
    let mut input = sample_input();
    input.step_names = vec!["a".into(), "b".into(), "a".into(), "c".into()];
    let deduped = input.dedup_step_names();
    assert_eq!(
        deduped,
        vec!["a".to_string(), "b".to_string(), "c".to_string()]
    );
}

#[test]
fn test_approveoutput_aggregate_helpers() {
    let mut out = sample_output();
    assert!(out.is_fully_approved());
    assert_eq!(out.approval_count(), 1);

    out.approved.clear();
    out.still_pending.push("deploy".into());
    assert!(!out.is_fully_approved());
    assert_eq!(out.pending_count(), 1);
}
