// Generated by Guardian TDD — rewritten as a Rust contract test (was an
// inert `assert!(false)` scaffold).
// From: SequenceRule (sequence-policy module)
// Contract freeze: the aggregate fields + serde wire format are frozen here;
// TOML-parse + predicate matching behavior lands in ISSUE-SEQUENCE-POLICY-1.

use rigorix_engine::sequence_policy::domain::{
    ParamMatchKind, ParamPredicate, RuleAction, SequenceRule, StepPredicate,
};
use serde_json::{Value, json};

/// The conference rule from the canonical module spec — remove-then-reassign.
fn conference_rule() -> SequenceRule {
    SequenceRule {
        id: "registration-remove-then-reassign".to_string(),
        name: "No remove-then-reassign of a full event seat".to_string(),
        description: "Removing an attendee to free a seat, then registering the requester, is never autonomous"
            .to_string(),
        steps: vec![
            StepPredicate {
                tool: "registration_remove".to_string(),
                params: vec![ParamPredicate {
                    pointer: "/event_id".to_string(),
                    kind: ParamMatchKind::Exact,
                    value: "conf-2026".to_string(),
                }],
            },
            StepPredicate {
                tool: "registration_add".to_string(),
                params: vec![ParamPredicate {
                    pointer: "/event_id".to_string(),
                    kind: ParamMatchKind::Exact,
                    value: "conf-2026".to_string(),
                }],
            },
        ],
        window: Some(3),
        action: RuleAction::Promote,
        history: None,
    }
}

#[test]
fn test_sequencerule_is_defined() {
    let rule = conference_rule();
    assert_eq!(rule.id, "registration-remove-then-reassign");
    // Ordered predicates: a match requires steps[0] before steps[1].
    assert_eq!(rule.steps.len(), 2);
    assert_eq!(rule.steps[0].tool, "registration_remove");
    assert_eq!(rule.steps[1].tool, "registration_add");
    assert_eq!(rule.steps[1].params[0].pointer, "/event_id");
    assert_eq!(rule.window, Some(3));
    assert_eq!(rule.action, RuleAction::Promote);
}

#[test]
fn test_sequencerule_serde_round_trip_preserves_all_fields() {
    let rule = conference_rule();
    let encoded = serde_json::to_string(&rule).expect("serialize");
    let decoded: SequenceRule = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, rule);

    // Every frozen field survives verbatim.
    let value: Value = serde_json::from_str(&encoded).expect("value");
    assert_eq!(value["id"], "registration-remove-then-reassign");
    assert_eq!(value["steps"].as_array().map(Vec::len), Some(2));
    assert_eq!(value["steps"][0]["tool"], "registration_remove");
    assert_eq!(value["window"], json!(3));
    assert_eq!(value["action"], json!("promote"));
}

#[test]
fn test_rule_action_wire_format_is_lowercase_and_defaults_to_promote() {
    // Wire format: action = "promote" | "deny" (config schema).
    let promote: RuleAction = serde_json::from_value(json!("promote")).expect("promote");
    let deny: RuleAction = serde_json::from_value(json!("deny")).expect("deny");
    assert_eq!(promote, RuleAction::Promote);
    assert_eq!(deny, RuleAction::Deny);

    // Action omitted → promote (the safe default: human decision, not silence).
    let defaulted: SequenceRule = serde_json::from_value(json!({
        "id": "r",
        "name": "n",
        "description": "d",
        "steps": [
            { "tool": "registration_remove" },
            { "tool": "registration_add" }
        ],
        "window": 3
    }))
    .expect("action omitted");
    assert_eq!(defaulted.action, RuleAction::Promote);
}

#[test]
fn test_rule_steps_require_order_and_preserve_params() {
    let rule = conference_rule();
    // Order is part of the contract — matching consumes steps in rule order.
    assert_ne!(rule.steps[0].tool, rule.steps[1].tool);
    assert_eq!(rule.steps[0].params.len(), 1);
    assert_eq!(rule.steps[1].params[0].kind, ParamMatchKind::Exact);
}
