// Generated by Guardian TDD
// From: AuthHandler / SSE Auth (Interfaces) (auth module)
// TDD Contract: AuthToolHandler trait (handle_auth_login/status/logout) and
// SseAuthGate trait (authorize per mode)

#![allow(unused_imports)]

use async_trait::async_trait;
use serde_json::Value;

use rigorix_mcp::auth::domain::error::AuthError;
use rigorix_mcp::auth::domain::value::Secret;
use rigorix_mcp::auth::interfaces::mcp::{AuthToolHandler, AuthToolHandlerImpl};
use rigorix_mcp::auth::interfaces::sse_auth::{SseAuthDecision, SseAuthGate, SseAuthMode};
use rigorix_mcp::auth::interfaces::SseAuthGateImpl;

/// Minimal contract-conforming handler stub — proves the frozen
/// AuthToolHandler trait is implementable with the ISSUE-AUTH-5 method set.
struct AuthHandlerTddContract;

#[async_trait]
impl AuthToolHandler for AuthHandlerTddContract {
    async fn handle_auth_login(&self, _params: Value) -> Result<Value, AuthError> {
        Ok(serde_json::json!({
            "status": "pending",
            "verification_uri": "https://idp.example.com/device",
            "user_code": "ABCD-EFGH",
            "expires_in": 600,
        }))
    }

    async fn handle_auth_status(&self, _params: Value) -> Result<Value, AuthError> {
        Ok(serde_json::json!({
            "status": "unauthenticated",
            "claim_summary": null,
            "source": "unverified",
        }))
    }

    async fn handle_auth_logout(&self, _params: Value) -> Result<Value, AuthError> {
        Ok(serde_json::json!({ "status": "logged_out" }))
    }
}

#[test]
fn test_authhandler_sse_auth_interfaces_is_defined() {
    let handler = AuthHandlerTddContract;
    let rt = tokio::runtime::Runtime::new().unwrap();
    let login = rt
        .block_on(handler.handle_auth_login(serde_json::json!({})))
        .unwrap();
    assert_eq!(login["status"], "pending");
    assert_eq!(login["user_code"], "ABCD-EFGH");
}

#[test]
fn test_authhandler_status_and_logout_contracts() {
    let handler = AuthHandlerTddContract;
    let rt = tokio::runtime::Runtime::new().unwrap();
    let status = rt
        .block_on(handler.handle_auth_status(serde_json::json!({})))
        .unwrap();
    assert_eq!(status["status"], "unauthenticated");
    let logout = rt
        .block_on(handler.handle_auth_logout(serde_json::json!({})))
        .unwrap();
    assert_eq!(logout["status"], "logged_out");
}

#[test]
fn test_sse_auth_gate_constructors_exist() {
    // Disabled (none) and api_key modes are directly constructible.
    let disabled = SseAuthGateImpl::disabled();
    assert_eq!(disabled.mode(), SseAuthMode::None);
    let keyed = SseAuthGateImpl::api_key(Secret::new("k".into()));
    assert_eq!(keyed.mode(), SseAuthMode::ApiKey);
}
