// Generated by Guardian TDD — rewritten as Rust (was an inert bun/TS stub).
// From: ScopeViolation (approval module)
// Contract freeze: the R5 evidence record is defined and serde round-trip;
// git-diff oracle detection lands in ISSUE-SCOPEVIOLATION (#791).

use chrono::Utc;
use rigorix_engine::approval::domain::ScopeViolation;
use uuid::Uuid;

fn sample_violation() -> ScopeViolation {
    ScopeViolation {
        node_id: Uuid::new_v4(),
        step_name: "build".to_string(),
        declared_scope: vec!["src/".to_string(), "Cargo.toml".to_string()],
        actual_effects: vec![
            "src/lib.rs".to_string(),
            "src/auth.ts".to_string(), // side-effect via script — outside scope
        ],
        out_of_scope: vec!["src/auth.ts".to_string()],
        detected_at: Utc::now(),
    }
}

#[test]
fn test_scopeviolation_is_defined() {
    let v = sample_violation();
    assert_eq!(v.out_of_scope, vec!["src/auth.ts".to_string()]);
    assert_eq!(v.step_name, "build");
}

#[test]
fn test_scopeviolation_serde_round_trip() {
    let v = sample_violation();
    let encoded = serde_json::to_string(&v).expect("serialize");
    let decoded: ScopeViolation = serde_json::from_str(&encoded).expect("deserialize");
    assert_eq!(decoded, v);
}
