// Generated by Guardian TDD
// From: identityrepository
// Corrected (GAP-A-24): the tested type is now implemented — the
// is_defined / interacts_with_none assertions exercise the real type.

#[cfg(test)]
mod tests {
    use rigorix_engine::identity::domain::claim::IdentityClaim;
    use rigorix_engine::identity::domain::{IdentityError, IdentitySource};
    use rigorix_engine::identity::infrastructure::repository::IdentityRepository;
    use uuid::Uuid;

    struct MockRepo;
    #[async_trait::async_trait]
    impl IdentityRepository for MockRepo {
        async fn save(&self, _e: Uuid, _c: &IdentityClaim) -> Result<(), IdentityError> {
            Ok(())
        }
        async fn load(&self, _e: Uuid) -> Result<Option<IdentityClaim>, IdentityError> {
            Ok(None)
        }
        async fn delete(&self, _e: Uuid) -> Result<(), IdentityError> {
            Ok(())
        }
    }

    #[tokio::test]
    async fn test_identityrepository_is_defined() {
        let claim = IdentityClaim {
            subject: "s".to_string(),
            issuer: "i".to_string(),
            authority: None,
            source: IdentitySource::Unverified,
            auth_method: None,
            issued_at: chrono::Utc::now(),
            expires_at: None,
            token_ref: None,
        };
        let repo = MockRepo;
        let id = uuid::Uuid::new_v4();
        assert!(repo.save(id, &claim).await.is_ok());
    }

    #[tokio::test]
    async fn test_identityrepository_interacts_with_none() {
        let repo = MockRepo;
        assert!(repo.load(uuid::Uuid::new_v4()).await.unwrap().is_none());
    }
}
