// Generated by Guardian TDD — rewritten as a Rust contract test (was an inert
// `assert!(false)` scaffold).
// From: PreconditionService (consequence-gating module)
// Contract freeze: the service port, its injected construction, and the
// Dispatch|Deny verdict shape are frozen here; matching/require_params/run
// behavior lands in ISSUE-CONSEQUENCE-GATING-4.

use rigorix_engine::precondition::application::{
    DispatchStep, PreconditionService, PreconditionServiceImpl,
};
use rigorix_engine::precondition::domain::{PreconditionOutcome, PreconditionVerdict};
use rigorix_engine::precondition::infrastructure::ProcessPreconditionRunner;
use rigorix_engine::precondition::infrastructure::repository::TomlPreconditionRepository;
use serde_json::json;

fn service() -> PreconditionServiceImpl {
    PreconditionServiceImpl::new(
        Box::new(TomlPreconditionRepository::new(
            ".rigorix/preconditions.toml",
        )),
        Box::new(ProcessPreconditionRunner::new("/workspace")),
    )
}

#[test]
fn test_preconditionservice_is_defined() {
    // The service is injected with its repository + runner (never defaulted).
    let service: Box<dyn PreconditionService> = Box::new(service());
    let _ = &service;
}

#[test]
fn test_preconditionservice_depends_on_runner_and_repository() {
    // Construction requires both ports — the contract cannot be built without
    // the config source and the deterministic runner.
    let step = DispatchStep {
        name: "pay".to_string(),
        tool: "payment_execute".to_string(),
        parameters: json!({ "beneficiary": "acct-1" }),
    };
    assert_eq!(step.tool, "payment_execute");
    let _service = service();
}

#[test]
fn test_verdict_dispatch_and_deny_are_the_only_outcomes() {
    assert!(PreconditionVerdict::Dispatch.allows_dispatch());
    let deny = PreconditionVerdict::Deny {
        precondition_id: "beneficiary-eligible".to_string(),
        outcome: PreconditionOutcome::Failed,
    };
    assert!(!deny.allows_dispatch());
    assert_eq!(deny.denying_precondition_id(), Some("beneficiary-eligible"));
}
