// Generated by Guardian TDD — rewritten as behavioral/integration tests (was an
// inert `assert!(false)` scaffold).
// From: PreconditionSurfaces (consequence-gating module)
// AC #16: `rigorix_validate_plan` surfaces findings; a refusal maps to a
// structured `policy_violation`.

use chrono::Utc;
use rigorix_engine::precondition::application::{
    PreconditionPolicyViolation, PreconditionSurfaces, PreconditionSurfacesImpl,
};
use rigorix_engine::precondition::domain::{
    PreconditionFinding, PreconditionOutcome, PreconditionVerdict,
};

#[test]
fn test_preconditionsurfaces_is_defined() {
    let surfaces = PreconditionSurfacesImpl;
    assert_eq!(surfaces.capability(), "precondition_gating");
}

#[test]
fn test_dispatch_verdict_has_no_policy_violation() {
    let surfaces = PreconditionSurfacesImpl;
    assert!(
        surfaces
            .refusal_payload(&PreconditionVerdict::Dispatch, "pay")
            .is_none()
    );
}

#[test]
fn test_refusal_maps_to_structured_policy_violation() {
    let surfaces = PreconditionSurfacesImpl;
    let verdict = PreconditionVerdict::Deny {
        precondition_id: "beneficiary-eligible".to_string(),
        outcome: PreconditionOutcome::Failed,
    };
    let violation = surfaces
        .refusal_payload(&verdict, "pay")
        .expect("a refusal is a structured violation");
    assert_eq!(
        violation,
        PreconditionPolicyViolation {
            precondition_id: "beneficiary-eligible".to_string(),
            step: "pay".to_string(),
            outcome: PreconditionOutcome::Failed,
        }
    );

    // The structured refusal data carries the frozen keys and is non-retriable.
    let data = PreconditionSurfacesImpl::policy_violation_data(&violation);
    assert_eq!(data["type"], "policy_violation");
    assert_eq!(data["precondition_id"], "beneficiary-eligible");
    assert_eq!(data["step"], "pay");
    assert_eq!(data["outcome"], "failed");
    assert_eq!(data["retryable"], false);
}

#[test]
fn test_findings_json_surfaces_evidence_and_redacts_values() {
    // AC #16: `rigorix_validate_plan` surfaces `precondition_findings[]` —
    // evidence fields only, never parameter values or stdout.
    let finding = PreconditionFinding {
        precondition_id: "beneficiary-eligible".to_string(),
        step: "pay".to_string(),
        outcome: PreconditionOutcome::Error,
        exit_code: None,
        inputs_hash: "sha256:deadbeef".to_string(),
        checked_at: Utc::now(),
        summary: Some("precondition 'beneficiary-eligible' error for step 'pay'".to_string()),
        check_digest: Some("sha256:check".to_string()),
        authority_digest: Some("sha256:authority".to_string()),
        check_writable: Some(false),
    };
    let surfaced = PreconditionSurfacesImpl::findings_json(&[finding]);
    assert_eq!(surfaced.len(), 1);
    let entry = &surfaced[0];
    assert_eq!(entry["precondition_id"], "beneficiary-eligible");
    assert_eq!(entry["step"], "pay");
    assert_eq!(entry["outcome"], "error");
    assert_eq!(entry["inputs_hash"], "sha256:deadbeef");
    assert!(entry["checked_at"].is_string());

    let serialized = serde_json::to_string(entry).expect("serialize");
    assert!(!serialized.contains("parameters"));
    assert!(!serialized.contains("stdout"));
}
