// Generated by Guardian TDD
// From: TemplateRepository (Aggregate Root) (template-tools module)
// Tests the frozen contract for TemplateRepository trait.

#[cfg(test)]
mod tests {
    use rigorix_mcp::template_tools::domain::entity::{
        SharedTemplateRepository, TemplateRepository,
    };
    use rigorix_mcp::template_tools::domain::error::TemplateError;
    use rigorix_mcp::template_tools::domain::value::{
        Constraints, PlanTemplate, StepDefinition, TemplateFilter, TemplateSummary,
    };
    use std::sync::Arc;

    /// Helper: create a minimal valid PlanTemplate for testing.
    fn make_test_template(name: &str) -> PlanTemplate {
        let step = StepDefinition::new(
            "step-1".into(),
            "test_tool".into(),
            serde_json::json!({}),
            false,
            "Test step".into(),
            None,
        );
        let now = chrono::Utc::now();
        PlanTemplate::new(
            name.into(),
            "Test description".into(),
            "1.0.0".into(),
            vec![],
            vec![step],
            None,
            std::collections::HashMap::new(),
            now,
            now,
        )
        .expect("Failed to create test template")
    }

    /// Mock repository for testing the TemplateRepository contract.
    struct MockTemplateRepository {
        templates: std::collections::HashMap<String, PlanTemplate>,
    }

    impl MockTemplateRepository {
        fn new() -> Self {
            Self {
                templates: std::collections::HashMap::new(),
            }
        }
    }

    #[async_trait::async_trait]
    impl TemplateRepository for MockTemplateRepository {
        async fn list(
            &self,
            _filter: &TemplateFilter,
        ) -> Result<Vec<TemplateSummary>, TemplateError> {
            Ok(self
                .templates
                .values()
                .map(|t| {
                    TemplateSummary::new(
                        t.name().to_string(),
                        t.description().to_string(),
                        t.version().to_string(),
                        t.tags().to_vec(),
                        t.steps().len(),
                        *t.updated_at(),
                    )
                })
                .collect())
        }

        async fn get(&self, name: &str) -> Result<PlanTemplate, TemplateError> {
            self.templates
                .get(name)
                .cloned()
                .ok_or_else(|| TemplateError::NotFound(name.to_string()))
        }

        async fn create(
            &mut self,
            template: PlanTemplate,
            overwrite: bool,
        ) -> Result<(), TemplateError> {
            let name = template.name().to_string();
            if !overwrite && self.templates.contains_key(&name) {
                return Err(TemplateError::AlreadyExists(name));
            }
            self.templates.insert(name, template);
            Ok(())
        }

        async fn delete(&mut self, name: &str) -> Result<(), TemplateError> {
            if self.templates.remove(name).is_none() {
                return Err(TemplateError::NotFound(name.to_string()));
            }
            Ok(())
        }

        async fn exists(&self, name: &str) -> Result<bool, TemplateError> {
            Ok(self.templates.contains_key(name))
        }
    }

    #[tokio::test]
    async fn test_template_repository_create_and_get() {
        let mut repo = MockTemplateRepository::new();
        let template = make_test_template("test-template");

        repo.create(template.clone(), false)
            .await
            .expect("Failed to create template");

        let retrieved = repo.get("test-template").await.expect("Failed to get template");
        assert_eq!(retrieved.name(), "test-template");
        assert_eq!(retrieved.steps().len(), 1);
    }

    #[tokio::test]
    async fn test_template_repository_already_exists_without_overwrite() {
        let mut repo = MockTemplateRepository::new();
        let template = make_test_template("duplicate");

        repo.create(template.clone(), false)
            .await
            .expect("First create should succeed");

        let err = repo.create(template.clone(), false).await.unwrap_err();
        assert!(
            matches!(err, TemplateError::AlreadyExists(_)),
            "Expected AlreadyExists error, got: {:?}",
            err
        );
    }

    #[tokio::test]
    async fn test_template_repository_overwrite() {
        let mut repo = MockTemplateRepository::new();
        let template1 = make_test_template("overwrite-me");
        let template2 = make_test_template("overwrite-me");

        repo.create(template1, false)
            .await
            .expect("First create should succeed");

        // Overwrite should succeed with overwrite=true
        repo.create(template2, true)
            .await
            .expect("Overwrite should succeed");
    }

    #[tokio::test]
    async fn test_template_repository_not_found() {
        let repo = MockTemplateRepository::new();
        let err = repo.get("nonexistent").await.unwrap_err();
        assert!(
            matches!(err, TemplateError::NotFound(_)),
            "Expected NotFound error, got: {:?}",
            err
        );
    }

    #[tokio::test]
    async fn test_template_repository_exists() {
        let mut repo = MockTemplateRepository::new();
        let template = make_test_template("exists-check");

        let exists_before = repo.exists("exists-check").await.expect("exists check should succeed");
        assert!(!exists_before, "Template should not exist before creation");

        repo.create(template, false)
            .await
            .expect("Create should succeed");

        let exists_after = repo.exists("exists-check").await.expect("exists check should succeed");
        assert!(exists_after, "Template should exist after creation");
    }

    #[tokio::test]
    async fn test_template_repository_delete() {
        let mut repo = MockTemplateRepository::new();
        let template = make_test_template("to-delete");

        repo.create(template, false)
            .await
            .expect("Create should succeed");

        repo.delete("to-delete")
            .await
            .expect("Delete should succeed");

        let exists = repo.exists("to-delete").await.expect("exists check should succeed");
        assert!(!exists, "Template should not exist after deletion");
    }

    #[tokio::test]
    async fn test_template_repository_delete_not_found() {
        let mut repo = MockTemplateRepository::new();
        let err = repo.delete("nonexistent").await.unwrap_err();
        assert!(
            matches!(err, TemplateError::NotFound(_)),
            "Expected NotFound error, got: {:?}",
            err
        );
    }

    #[tokio::test]
    async fn test_template_repository_list_empty() {
        let repo = MockTemplateRepository::new();
        let filter = TemplateFilter::default();
        let results = repo.list(&filter).await.expect("List should succeed");
        assert!(results.is_empty(), "Expected empty list");
    }

    #[tokio::test]
    async fn test_template_repository_list_with_templates() {
        let mut repo = MockTemplateRepository::new();
        repo.create(make_test_template("alpha"), false)
            .await
            .expect("Create should succeed");
        repo.create(make_test_template("beta"), false)
            .await
            .expect("Create should succeed");

        let filter = TemplateFilter::default();
        let results = repo.list(&filter).await.expect("List should succeed");
        assert_eq!(results.len(), 2, "Expected 2 templates");
    }

    #[tokio::test]
    async fn test_template_repository_is_send_sync() {
        // Verify TemplateRepository trait is Send + Sync by wrapping in Arc
        let repo: SharedTemplateRepository = Arc::new(MockTemplateRepository::new());
        let filter = TemplateFilter::default();
        let _ = repo.list(&filter).await;
    }
}
